Reflection_Engine/Query/CurrentAssemblyFolder.cs
Reflection_Engine/Reflection_Engine.csproj

Fixes #765.
Should be easy enought to test:

Reflection_Engine - Issue 765 - Method to get the current location of the executing BHoM dlls

---

Serialiser_Engine/Objects/MemberMapConventions/ImmutableBHoMClassMapConvention.cs

Closes #767 
Removing requirement for IImmutable class map convention to have no empty constructor. Doing this to allow correct serialisation of IImmutable objects where the developer has opted to have an empty standard constructor.
https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/BHoM_Engine/Serializer_Engine/Serialiser_Engine-Issue%20767-Serialisation%20of%20IImutable%20objects.gh?csf=1&e=myIaQc

Serialisation of IImmutable objects, Issue 767

---

Geometry_Engine/Modify/Translate.cs

Closes #777 
Fixes bug in translation for coordinatesystem
https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/BHoM_Engine/Geometry_Engine/Modify/Translate.gh?csf=1&e=5H8FwC
- Bug fixed in `Query.Translate()` for `CoordinateSystem.Cartesian` where the x-axis was wrongly set for the translated coordinate system #777

Bug in translate for CoordinateSystem.Cartesian

---

Serialiser_Engine/Convert/Bson.cs
Serialiser_Engine/Objects/BsonSerializers/CustomObjectSerializer.cs
Serialiser_Engine/Objects/BsonSerializers/ObjectSerializer.cs

Closes #302
https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/BHoM_Engine/Serializer_Engine/Serialiser_Engine-Issue302-FallbackDeserialisation.gh?csf=1&e=oQMEFJ
legacy BHoM objects stored in Bson/Json format will now deserialise into a custom objects instead of returning nothing. 
Notice there are two reasons an object can fail to deserialise:
and
This is the first step of a proper handling of legacy objects. See issue #779 for what comes next. For those wondering, the saving and recovery of the BHoM version will be handled there as it is not needed for this first step.

Serialiser_Engine - Issue 302 - Convert unknown objects into custom objects

---

Structure_Engine/Compute/Integrate.cs
Structure_Engine/Create/ConcreteSection.cs
Structure_Engine/Create/SteelSection.cs

Closes #663 
Adding integrate method for section profile, centring all sections around the global origin. Changed the SteelSectionFromProfile and ConcreteSectionFromProfile to call this method instead.
[Section Curve Alignment.zip](https://github.com/BHoM/BHoM_Engine/files/2868662/Section.Curve.Alignment.zip)

Centring Sections around the origin

---

Environment_Engine/Query/MatchSpace.cs
Environment_Engine/Query/Spaces.cs

Fixes #806 
N/A
- `MatchSpaces` method
- Added `CommonSpaceName` method
Deprecates the `MatchSpaces` method

Fix #806 - match spaces method

---

Common_Engine/Common_Engine.csproj
Common_Engine/Compute/DistributeOutlines.cs
Geometry_Engine/Compute/DistributeOutlines.cs
Geometry_Engine/Query/Area.cs
Structure_Engine/Create/PanelPlanar.cs
Structure_Engine/Structure_Engine.csproj

Closes #831  #832 
Test files is located [here](https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/BHoM_Engine/Geometry_Engine/Geometry%26Structure%26Common_Engine-Issues831,832?csf=1&e=mewNjU). BTW, @IsakNaslundBh why is there no `Create.PanelPlanar` test? Weird, as all others are in place ❔ Would be fantastic if you could give it a proper stress-test.
Small fix to `Area(PolyCurve)`.
`DistributeOutlines` method has been migrated from Geometry_Engine to Common_Engine, which will allow using it in other projects more efficiently. PanelPlanar constructor headers stay the same, only the body changed. All previous methods related to `DistributeOutlines` have been deprecated.

Geometry&Structure&Common_Engine-Issues831,832-PolyCurveAreaFix&DistributeOutlinesMigration

---

Reflection_Engine/Modify/SetPropertyValue.cs

Closes #835
Adding warning message if property is set to custom data and the object worked on is not a custom object
https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/BHoM_Engine/Reflection_Engine/Reflection_Engine-Issue835-SetPropertyWarnings.gh?csf=1&e=65IhPI

Reflection_Engine - Warning message for set property

---

Environment_Engine/Modify/MergeBuildingElements.cs
Environment_Engine/Modify/SetBuildingElementType.cs

Fixes #845 
Rhino to BHoM workflow previously provided
- Fixed issue with merging building elements to take the one with the smallest area as the returned element.
This is for the Rhino to BHoM workflow, and an alpha installer could be created from this merge.

Environment engine merge BE issue

---

Environment_Engine/Query/ExtendedProperties.cs
Environment_Engine/Query/NormalAwayFromSpace.cs

Fixes #846 
Fixes #848 
Rhino to BHoM test files as before
- Added query result for space context properties
- Changed input variable names for `NormalAwayFromSpace` to make more obvious what the input is needed
> As one PR closes, another one opens
I think that's the saying anyway...

Environment engine Space Context Properties

---

Structure_Engine/Query/Geometry.cs

Closes #859 
Adding Geometry() method to the PanelPlanar returning a PlanarSurface
All panels should now automatically display their centre plane geometry, so any GH script using PanelPlanar should work for testing this.
Also, see simple script here:
https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/BHoM_Engine/Structure_Engine/Structure_Engine-Issue859-GeometryForPanelPlanar?csf=1&e=2LqibL
- Geometry() method added for PanelPlanar automatically displaying its geometry in GH

Structure_Engine: Adding Geometry() method To PanelPlanar

---

Geometry_Engine/Geometry_Engine.csproj
Geometry_Engine/Query/Area.cs
Geometry_Engine/Query/Centroid.cs
Geometry_Engine/Query/Normal.cs

Closes #343 
Closes #637
Adding methods centroid(polyline) calculating a center of mass of planar polyline and centroid(polycurve) for planar polycurve (consisting of arcs and lines only).
Adding methods for polylines and polycurves to Normal() calculating normal vector; always according to the right-hand rule.
[Here](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FBHoM%5FEngine%2FGeometry%5FEngine%2FGeometry%5FEngine%2DIssues343%2C637%2DCentroidAndNormalOfACurve) is the GH test file for both methods.
**Added:**
- Centroid(Polyline), Centroid(PolyCurve)
- Normal(Polyline), Normal(PolyCurve)
There are some errors (less than 0,5% of tested samples) in Normal(PolyCurve) method. In my …

Geometry engine issues 343, 637 centroid and normal of a curve

---

Reflection_Engine/Compute/OpenHelpPage.cs
Reflection_Engine/Query/Url.cs
Reflection_Engine/Reflection_Engine.csproj
Structure_Engine/Properties/AssemblyInfo.cs

https://github.com/BHoM/BHoM/pull/436
Closes #863 
This code supports the functionality of the UI to open a webpage when clicking on the "help" of the component. It retrieves the url of the method or object from assembly and type info.
The query is based on the way we structure the files in the project, so if an object is not compliant - i.e. the file that contains it is not in the right place - the web page would report 404.
The `AssemblyUrl` attribute is the one used to store the info about the remote repo web address.
It sits in the Reflecion_oM, so one weakness of this is that all the projects that want to implement the functionality will have a dependency on the Reflection_oM. The alternative is to use attributes that already exist, such as `AssemblyProduct`.

Reflection entgine issue863 assembly url attribute

---

Reflection_Engine/Query/Description.cs
Reflection_Engine/Query/ImplementedTypes.cs
Reflection_Engine/Reflection_Engine.csproj

Closes #878
This PR changes the way `interface`s are described in the UIs, by appending all the types that implement the interface to the string.
For example:
If you have `ICurve`, the tooltip in the UI displays only "ICurve".
It now displays: "ICurve: Arc, Circle, Ellipse, Line, Polyline, Polycurve" and all the others I forgot to add.
If the number of types is more than 15, it stops and ends with "...and more".
NB. It does not work yet for lists where the generic type is an interface.
Hover on the parameters to get the description.
https://burohappold.sharepoint.com/:f:/s/BHoM/EpZu2DXIL1VGlms6O3XwBz4BZ6usNVH1NeF0FILz3bVy_A?e=cFUgFK

Solves #878

---

Structure_Engine/Modify/SetInternalElements2D.cs

Closes #887  
Cannot think of one 😸 But needed for the operations on the IElements2D.

Structure_Engine-Issue887-MakeSetInternalElements2DNotReturnNull

---

Common_Engine/Common_Engine.csproj
Common_Engine/Compute/DistributeOutlines.cs
Common_Engine/Query/Normal.cs
Structure_Engine/Create/PanelPlanar.cs

Closes #886 
Closes #889 
No test file for the Normal method (I believe #872 should be enough), a DistributeOutlines test file is [here](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F02_Current%2F12_Scripts%2F01_Test%20Scripts%2FBHoM_Engine%2FCommon_Engine%2FCommon_Engine-Issues886%2C889-RightHandNormalAndDistributeOutlinesFix) - this one should also be safe.
Added Normal method for an IElement2D + an extra argument that makes the `DistributeOutlines` method work correctly on the IElement2D that do not allow cutting holes.

Common_Engine-Issues886,889-RightHandNormalAndDistributeOutlinesFix

---

Library_Engine/Query/Libraries.cs

Closes #900 
Updated m_SourceFolder in libraries.cs to use appdata instead of account username.
BHoM\DataSets Should now be found for everyone.

Fixes #900 updated m_SourceFolder to use appdata

---

Serialiser_Engine/Convert/Json.cs

Closes #906
When a JsonArray is parsed via `FromJson` method, the method returns the BsonIterator instead of the entire list.
https://burohappold.sharepoint.com/:f:/s/BHoM/EnPlQvcelkhGihJYzsRDPo0BbzhBqgeFxAw564xkVEpUNA?e=m0E5DF

Serialiser_Engine: Return list when FromJson parses a json array

---

Geometry_Engine/Compute/SortAlongCurve.cs
Geometry_Engine/Modify/Join.cs
Geometry_Engine/Modify/SplitAtPoints.cs
Geometry_Engine/Query/ClosestPoint.cs
Geometry_Engine/Query/CurveIntersections.cs
Geometry_Engine/Query/Distance.cs
Geometry_Engine/Query/IsCoplanar.cs
Geometry_Engine/Query/IsOnCurve.cs
Geometry_Engine/Query/Normal.cs

Closes #880 
Closes #896 
Test files are [here](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FBHoM%5FEngine%2FGeometry%5FEngine%2FGeometry%5Fengine%2Dissues%2D880%2C896%2DSplitAtPoints%2DSortAlongCurve%2DDistance%2Detc)
New methods added:
- SortAlongCurve: Arc, Circle, PolyCurve
- SplitAtPoints: Arc, Circle PolyCurve
- Normal: Arc
Rewrited code for new inputs:
- IsCoplanar: PoluCurve (rewrited from polylines)
- IsOnCurve: everything but nurbs and ellipse. (Refer to Distance())
- Join: List PolyCurve (rewrited from Join(List ICurve))
- CurveIntersections: PolyCurve, PolyCurve (rewrited from CurveIntersections(ICurve, ICurve))
Fixed:
- ClosestPoint(Arc,Point) now checks if the point is …

Geometry_engine-issues-880,896-SplitAtPoints-SortAlongCurve-Distance-etc

---

Structure_Engine/Create/FramingElement.cs
Structure_Engine/Create/FramingElementProperty.cs
Structure_Engine/Query/AnalyticalBars.cs

Closes #802 
- Adding new Create method for FramingELement accepting ICurve isntead of just Line
- Deprecating old Create method for FramingElement
- Adding description for Create method for ConstantFramingElementProperty and taking name from SectionProperty if no name is provided
- Updating AnalyticalBars method to handle non-linear elements
https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/BHoM_Engine/Structure_Engine/Structure_Engine-Issue802-UpdateFramingElementMethods?csf=1&e=CfEsTr

Structure_Engine: Updating FramingELementProperties to handle non-linebased centreliens

---

Geometry_Engine/Create/Cone.cs
Geometry_Engine/Create/Cuboid.cs
Geometry_Engine/Create/Cylinder.cs
Geometry_Engine/Create/Sphere.cs
Geometry_Engine/Create/Torus.cs
Geometry_Engine/Geometry_Engine.csproj

Closes #917
Addition of simple Create methods in the Engine for the Primate Solids:
https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02_Current%2F12_Scripts%2F01_Test%20Scripts%2FBHoM_Engine%2FGeometry_Engine%2FGeometry_Engine-issue917-PrimativeSolidCreate&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4
See related but not dependant issue raised here: 
https://github.com/BHoM/Rhinoceros_Toolkit/issues/93

Geometry engine #917 create methods for solids

---

Environment_Engine/Modify/SetConstruction.cs
Environment_Engine/Query/Absorptance.cs
Physical_Engine/Create/Layer.cs

Fixes #958 
Fixes #955 
Current macro test files
- Changed function for setting construction by type as per #958 to allow multiple type names to be given
- Changed Absorptance method to provide protection in the event of a `null` absorptance object
- Changed input description for Physical Layer Create method
- Added function to set constructions by type for hosted openings

Environment_Engine: Set construction by type

---

Geometry_Engine/Compute/BooleanIntersection.cs

Closes #941 
Test file is [here](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F02_Current%2F12_Scripts%2F01_Test%20Scripts%2FBHoM_Engine%2FGeometry_Engine%2FGeometry_Engine-Issue941-AddBooleanIntersectionForBoundingBoxes), the method has been also added to the standard BooleanIntersection test file.
Added BooleanIntersection for the BoundingBoxes.

Geometry_Engine-Issue941-AddBooleanIntersectionForBoundingBoxes

---

Geometry_Engine/Query/IsContaining.cs

Closes #918 
As mentioned in comment in PR #920 updating and properly testing new methods.
Old methods did not include tolerance and AcceptOnEdge bool.
I also changed them a bit after merge in PR #920 .
Test file is [here](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?newTargetListUrl=%2Fsites%2FBHoM%2F02_Current&viewpath=%2Fsites%2FBHoM%2F02_Current%2FForms%2FAllItems%2Easpx&id=%2Fsites%2FBHoM%2F02_Current%2F12_Scripts%2F01_Test%20Scripts%2FBHoM_Engine%2FGeometry_Engine%2FQuery)
Updated:
- IsContaining(this BoundingBox box1, BoundingBox box2)
- IsContaining(this BoundingBox box, Point pt)
- IsContaining(this BoundingBox box, IGeometry geometry)
Added:
-  IsContaining(this BoundingBox box, List<Point> pts)
- We discussed with @pawelbaran the matter of BBoxes …

Geometry_Engine: Issue918 Update IsContaining for BoundingBoxes

---

Reflection_Engine/Query/IsDeprecated.cs

Closes #985
Adding the interface method for the `IsDeprecated` method and its fallback overload.
https://burohappold.sharepoint.com/:u:/s/BHoM/EXrxcHTxIZZAurC0B--VmVIBiwvHM-fLgK1I26GVy6XW1A?e=OtrxJ5

Reflection_Engine: Add IsDeprecated interface method

---

Geometry_Engine/Compute/ClusterCoplanar.cs
Geometry_Engine/Modify/SplitAtPoints.cs
Geometry_Engine/Query/CurveIntersections.cs
Geometry_Engine/Query/IsCoplanar.cs
Geometry_Engine/Query/LineIntersections.cs
Geometry_Engine/Query/ParameterAtPoint.cs

Closes #963 
Closes #989
Closes #991 
Added interfaces for `ClusterCoplanar` and `IsCoplanar`.
Fixed minor bug that occurred with some of closed polycurves in `SplitAtPoints`
Fixed bug in `CurveIntersections` and `LineIntersections` which caused in returning same intersection points twice.
Fixed bug in `ParameterAtPoint(arc, point)` causing in returning wrong values for negative angles
[IsCoplanar](https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/BHoM_Engine/Geometry_Engine/Query/IsCoplanar.gh?csf=1&e=dFdFca) regular
[ClusterCoplanar](https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/BHoM_Engine/Geometry_Engine/Compute/ClusterCoplanar.gh?csf=1&e=wJx339) regular …

Geometry engine issues963,989 intersections bug and methods for boolean interfaces

---

Geometry_Engine/Compute/Join.cs
Geometry_Engine/Modify/SplitAtPoints.cs
Geometry_Engine/Query/IsClockwise.cs
Geometry_Engine/Query/IsCoplanar.cs

closes #1008
addresses #980
Fixed `Join (List<ICurve>)` so now if there is PolyCurve as input it will stay unchanged and will not be wrapped into another PolyCurve.
Updated `SplitAtPoints`, `IsClockwise` and `IsCoplanar` `(PolyCurve)` so now when a Circle is a part of PolyCurve, these methods would return correct values. Also created `IsClockwise(Circle)`.
Join - regular test [file](https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/BHoM_Engine/Geometry_Engine/Modify/Join.gh?csf=1&e=Dt1zjb)
SplitAtPoints, IsClockwise and IsCoplanar - [issue specific test](https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/BHoM_Engine/Geometry_Engine/Geometry_Engine-issue980-CircleInPolycurveIssue/Geometry_Engine-issue980-Circ …

Geometry_Engine: issues 980, 1008: Join(iCurve) bug and Circles inside PolyCurves

---

Common_Engine/Common_Engine.csproj
Common_Engine/Query/Bounds.cs
Geometry_Engine/Query/Bounds.cs
Geometry_Engine/Query/Edges.cs
Geometry_Engine/Query/IsInRange.cs
Geometry_Engine/Query/PlaneIntersection.cs

Closes #1019 
Closes #1020 
Added regular test files:
- `Bounds(IElement)` - [here](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FBHoM%5FEngine%2FCommon%5FEngine%2FQuery) 
- `Edges(BoundingBox)`, `PlaneIntersection(BoundingBox, Plane)` and `IsInRange(Point/ICurve, BoundingBox)` - [here](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FBHoM%5FEngine%2FGeometry%5FEngine%2FQuery)
Errors in the test files are caused by:
- `IsInRange(Point, BoundingBox)` - inbuilt tolerance of Rhino being different from BHoM
- `IsInRange(ICurve, BoundingBox)` - nulls being returned due to lack of support of …

GeometryCommon_Engine-Issues1019,1020-BoundingBoxMethods

---

Environment_Engine/Query/UniqueConstructions.cs

Fixes #1039 
Existing Test Scripts on Constructions
- Fixed handling of `null` constructions when getting unique constructions for certain toolkits

Environment_Engine: Fix handling null constructions

---

Geometry_Engine/Compute/BooleanDifference.cs
Geometry_Engine/Compute/BooleanIntersection.cs
Geometry_Engine/Compute/BooleanUnion.cs
Geometry_Engine/Modify/SplitAtPoints.cs

closes #924 
Added Interfaces for boolean methods. Now they work on both PolyCurves and Polylines as one input. Circles are are also implemented as singular Circles and as a parts of a PolyCurves. To be discussed is if we need separate Polyline, PolyCurve and Interface methods. I think we could have one method for Polylines as it is faster than others and one universal method for the rest (including Polylines). Method for only PolyCurves is a bit redundant.
I also did some updates in all boolean methods as there appeared new egde cases :wink:
However there are some issues with performance. In some cases BhoM methods are much faster then GH's, but they also can be slower. I give some examples in the thest file.
Regular [Intersection](https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Cu …

Geometry_Engine: #924 Add Interfaces to Boolean Intersection / Union / Difference

---

Reflection_Engine/Modify/SetPropertyValue.cs
Reflection_Engine/Query/PropertyValue.cs

Closes #982
Get method for nested properties allows to use the form `PropOne.PropTwo` as input in the GetProperty method.
The `SetPropertyValue`, at the moment, cannot work that way. The BHoM_Engine project, where the `DeepClone` resides, references the Reflection_Engine. Trying to use any cloning functionality would result in a circular dependency.
https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/BHoM_Engine/Reflection_Engine/Reflection_Engine-Issue985-IsDeprecatedInterfaceMethod/ReflectionEngine-Issue982-GetSetNestedProperties.gh?csf=1&e=2RnGdv

Reflection engine issue982 get set nested properties

---

Geometry_Engine/Query/ClosestPoint.cs

Closes #1053 
Issue specific test file is [here](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FBHoM%5FEngine%2FGeometry%5FEngine%2FGeometry%5FEngine%2DIssue1053%2DClosestPointToCircleBugWhenPointInCenter).
- `Query.ClosestPoint()` method with distance tolerance added in the Geometry_Engine for `Circle` class
- `Query.ClosestPoint()` method without distance tolerance deprecated in the Geometry_Engine for `Circle` class, replaced with similar method taking the distance tolerance

Geometry_Engine-Issue1053-ClosestPointToCircleBugWhenPointInCenter

---

Common_Engine/Query/Area.cs
Common_Engine/Query/Centroid.cs
Geometry_Engine/Compute/BooleanUnion.cs
Geometry_Engine/Query/Centroid.cs

Closes #1016 
Updated `Area(IElement2D)` so now it operates on any ICurve.
Created `Centroid(IElement2D)`. It needed a small fix in Geometry_Engine Centroid.
Also found bug in `BooleanUnion(IEnumerable<ICurve>)` and fixed it.
Area - regular test [file](https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/BHoM_Engine/Common_Engine/Query/Area.gh?csf=1&e=xBHseu)
Centroid - regular test [file](https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/BHoM_Engine/Common_Engine/Query/Centroid.gh?csf=1&e=D3MKCl)
BooleanUnion - regular test [file](https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/BHoM_Engine/Geometry_Engine/Compute/BooleanUnionV3.gh?csf=1&e=mBTTjA)
BooleanUnion - …

Common_Engine: issue 1016 Update Area and Centroid and fix Gemetry_Engine BooleanUnion bug

---

Geometry_Engine/Query/Bounds.cs

Closes #1004 
Dedicated test file located [here](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FBHoM%5FEngine%2FGeometry%5FEngine%2FGeometry%5FEngine%2DIssue1004%2DIBoundsMethodBreaksIfObjectIsNull).
- Added null checks that prevent the code from breaking when no geometrical bounds are found for an object
Should not interfere with #1022 as modifying different files.

Geometry_Engine-Issue1004-IBoundsMethodBreaksIfObjectIsNull

---

Common_Engine/Query/ElementCurves.cs
Common_Engine/Query/ElementVertices.cs

Closes #1077 
Not liking myself, but no test file added - it did not exist and I have not created one. The methods are used in dependent projects and everything seems to be fine.
- `Query.ElementCurves()` method added in the `Common_Engine` for `IElement` interface
- `Query.ElementVertices()` method added in the `Common_Engine` for `IElement` interface
- `Query.ElementCurves()` method deprecated in the `Common_Engine` for `BHoMObject` interface
- `Query.ElementVertices()` method deprecated in the `Common_Engine` for `BHoMObject` interface

Common_Engine-Issue1077-ChangeArgumentTypeFromBHoMObjectToIElement

---

Environment_Engine/Create/Gain.cs

https://github.com/BHoM/BHoM/pull/518
N/A - this does not resolve the issue in #1078, but it allows the engine to compile against BHoM. The changes to #1078 will be made tomorrow.
N/A
Note dependency PRs

Environment_Engine: Temporary fix of #1078 - more to do for proper though

---

Reflection_Engine/Query/PropertyValue.cs

Closes #1081 
In `Query.PropertyValue`, excluding `CustomObject`s from logging that the property is stored in the `CustomData` - as it is too verbose.
https://burohappold.sharepoint.com/:f:/s/BHoM/EpwKcoP9VTVGkssT71fhu7UBwMljIT4OTG1hmp96BH5MZw?e=HWJFe7

Reflection_Engine: Issue1081-RemoveLoggingForGetPropertyAndCustomObjects

---

Geometry_Engine/Query/Bounds.cs
Geometry_Engine/Query/Degree.cs
Geometry_Engine/Query/UVCount.cs

Closes #1094 
In order to reinstate the ability to convert `NurbsSurface` to and from Rhinoceros.
See the issue for more.
I simply reinstated the code that was in these commits, which, for the sake of celerity, I assume it is correct. The test file will come with the associated Grasshopper pull request.
- Add `BH.Engine.Geometry.Query.UVCount()`
- Add `BH.Engine.Geometry.Query.Degrees()`
- Add `BH.Engine.Geometry.Query.Bounds(NurbsSurface)`

Geometry_Engine: re-implement UVCount() and Degrees()

---

Environment_Engine/Compute/MergeBuildingElements.cs
Environment_Engine/Query/IsContaining.cs
Environment_Engine/Query/Level.cs
Environment_Engine/Query/Panels.cs

Fixes #1105 
Being developed - but feel free to test on existing scripts
- Added ability to filter Environment Panels by level

Environment_Engine: Panels by level filter

---

BHoM_Engine/Query/FilterByType.cs
Environment_Engine/Environment_Engine.csproj
Environment_Engine/Modify/AddOpening.cs
Environment_Engine/Query/Buildings.cs
Environment_Engine/Query/Level.cs
Environment_Engine/Query/Openings.cs
Environment_Engine/Query/Panels.cs
Environment_Engine/Query/Spaces.cs
Physical_Engine/Physical_Engine.csproj
Physical_Engine/Query/Doors.cs
Physical_Engine/Query/Floors.cs
Physical_Engine/Query/Polyline.cs
Physical_Engine/Query/Roofs.cs
Physical_Engine/Query/Walls.cs
Physical_Engine/Query/Windows.cs

Fixes #1114 
Fixes #1115 
Fixes #1116 
Existing test scripts for physical workflow from Revit
- Add query methods to extract physical objects from collections of BHoM objects to the Physical Engine
- Add query methods to obtain polyline representations of Physical objects to the Physical Engine
- Add query methods to obtain Environment representations of Physical objects to the Environment Engine
- Move method from Environment Engine to BHoM Engine to query objects by type for use by multiple engines

Physical_Engine: Query methods for topology workflows

---

Environment_Engine/Compute/EquipmentGain.cs
Environment_Engine/Compute/LightingGain.cs
Environment_Engine/Compute/PeopleGain.cs
Environment_Engine/Compute/PlugGain.cs

Fixes #1112 
Existing scripts
- Added default inputs to gain computes to return gains even if not all gains are required (e.g. sensible/latent)
This addresses item 1 of the issue referenced. The other items are being ignored for now while gain refactoring is done between @michaldengusiak and @kayleighhoude

Environment_Engine: Add defaults for gain computes to allow gains to be returned

---

Reflection_Engine/Query/UnderlyingType.cs

Closes #703
`Engine.Reflection.Query.UnderlyingType` currently returns the wrong depth for array types, this pr solves it.
Note: a multidimensional array (`int[,]`) has depth of 1. A jagged array (`int[][]`) has depth equals to its nesting levels (2 in this case).
https://burohappold.sharepoint.com/:f:/s/BHoM/EjmxIfvj4WNBvi9qWzVvunoBwjYJX03lohJTTu8WHAxAhA?e=5F10sa
- Update the `Engine.Reflection.Query.UnderlyingType` to return the correct depth for the `Array`  type.

Reflection_Engine  - Issue 703 - Fix Depth of Arrays in UnderlyingType

---

Planning_Engine/Create/Milestone.cs

https://github.com/BHoM/BHoM/pull/548
Closes #1168

Planning_Engine : Update Create method to include Description Property

---

Geometry_Engine/Query/Centroid.cs
Geometry_Engine/Query/Normal.cs

Fixes #1156 
Fixes #1157 
N/A
- Expose tolerance parameter on `Normal` query for `Curve` inputs
- Expose tolerance parameter on `Centroid` query for `Curve` inputs
- Deprecate existing `Normal` and `Centroid` queries as a result of the above
This exposes tolerances for methods which can utilise tolerances to provide greater control when utilising these geometry methods within code and visual programming.

Geometry_Engine: Expose tolerances

---

Geometry_Engine/Geometry_Engine.csproj
Geometry_Engine/Modify/CleanPolyline.cs
Geometry_Engine/Modify/RemoveLeastSignificantVertices.cs
Geometry_Engine/Modify/RemoveShortSegments.cs
Geometry_Engine/Query/Centroid.cs

Fixes #1173 
[Existing](https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/BHoM_Engine/Geometry_Engine/CleanPolyline.gh?csf=1&e=mpq5Kw)
- Rename `distanceTolerance` to `minmumSegmentLength` in `CleanPolyline`
- Add `RemoveLeastSignificantVertices` method separately from `CleanPolyline` for greater user control
- Add `RemoveShortSegments` method separately from `CleanPolyline` for greater user control
- Modify `CleanPolyline` to use the two separate methods
- Add `tolerance` to all `centroid` methods
Tolerance added to all Centroid methods per PR comment https://github.com/BHoM/BHoM_Engine/pull/1170#issuecomment-529340030

Geometry_Engine: Change variable name to minimumSegmentLength

---

Structure_Engine/Create/RigidLink.cs

Closes #1127 
Added name to create method for `RigidLink`.
https://burohappold.sharepoint.com/:u:/s/BHoM/ERKv9v45aXFLrnN-Mxw3rNkBwwe62gb2vTk0av7rrQ-7ow?e=BLG7aU
Added name to create method for `RigidLink`.

Structure_Engine: Closes #1127 Adds name to create method for RigidLink

---

Geometry_Engine/Create/IntegrationSlice.cs
Structure_Engine/Create/ConcreteSection.cs
Structure_Engine/Create/SteelSection.cs

Closes #1160 
Fixing issue with Integrate method crashing for empty `FreeFormProfile`s. 
This has caused the AnalyticalBars method to crash when used on profiles that failed to pull correctly from Revit.
[Test file using analytical bars](https://burohappold.sharepoint.com/:f:/s/BHoM/Eqqz9K_SKOpDu0r41tlnwsoBUS2Ba92z4qamTBZt01ludA?e=df0tNn)

Structure_Engine: Fix crash when integrating empty FreeFormProfiles

---

Environment_Engine/Modify/AddOpening.cs

Fixes #1195 
See issue raised
- Expose `ContainingTolerance` on adding openings
Test script may need updating to use the new method signature for this method.

Environment_Engine: expose multiple tolerance to prevent incorrect opening additions

---

Architecture_Engine/Architecture_Engine.csproj
Architecture_Engine/Create/Grid.cs
Architecture_Engine/Create/Level.cs
Architecture_Engine/Modify/SetGeometry.cs
Environment_Engine/Query/Level.cs
Environment_Engine/Query/Panels.cs
Environment_Engine/Query/StoreyGeometry.cs
Geometry_Engine/Create/SettingOut/Grid.cs
Geometry_Engine/Create/SettingOut/Level.cs
Geometry_Engine/Geometry_Engine.csproj
Geometry_Engine/Modify/SetGeometry.cs

https://github.com/BHoM/BHoM/pull/554
Closes #1203
https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FBHoM%5FEngine%2FArchitecture%5FoM%2F%23536%20%2D%20migration%20of%20grid%20and%20level&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4
- `BH.oM.Architecture.Elements.Grid` and `Level` Creates deprecated.
- `Grid` and `Level` added to `BH.oM.Geometry.SettingOut`
- Environment methods based on `Level` deprecated and updated to utilise `BH.oM.Geometry.SettingOut.Level`

Migrating grids and levels from Architecture to Geometry.SettingOut

---

Structure_Engine/Query/Geometry.cs

Closes #1219 
Updating method name from Geometry to IGeometry for ISectionProperty
Adding fallback method returning null
This was for some cases before causing stack overflow exceptions when trying to get geometry for Sectionproeprties
https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/Grasshopper_Toolkit/Issue403-ExplodeBarsCrash?csf=1&e=wudePW

Structure_Engine: Updating Geometry(this ISectionProperty section) to IGeometry(this ISectionProperty section)

---

Reflection_Engine/Create/Type.cs

Closes #1193
You can find two test files at https://burohappold.sharepoint.com/:f:/s/BHoM/ErItJgi3dcJGuWF4ewszSdYB_vmDJaNuib6ZILMPdx_xOQ?e=APCMLW
I suggest using the one with the suffix "Loop" which actually reproduces the error.

Reflection_Engine: CreateType throws exeptions that stop the data flow in visual programming if in a loop

---

Serialiser_Engine/Convert/Json.cs

Serialiser_Engine: Fix ToJson() method for when input is null

---

Geometry_Engine/Compute/BooleanUnion.cs

Didn't work in certain cases of regions inside regions. Now it does. It applies to both Polyline and ICurve methods.
#1096
Closes #1096
Updated [file with bug](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FBHoM%5FEngine%2FGeometry%5FEngine%2FGeometry%5FEngine%2DIssue1096%2DUnionBug) uploaded by @pawelbaran 
- `Compute.BooleanUnion()` Compute method updated in the `Geometry_Engine` for `Polyline` class
- `Compute.BooleanUnion()` Compute method updated in the `Geometry_Engine` for `ICurve` class

Geometry_Engine #1096 - Fix BooleanUnion bug

---

Geometry_Engine/Modify/SplitAtPoints.cs

Fixed the bug of splitting 360 degree arc and circle having no split points. Also changed `SplitAtPoints(Circle)` output type from `List<Arc>` to `Liast<ICurve.` to allow returning Arcs or Circles. It does not affect any other method
Closes #1057 
Closes #1058 
[Here](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?viewid=a5a93cba%2Dfcca%2D46cc%2Da31a%2D80b8d5cbfd7b&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FBHoM%5FEngine%2FGeometry%5FEngine%2FGeometry%5FEngine%20%231057%20%231058%20%2D%20SplitAtPoints%28%29%20bugs) is the issue specific test and [here](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?viewid=a5a93cba%2Dfcca%2D46cc%2Da31a%2D80b8d5cbfd7b&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F0 …

Geometry_Engine - Fix SplitAtPoints() bugs and change output type

---

Geometry_Engine/Query/PointInRegion.cs

Closes #1242 
Added a protection for when the ICentroid returns null so that PointInRegion can find another PointInRegion 
[Test file](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?csf=1&e=UuLrGh&cid=13698a4a%2Dabca%2D4608%2Db33f%2D5e33f66d98f1&RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FXML%5FToolkit%2FXML%5FToolkit%2DIssue355%5FPushError&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4)

Geometry_Engine Protection if ICentroid returns null

---

Geometry_Engine/Query/Geometry.cs

Closes #1239 
[Here](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?viewid=a5a93cba%2Dfcca%2D46cc%2Da31a%2D80b8d5cbfd7b&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FBHoM%5FEngine%2FGeometry%5FEngine%2FGeometry%5FEngine%2DIssue1239%2DGridIsMissingGeometryMethod).
`Geometry()` query method added to `BH.oM.Geometry.SettingOut.Grid`
Needs to be merged ASAP!

Geometry_Engine - Grid is missing Geometry method

---

Environment_Engine/Environment_Engine.csproj
Environment_Engine/Modify/SetOpeningType.cs

Added SetOpeningType to the Environment_Engine modify. 
Makes it possible to assign a specific opening type to a list of openings.
Closes #1176 
[Test file](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?csf=1&e=HbjegC&cid=2fb09dcd%2D74bf%2D4ca8%2D8984%2Db0b2830f78c0&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4&viewid=a5a93cba%2Dfcca%2D46cc%2Da31a%2D80b8d5cbfd7b&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FBHoM%5FEngine%2FEnvironment%5FEngine%2FEnvironment%5FEngine%2DIssue%2D1176%2DSetOpeningType)

Environment_Engine: Add ability to Set Opening Type

---

Geometry_Engine/Create/TransformMatrix.cs
Geometry_Engine/Geometry_Engine.csproj
Geometry_Engine/Modify/Orient.cs
Geometry_Engine/Modify/Rotate.cs
Geometry_Engine/Modify/Scale.cs
Geometry_Engine/Modify/Transform.cs
Geometry_Engine/Modify/Translate.cs

Closes #1010 
Closes #1236 
Closes #1237 
- Added three new TransformMatrices:
- `OrientationMatrixGlobalToLocal` - transforming geometry from global coordinate systems to given local coordinate system
- `OrientationMatrixLocalToGlobal` - transforming geometry from given local coordinate systems to global coordinate system
- `OrientationMatrix` - transform geometry between two given coordinate systems
- Added new method `Modify.Orient`, which orients geometry between two coordinate systems using `Transform(OrientationMatrix)`. **( IMPORTANT )** With @IsakNaslundBh we came up with an idea to cover all IGeometry classes with one Generics method. It works quite good for Orient so we'd like to hear your opinions and maybe discuss spreading this approach also over Rotate, Scale and Translate …

Geometry engine - Adding an Orient method and Translate, Scale and Rotate methods for Arcs, Circles and Ellipses

---

Structure_Engine/Create/Bar.cs
Structure_Engine/Create/MaterialFragment.cs
Structure_Engine/Query/EmbodiedCarbon.cs
Structure_Engine/Structure_Engine.csproj

Adapting to [BHoM PR 560](https://github.com/BHoM/BHoM/pull/560)
Closes #1230
Added default value for embodied carbon for each material class

Structure_Engine: Add embodied carbon to material fragments

---

Environment_Engine/Environment_Engine.csproj
Environment_Engine/Modify/CleanPanel.cs

Closes #1152 
Clean panel method added to clean panels from short segments and extra control points. 
[Test file](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?csf=1&e=qi5MJa&cid=6a0a6b5b%2D06a5%2D4f34%2D8198%2D92b8c6f54303&RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FBHoM%5FEngine%2FEnvironment%5FEngine%2FEnvironment%5FEngine%2DIssue%2D1152%20CleanPanel&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4)

Environment_Engine: Adding cleanPanel method 

---

Reflection_Engine/Convert/ToText.cs

This assists solving this issue: https://github.com/BHoM/BHoM_UI/issues/124
I honestly don't think this needs testing. Inspection of the code and making it compiles should be enough here. 
Unless you see a reason for the fallback case to not be `member.ToString()` ?

Reflection_Engine: Add a ToText() method for MemberInfo

---

Environment_Engine/Query/Tilt.cs

Closes #1273 
Added distanceTolerance and angleTolerance as input parameters for the Tilt methods.

Environment_Engine: Explose Tilt tolerance parameters

---

Diffing_Engine/Diffing_Engine.csproj

Fixes #1299
If you take a look for the CI checks on BHoM UI that @adecler ran this morning, you'll find this snippet:
This PR aims to remove that warning.

Diffing_Engine: Remove reference to Testing oM

---

Environment_Engine/Environment_Engine.csproj
Environment_Engine/Modify/RemoveOpenings.cs
Environment_Engine/Modify/SplitOpening.cs
Environment_Engine/Modify/SplitPanels.cs
Environment_Engine/Query/Openings.cs

Fixes #1303 
Standard test scripts
- Add function to remove openings
- Add function to split a single opening into multiple openings
- Add function to split a single panel into multiple panels
- Add function to query an opening from a collection of openings by its name

Environment_Engine: Adding manipulation and query methods

---

Environment_Engine/Query/IsContaining.cs

Closes #1217 
Fixes bug on NormalAwayFromSpace which returned "false" even though the the Normal was away from space. Now it returns "true". 
See issue

Environment_Engine: fix NormalAwayFromSpace bug  

---

Geometry_Engine/Create/ShapeProfile.cs

Closes Issue #259
Added code to not make profile components not output inconceivable profiles.
With inconceivable i mean for example where the profile is inside out or it self intersects. With the changes you are still able to make unrealistic profiles structure wise, but not geometry wise. 
- Adding checks for all ratios used to generate section profiles, raising error messages and returning null if the provided values does not generate a functioning profile.
https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?csf=1&e=CJWjNz&cid=0b727f4a%2Daf39%2D4d1d%2D8942%2D0c26c33d7c20&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4&viewid=a5a93cba%2Dfcca%2D46cc%2Da31a%2D80b8d5cbfd7b&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FBHoM%5FEngine%2FG …

Geometry_Engine: Ensures all section profile constructors are correct

---

Geometry_Engine/Convert/NurbsForm.cs
Geometry_Engine/Create/NurbsCurve.cs
Geometry_Engine/Geometry_Engine.csproj
Geometry_Engine/Modify/Rotate.cs
Geometry_Engine/Modify/Scale.cs
Geometry_Engine/Modify/Transform.cs
Geometry_Engine/Modify/Translate.cs

Closes #764 
Closes #960 
Closes #1148 
- Re-enabling conversions of basic geometry into NurbsCurves, heavily inspired by what was disabled in [that commit](
https://github.com/BHoM/BHoM_Engine/commit/ee1643f3403cefb97fe2f845e541d224e7c1ffd0#diff-4d3e0b17ced26bb9f91e2f284a923b9c). Did not implement `ToNurbsCurve(PolyCurve)` as it's hard to implement and not very needed.
- Implementing scaling, rotating and translating (orienting wasn't needed thanks to generics method) for NurbsCurves.
- Implementing Transform for NurbsCurves.
- Changing file name from `NurbCurve` to `NurbsCurve` and implemeting basic creation method.
[Click](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?viewid=a5a93cba%2Dfcca%2D46cc%2Da31a%2D80b8d5cbfd7b&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F1 …

Geometry engine: reenable NurbsCurves

---

Geometry_Engine/Query/Clone.cs

Closes #1307 
- This was actually highlighted when trying to add default value for each input of the new `CreateObject` component (see https://github.com/BHoM/BHoM_UI/pull/152)
- I suppose it might be worth checking if other geometry methods are missing support for `Basis` and fallback method. Something to fix in another PR though as this one is purely to make sure the UI PR is not held up because of this.

Geometry_Engine: Add fallback cases and support for Basis in Clone.cs

---

Serialiser_Engine/Objects/BsonSerializers/ObjectSerializer.cs

https://github.com/BHoM/Versioning_Toolkit/pull/6
See https://github.com/BHoM/Versioning_Toolkit/pull/6 for more details
When a class is modified only internally, there is no `Deprecated` tag used anywhere (since the class is still active, just modified). This makes it very difficult to detect when deserialising another class that has this modified class as one of the inner properties. The only solution I could find here is to deserialise as custom object so the text now only contains upgraded json/bson and then deserialise again. This works fine and doesn't break the case of deleted classes. Make sure you test any case you can think of though as this is probably the part that is most likely to fail in some weird cases.

Serialiser_Engine: Handle the case of a class containing another class that was only changed internally

---

Geometry_Engine/Geometry_Engine.csproj
Geometry_Engine/Modify/Extend.cs
Geometry_Engine/Modify/Offset.cs

Closes #1066 
Replacing over-dated #1229.
- Added `Offset` method for `Line`, `Arc`, `Polyline` and `PolyCurve`. `Polycurve` has been rewritten from the top down and now it is based on new private method `Fillet()`. **It is not perfect.** In more complicated cases `Offset` method is very intuitive and does not have one objective solution. I'd say there is no such a thing as a perfect Offset method (even a GrassHopper's one :wink:). This version is the closest I can get us to a proper Offset and is fully functional for most of engineering applications.
- Extended `Extend` method to `Arc`, `Polyline` and `PolyCurve`. Also added an option to choose between tangent extensions or following the curve shape.
- Added three private methods:
- `Fillet(ICurve, ICurve)` - works like Autocad fillet …

Geometry engine: add Offset and Extend methods

---

Geometry_Engine/Compute/ConvexHull.cs
Geometry_Engine/Create/ConvexHull.cs
Geometry_Engine/Geometry_Engine.csproj

Closes #238 
Moved ConvexHull method from create to compute. Deprecated the old method in create.

Geometry_Engine Move ConvexHull

---

Geometry_Engine/Compute/CurveProximity.cs

Closes #1327 
CurveProximity always tried to return both intersection events for some curves, which caused issues when there only was one.
Now it returns the first point of the intersection twice if there is an intersection event.
The method is really not structured to be able to return all closest points
[CurveProximity](https://burohappold.sharepoint.com/:u:/s/BHoM/EW3dPy2DKiBEuYL3nxchY6sBKpYfVyxIj032G682HsQSOg?e=saKZxY)
- `BH.Engine.Geometry.Compute.CurveProximity(Line, Circle)` coplanar curve edge case bug fixed
also @pawelbaran  @FraserGreenroyd  @KonradStolarski  why did it try to return separate intersections (i.e both of two planar circles intersection points)? I thought that this was used in to find distance between curves (and this would cause some intersecting curves to have a …

Geometry_Engine CurveProximity, return single point twice for intersection events

---

Reflection_Engine/Convert/ToText.cs

Closes #1334
You should get something like this when testing the ToText component on method (i.e. full path for method parameters):
Nothing depends on this. This is purely to help users generate the correct string when adding a method upgrader to the versioning engine.

Reflection_Engine: Add possibility to include full path for parameters in method.ToText()

---

Serialiser_Engine/Objects/BsonSerializers/ObjectSerializer.cs

Fixes #1337 
[Here](https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/BHoM_Engine/Serializer_Engine/ROI_Rhino%20to%20IES_RoomReference(1).gh?csf=1&e=pitETz)
During an investigation into Excel problems with @awakeman and @IsakNaslundBh today, it was discovered that some old scripts weren't loading following a change to fragment structure done by myself and @alelom . Namely, the PR to Serialiser_Engine of the 9th November suddenly caused old scripts not to deserialise.
The line which appeared to be causing it was `object result = Convert.FromBson(customObject.ToBson());` it appeared to be getting recursively stuck and never moving onto the next line.
Commenting out this line (and then removing it) appeared to fix the problem, in so much as the …

Serialiser_Engine: Remove attempt to re-deserialise a custom object

---

Structure_Engine/Create/Loadcombination.cs

Closes #1336 
https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/BHoM_Engine/Structure_Engine/Issues?csf=1&e=CNo5DP
- Prevent load combinations from adding a null loadcase where a case factor is input without a corresponding loadcase.
To test, open the spreadsheet and try combinations into a clean Robot/analysis model. The spreasheet includes reference to cells with no loadcase, so the null check removes these and allows the combinations to be created.

Structure_Engine: Add null check for load combination create method

---

Reflection_Engine/Compute/UnqualifiedName.cs
Reflection_Engine/Reflection_Engine.csproj
Serialiser_Engine/Objects/MemberMapConventions/GenericDiscriminatorConvention.cs

Closes #1340
- For the bug fix itself:
https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/BHoM_Engine/Serializer_Engine/Serialiser_Engine-Issue1340-FailingToDeserialiseLoads.gh?csf=1&e=qhxese
- To make sure nothing is broken on the backward compatibility side
https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/Versioning_Toolkit/Issue5_deserialise_Test.gh?csf=1&e=Ke9V5v
- To make sure `UnqualifyName` method work in all case:
https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/BHoM_Engine/Reflection_Engine/Serialiser_Engine-Issue1340-UnqualifyName.gh?csf=1&e=ggdhbU
Notice that I unqualify the name on both sides (nominalType and discriminator) because Type.ToString() …

Serialiser_Engine: Fix deserialisation of generic types

---

Structure_Engine/Create/IResultRequest.cs
Structure_Engine/Structure_Engine.csproj

Closes #1347 
Add method to turn type to appropriate IResultRequest. Main reason behind method is to be used by adapters to turn a simple filterRequest of a result type into the appropriate IResultRequest.
https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/BHoM_Engine/Structure_Engine/Issues/Issue1347-ResultRequestFromType?csf=1&e=kR4Rdb
Will need this to be able to make significant cleanups of the structural adapters for result extraction, so would be nice to get this reviewed as soon as possible! Thanks!

Adding Create method for IResultRequest from type

---

Reflection_Engine/Convert/ToFunc.cs

Closes #1345 
As described in the issue, when calling an instance method from the UI, the instance itself is passed as an argument. This pr is just removing that from that list.
https://burohappold.sharepoint.com/:u:/s/BHoM/EZp-V_m8TcZHmpyYCHk2uUIBazpG9AAh-flvoFqsMo9IYw?e=BdiNrm
- Fix inputs handling when dealing with instance methods in the UI

Reflection_Engine: Remove the instance from the list of arguments when calculating an instance method

---

Environment_Engine/Create/SpaceTime.cs

Closes #1355 
Hours are now assigned correctly to the SpaceTime object.
[SpaceTime-Hours.zip](https://github.com/BHoM/BHoM_Engine/files/3901219/SpaceTime-Hours.zip)

Environment_Engine: SpaceTime create-method now assigns hour-values correctly

---

Geometry_Engine/Compute/FitPlane.cs

Closes #1357 
On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?viewid=a5a93cba%2Dfcca%2D46cc%2Da31a%2D80b8d5cbfd7b&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FBHoM%5FEngine%2FGeometry%5FEngine%2FGeometry%5FEngine%2DIssue1357%2DAddMissingFitPlaneMethods).
- `BH.Engine.Geometry.Compute.FitPlane` methods added for `BH.oM.Geometry.NurbsCurve` and `BH.oM.Geometry.Ellipse`
`FitPlane` for `NurbsCurve` is simply fitting a plane into curve's control points, without taking into account curve's degree, point weights etc. - issue to be raised after this PR gets merged.

Geometry_Engine: Missing FitPlane methods added

---

Geometry_Engine/Query/IsClosed.cs
Geometry_Engine/Query/IsPeriodic.cs

Closes #1359
Closes #1361 
Uploaded to SharePoint [here](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?viewid=a5a93cba%2Dfcca%2D46cc%2Da31a%2D80b8d5cbfd7b&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FBHoM%5FEngine%2FGeometry%5FEngine%2FGeometry%5FEngine%2DIssue1359%2DAddIsPeriodicForNurbsCurve) and [here](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?viewid=a5a93cba%2Dfcca%2D46cc%2Da31a%2D80b8d5cbfd7b&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FBHoM%5FEngine%2FGeometry%5FEngine%2FGeometry%5FEngine%2DIssue1361%2DIsClosedNurbsCurve).
- `BH.Engine.Geometry.Query.IsPeriodic` method added for `BH.oM.Geometry.NurbsCurve`

Geometry_Engine: IsPeriodic added and IsClosed fixed for NurbsCurve

---

Reflection_Engine/Query/IsDeprecated.cs

Closes #1372
1. Create a grasshopper file that has a a SocketAdapter in it.
1. Compile the current branch of the BHoM_Engine and the BHoM_UI
1. Open the Socket_Toolkit, and and the `Deprecated` attribute to the `SocketAdapter` class
1.  Reopen the file you created at 1.
1. Check that it has the "OLD" label on it.
- `Engine.Reflection.IsDeprecated(MethodBase)` now also checks if the class is deprecated

Fixes #1372

---

Reflection_Engine/Query/IsDeprecated.cs

Closes #1376 
This reverts commit ba775cc657704750802f84d893c247ac2c6a1e01.
Reverting previously merged commit due to problems in GH

Revert "Fixes #1372"

---

Reflection_Engine/Query/IsDeprecated.cs

Following https://github.com/BHoM/BHoM_Engine/pull/1373
that had to be reverted, due to a missed bug, with https://github.com/BHoM/BHoM_Engine/pull/1377
Closes https://github.com/BHoM/BHoM_Engine/issues/1372
1. Create a grasshopper file that has a a SocketAdapter in it.
1. Compile the current branch of the BHoM_Engine and the BHoM_UI
1. Open the Socket_Toolkit, and and the `Deprecated` attribute to the `SocketAdapter` class
1.  Reopen the file you created at 1.
1. Check that it has the "OLD" label on it.
- `Engine.Reflection.IsDeprecated(MethodBase)` now also checks if the class is deprecated

Fix issue with Deprecated classes still showing up

---

Environment_Engine/Query/FloorGeometry.cs

Closes #1389 
Change tolerance default to be BH.oM.Geometry.Tolerance.Distance for FloorGeometry query method. 
Add input description.

Environment_Engine Change tolerance default for FloorGeometry

---

Reflection_Engine/Query/Description.cs

This completes PR https://github.com/BHoM/BHoM_UI/pull/173
I have taken the liberty to also include the namespace of a type description when this is a BHoM object. This should help clarifying further how to generate objects for given inputs.

Reflection_Engine: Make sure PropertyInfo have a line describing their type

---

Environment_Engine/Query/Level.cs
Environment_Engine/Query/Openings.cs

Closes #1392 
[Test script](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?viewid=a5a93cba%2Dfcca%2D46cc%2Da31a%2D80b8d5cbfd7b&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FBHoM%5FEngine%2FEnvironment%5FEngine%2FEnvironment%5FEngine%2DIssue%2D1392%20OpeningsByLevel%20query)

Environment_Engine Fix opening query by level

---

Geometry_Engine/Geometry_Engine.csproj
Geometry_Engine/Query/ElementNormal.cs
Geometry_Engine/Query/IsVertical.cs
Physical_Engine/Physical_Engine.csproj
Physical_Engine/Query/Normal.cs
Structure_Engine/Query/IsVertical.cs
Structure_Engine/Query/Normal.cs

Closes #1401 
Adds a method for getting the Normal (Z-axis) of a IFramingElement and a central method in the Geometry_Engine which mirrors the existing one in the Structure_Engine.
Named the file in Geometry_Engine `ElementNormal` since it already existed a `Normal.cs` with other kinds of normal, but it still doesn't feel like the right place for it.
The `orientationAngle` should rotate the default normal around an axis, and for a curved element, is that the initial direction, start/end point or something else? Almost feels like one would like to be able to query the normal at every point of the element.
A very low amount of change to a curved element can flip the default normal:
@IsakNaslundBh That feels very unsafe, it is however technically not a problem yet because... (turns out I …

Physical_Geometry_Engine: Add `Normal` method for IFramingElement

---

BHoM_Engine/Query/ShallowClone.cs

Closes #1419 
Creating a new `FragmentSet` when object is being cloned using `ShallowClone`

BHoM_Engine: Instantiating new FragmentSet in ShallowClone method

---

Geometry_Engine/Modify/Offset.cs

Fixing a bug that occurred while offsetting a PolyCurve consisting of Arcs which were parts of one circle.
Closes #1407 
[Same file](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?viewid=a5a93cba%2Dfcca%2D46cc%2Da31a%2D80b8d5cbfd7b&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FBHoM%5FEngine%2FGeometry%5FEngine%2FGeometry%5FEngine%2DIssue1407%2DOffsetArcsIntoCircleBug) that was in the issue.
- `Modify.Offset()` method updated in the `Geometry_Engine` for `PolyCurve` class.
- `Modify.Fillet()` private method updated in the `Geometry_Engine`.

Geometry Engine: fix Offset(PolyCurve) Arcs bug

---

Library_Engine/Query/Match.cs

Closes #1425 
Adds partial match method for returning all library objects that contain input string.
[Test Script](https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/BHoM_Engine/Library%20Engine/Issue1425-Partial%20Match?csf=1&e=Jw5CVY)

Library_Engine: Added partial match method

---

Structure_Engine/Create/AluminiumSection.cs
Structure_Engine/Create/ConcreteSection.cs
Structure_Engine/Create/ConstantFramingProperty.cs
Structure_Engine/Create/GenericSection.cs
Structure_Engine/Create/SectionProperty.cs
Structure_Engine/Create/SteelSection.cs
Structure_Engine/Create/TimberSection.cs
Structure_Engine/Query/AnalyticalBars.cs
Structure_Engine/Query/Default.cs
Structure_Engine/Query/Description.cs
Structure_Engine/Query/Extrude.cs
Structure_Engine/Query/Geometry.cs
Structure_Engine/Query/MaterialType.cs
Structure_Engine/Structure_Engine.csproj

https://github.com/BHoM/BHoM/pull/654
Closes #1409 
https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/BHoM/Structure_oM/Issue555-AddingTimberALuminiumAbdGenericSections?csf=1&e=HMfIUS
- Add Create methods for Aluminium, Timber and Generic sections
- Update Geometry and Extrude methods to work with new `IGeometricalSection` interface
- Adding support for new section types for converting to and From `IFramingElement`
- Adding descriptions for create methods for section properties

Structure_Engine: Add support for Timber, Aluminium and Generic sections

---

Environment_Engine/Modify/SetPanelType.cs

Fixes #1422 
Fixes to internalFloors that where not at the lowest point of the space. 
Finds ceilings and internal floors between two spaces.
Test script in issue

Environment_Engine: SetRoofPanels to set ceilings and internalfloor between spaces

---

Geometry_Engine/Compute/FitPlane.cs
Geometry_Engine/Query/IsPlanar.cs
Geometry_Engine/Query/Normal.cs

Closes #1428
No test files as the methods are mere wrappers of others. One thing that came across my mind: should we implement explicit `IsPlanar` check for `PlanarSurface`, or is it OK to _assume_ that it has been constructed correctly (current approach, returning `true` without any computations)?
- `IsPlanar`, `FitPlane` and `Normal` methods have been implemented for `BH.oM.Geometry.PlanarSurface`

Geometry_Engine: Implemented Normal, IsPlanar and FitPlane for PlanarSurface

---

.ci/CloneTest.ps1

Updates the `CloneTest` file to only clone `BHoM` if it is not already cloned as a failsafe. Related to #1452

BHoM_Engine: Update CI file to check if path already exists

---

.github/CODEOWNERS
BHoM_Engine.sln
Programming_Engine/Compute/PopulateTypes.cs
Programming_Engine/Programming_Engine.csproj
Programming_Engine/Properties/AssemblyInfo.cs
Programming_Engine/Query/DataTypePerParam.cs

https://github.com/BHoM/BHoM/pull/682
Provides the Engine for the task covered by this PR: https://github.com/BHoM/Grasshopper_Toolkit/pull/447
This effectively removes the dependency of Grasshopper with the Node2Code toolkit. It is critical to do so since some of the code in GH related to Node2Code will later be migrated to BHoM_UI.
In term of review, this is mainly a question of testing that the Grasshopper PR still works the same ways now that the oM has been migrated.
This is simply a migration of the code from https://github.com/BHoM/Node2Code_Toolkit/pull/2 with no change other than the namespace

Programming_Engine: Adding Initial code

---

Diffing_Engine/Compute/DiffingHash.cs
Diffing_Engine/Compute/SHA256Hash.cs

Closes #1466 
Removes the limitations on the inputs of two methods: SHA256 and DiffHash. More consistent with the rest.
Note that the branch name is defined like that for development need (CI on Speckle_Toolkit)
No test needed.

Diffing_Engine: SHA hashing: add support for any object; DiffHash: add support for IObject

---

Versioning_Engine/Convert/ToNewVersion.cs

Engine part of https://github.com/BHoM/Versioning_Toolkit/issues/20
See https://github.com/BHoM/Versioning_Toolkit/pull/21 for more details.
Notice that the changes are on two levels:
- The `ToNewVersion` method now takes an extra parameter: the version to run the upgrade on. This way, the upgrader can now call each other. 
- Correction on the assembly version extracted for the current assembly. It was previously using the assembly version and not the assembly FILE version. This is corrected with this PR.

Versioning_Engine - Add support for versioning chains

---

Structure_Engine/Compute/Integrate.cs
Structure_Engine/Compute/IntegrateSection.cs
Structure_Engine/Create/AluminiumSection.cs
Structure_Engine/Create/ConcreteSection.cs
Structure_Engine/Create/GenericSection.cs
Structure_Engine/Create/SectionProperty.cs
Structure_Engine/Create/SteelSection.cs
Structure_Engine/Create/TimberSection.cs

Closes #1482 
Enables the functionality from #1255 in the calculation of section constants for the Structure_Engine.
Also changes the output of the method to a dictionary of doubles as there no longer are any `object` outputs

Structure_Engine: Enable the use of Green's Therom for Section Integration

---

BHoM_Engine/Modify/RemoveFragment.cs

Closes #1479
Makes the behaviour of `RemoveFragment` more as it could be expected from an User point of view.
Not needed.

BHoM_Engine: RemoveFragment returns the same BHoMObject if the given fragment is not found

---

Structure_Engine/Compute/PlasticModulus.cs

Closes #1490 
Added proper tolerance handling for `SplitAtX`, and a null check after `PointAtX`
also makes `SplitAtX(PolyLine)` call `SplitAtX(PolyCurve)` 
and fixes the edge cases by splitting up the splitting process in splitting for values on the curves and splitting for values on the endpoints
change `SplitAtX` to public for the extra bits
https://burohappold.sharepoint.com/:f:/s/BHoM/EnhPFd09iDdJuT6hVgP7iAsB76qsXiyjHSqTGNhrNQfhXQ?e=HCMaQm

Structure_Engine: Plastic modulus, SplitAtX fix

---

Structure_Engine/Query/Geometry.cs

Closes #1381 
Splits the `FEMesh.Geometry()` method into three smaller methods:
FeMeshFace => Face
IEnumerable<FeMeshFace> => IEnumerble<Face>
FeMesh => Mesh
What should the excact format for the Output parameter be? `line` `outline` or `face` @IsakNaslundBh  ?

Structure_Engine: Split FeMesh.Geometry() into three methods

---

Geometry_Engine/Compute/WetBlanketInterpretation.cs
Geometry_Engine/Geometry_Engine.csproj

Closes #1503 
As discovered through the use of PlasticModulus, `WetBlanketInterpetation` does not work for `Polylines` with segments shorter than the tolerance.
I have hence added `RemoveShortSegments` to the beginning of `WetBlanketInterpetation`
#1505 needed to see the change in the test file
see issue
Expanded my description with some Quantities which did touch the `.csproj`

Geometry_Engine: WetBlanketInterpetation edge case fix

---

Serialiser_Engine/Convert/Bson.cs
Serialiser_Engine/Objects/MemberMapConventions/BHoMObjectDiscriminatorConvention.cs
Serialiser_Engine/Serialiser_Engine.csproj

Closes #1500
Here's what was happening in term of teh code side:
- The `Dataset` class has property of type List<IBHoMObject>
- Mongo Bson automatically generate a deserialiser for `Dataset`
- When that deserialiser tries to figure out the type of the objects inside the list (yes, generics again), it fails because custom objects don't have a "_t" value provided.
- The same would have happen for a list of IObject but not for list of objects (as we already cover that last case).
So the trick here was to add a discriminator on interfaces that can cover CustomObject to make sure `CustomObject` is returned when no "_t" value is found 
https://burohappold.sharepoint.com/:u:/s/BHoM/EXSqZLG23OJOnS30i215tE8BqHhmzwfMwyL75z3NIChj_Q?e=4Chz65
I have updated the file provided in the issue so it also …

Serialiser_Engine: Fix bug for deserialisation of List<IBHoMObject> containing CustomObjects

---

Geometry_Engine/Create/ShapeProfile.cs

Closes #1502 
Allows for dumb but valid sections
i.e. an I section can now be a rectangular section and a Generalised T section can become wider by having one of the flanges occupy the whole height 
It does still not allow for the creation of zero length polylines in the centre of sections
i.e. attempts to create a rectangular profile from a box profile
https://burohappold.sharepoint.com/:f:/s/BHoM/EmcFr3JyH5FGg81281kzc9wBwUc0z-dJ4VBmljAPfECcXg?e=E927at

Geometry_Engine: Allow equal values for shape profiles

---

Versioning_Engine/Convert/ToNewVersion.cs

Closes #1548
I have added the PID of the program calling the upgrader in the pipeline name so multiple pipelines can be created for the same upgrader version.

Versioning_Engine: Functionality for multiple instances of Rhino (or any UI)

---

Library_Engine/Query/Datasets.cs
Library_Engine/Query/Libraries.cs
Library_Engine/Query/RefreshLibraries.cs

Closes #1379 
Fixing making sure library paths are only stored once for each guide path. Before identical filename and folder name could lead to the same library being picked up multiple times.
This should not have any effect at all on the dropdown component as it always works with full paths.
Extract the zip file, including folder, and place it in appdata/BHoM/Datasets
[TestSameName.zip](https://github.com/BHoM/BHoM_Engine/files/4338445/TestSameName.zip)
And run this testfile:
https://burohappold.sharepoint.com/:f:/s/BHoM/Es5sBsBXc1RHsI9x7JMI70gB-qrRj_Px_P39kf_ZYjX0ww?e=jjIs97
The dataset contains two dummy bars. Without this change the testscript returns both of them 2 times (resulting in 4 Bars) as the library is being picked up twice.

Library_Engine: Only pick up exact path for library search strings once

---

Reflection_Engine/Query/Description.cs

Closes #1584 
Adding the options of the enums, and their inner descriptions, to the description text of an enum. Enum values and text below added:

Reflection_Engine: Extract descriptions of enum options

---

.github/CODEOWNERS

Closes #1592 
Added @al-fisher, @IsakNaslundBh and @pawelbaran as co-code owners - mirroring the Spatial_Engine. As we grow further the Matter_Engine in the future and the general trans-dimensional approaches across our IElement interfaces there will be good common design patterns and approaches to share across Spatial and Matter
So hope makes sense and both happy? 😄

Matter_Engine: Update CODEOWNERS

---

Geometry_Engine/Modify/Simplify.cs

Closes #1602 
Add a control point if the curve is closed.

Geometry_Engine: Add last control point for Simplify

---

Reflection_Engine/Modify/SetPropertyValue.cs

Closes #1578 
Adeed dictionary functionality to set property so that custom data properties can be set.
[SetCustomDataProperty.zip](https://github.com/BHoM/BHoM_Engine/files/4331627/SetCustomDataProperty.zip)

Reflection_Engine: Added set property functionality for custom data

---

Serialiser_Engine/Convert/Bson.cs

Closes #1618 
Two things to test:
- Convert a string to Json and then back using `FromJson`. The result should be a string and not a custom object.
- For the dataset component, just create any data component using teh ctrl-shift-b menu. For example, search for `CHS`.
- It is important to note that, this close to the creation of the installer, I have prioritised the minimisation of risk. One could argue that the proper way to handle deserialisation of the string is to Create a string serialiser and to register it with `BsonSerializer`. But making sure there is no undesirable side-effect is way more difficult that way. 
- My key concern is the fact that the data component is not created properly through the ctrl-shit-B menu. This should be, in my opinion, the deciding factor for merging …

Serialiser_Engine: Fix deserialisation of string when top object

---

Reflection_Engine/Compute/DummyObject.cs
Reflection_Engine/Query/IsEqual.cs
Reflection_Engine/Query/TypeList.cs
Reflection_Engine/Reflection_Engine.csproj
Reflection_Engine/packages.config

Closes #1642 
See changelog
https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/BHoM_Engine/Serializer_Engine/Serialiser_Engine-Issue1642-SerialiserValidation.gh?csf=1&web=1&e=L7IzcC
This file eliminate types that might not be on your computer so you might have to tweak it to get to the same result. I'll List the things I have found already in #1620 .
- Added new method to generate a dummy object of a given type
- Added new method to test if two objects are equal (works for any type)
- Removed static classes from `BHoMTypeList`
The `DummyObject` method certainly needs some refactoring. But it does the job for now.

Serialiser_Engine: Add tools necessary to perform serialisation validation 

---

Structure_Engine/Objects/EqualityComparers/NameOrDescriptionComparer.cs
Structure_Engine/Query/Description.cs
Structure_Engine/Structure_Engine.csproj

Closes #1398 
Adding a new comparer making use of the DescriptionOrName method, that first checks for the name, and if empty, uses the autogenerated description.
To be used across most structural adapters for Property type obejcts.
Also added missing description for LinkConstraint
See test case for method here https://github.com/BHoM/Robot_Toolkit/pull/353

Structure_Engine: Add comparer for name or description for IProperty

---

Physical_Engine/Query/SolidVolume.cs

Closes #1627 
Had a home-brewed area calculation (which was wrong as I missed the physical openings).
Exchanged for calculating it with the Geometry_Engine methods, adding the locations area and removing the openings ones.
https://burohappold.sharepoint.com/:f:/s/BHoM/EuMPZj-GEMNKhjpnmGLko4UBUSEhwIdWfJzUUlfLMTf_ag?e=TypUUi

Physical_Engine: Correct area for SolidVolume

---

Geometry_Engine/Compute/CollapseToScaledPolyline.cs

Closes #1631
Not needed, and only code implementation was in structures where the tolerance value was defined, doubt it has gotten mush use elsewhere.

Geometry_Engine: Clarify input naming in CollapseToScaledPolyline.cs

---

Structure_Engine/Compute/Integrate.cs
Structure_Engine/Compute/IntegrateSection.cs

Closes #1669 
The integration returned a hard error if no curves were provided, which made creating things like Tapered Sections impossible
So does now return zero for everything for zero curves
https://burohappold.sharepoint.com/:u:/s/BHoM/ESlszk2mhYVAga4AeAk4IFQB08YBzdVounGwriiWumASkw?e=6TdCb1

Structure_Engine: Create Section from TaperedProfile fix

---

Reflection_Engine/Query/IsDeprecated.cs

https://github.com/BHoM/BHoM/pull/804
Align with separated of the `DeprecatedAttribute` into two separate attributes: replaced and deleted.

Reflection_Engine: Update IsDeprecated method

---

Reflection_Engine/Query/Description.cs

Closes #1461 
- Removes the "This is a property of...." default description
- Only add type description for IObjects

Reflection_Engine: Remove boilerplate default descriptions

---

Structure_Engine/Query/Area.cs
Structure_Engine/Query/AverageThickness.cs
Structure_Engine/Query/MaterialComposition.cs
Structure_Engine/Query/SolidVolume.cs
Structure_Engine/Structure_Engine.csproj

https://github.com/BHoM/BHoM/pull/814
Closes https://github.com/BHoM/BHoM/issues/809
Adds `SolidVolume()` and `MaterialComposition()` for `IAreaElements`
https://burohappold.sharepoint.com/:f:/s/BHoM/EihNne-QqplJjKE8p_V7pqAB0hbwPNDVLGRzbVR-Y59d8g?e=50JAKv
- Added `SolidVolume()` for `IAreaElement`
- Added `MaterialComposition()` for `IAreaElement`
- Added `AverageThickness()` for `ISurfaceProperty`
- Support for `Surface` in Structure_Engine's `Area()` method

Structure_Engine: Extension Methods for IElementM

---

Structure_Engine/Objects/EqualityComparers/Constraint4DOFComparer.cs
Structure_Engine/Objects/EqualityComparers/Constraint6DOFComparer.cs
Structure_Engine/Structure_Engine.csproj

Closes #1688
Migrating full comparers for Constraint4DOF and Constraint6DOF from Robot_Toolkit to Structure_Engine

Structure_Engine: Adding comparers for Contraints4DOF and 6DOF from Robot_Toolkit

---

Geometry_Engine/Geometry_Engine.csproj
Geometry_Engine/Modify/RoundCoordinates.cs
Geometry_Engine/Modify/RoundPoint.cs

Closes #1675 
Adds `RoundCoordinates` which rounds the coordinates of a `IGeometry`, currently supports `ICurves`
#1676 will be addressed once Spatial_Engine clears up
https://burohappold.sharepoint.com/:u:/s/BHoM/EeDbV5uQCIFEgOxEzGM3FuUBey_qVsrbuNa4JPjrtGpV0g?e=KPhnSe
- Deprecates `RoundPoint`

Geometry_Engine: Add RoundCoordinates

---

Versioning_Engine/Compute/VersionKey.cs
Versioning_Engine/Query/VersionKey.cs
Versioning_Engine/Versioning_Engine.csproj

Provide helper method/component to go along with this PR: https://github.com/BHoM/BHoM_UI/pull/247
This makes it way easier to populate the inputs of a `PreviousVersion` attribute.

Versioning_Engine: method to easily generate method keys for versioning

---

Reflection_Engine/Create/Type.cs
Serialiser_Engine/Objects/BsonSerializers/MethodBaseSerializer.cs

Closes #1695 
- Fixes issue of deserialising a method if multiple engine types with the same name and namespace is found
- Adding AllEngineTypes method in reflection engine that returns all types matching a type name
@kThorsager can you run through your testcases

Serialiser_Engine: Fix issue of failing to deserialise methods if multiple engine method matches are found

---

Library_Engine/Query/Datasets.cs

Closes #1715
On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?viewid=a5a93cba%2Dfcca%2D46cc%2Da31a%2D80b8d5cbfd7b&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FBHoM%5FEngine%2FLibrary%20Engine%2FLibrary%5FEngine%231715%2DMissingNotFoundWarning).

Library_Engine: Warning added when the library under given name is not found in the folder 

---

Analytical_Engine/Analytical_Engine.csproj
Graphics_Engine/Graphics_Engine.csproj

BHoM_Engine: Fix Analytical_Engine and Graphics_Engine CSProj

---

Reflection_Engine/Reflection_Engine.csproj
Serialiser_Engine/Convert/Bson.cs
Serialiser_Engine/Objects/BsonSerializers/BitmapSerializer.cs
Serialiser_Engine/Objects/BsonSerializers/IntPtrSerializer.cs
Serialiser_Engine/Serialiser_Engine.csproj

Closes #1736
This is a very minor thing as IntPtr and Bitmap will generally not be something you would want to serialise but good for completion sake. 
It is worth noting that there are three issues with Bitmap:
- Generating a Dummy Bitmap leads to a failing `ToJson`  So you have to break in the code where you have access to a `SearchItem` so you can test (de)serialisation: 
- while Bitmap goes through a serialisation cycle properly now, it fails the `IsEqual` Test. This is because of the `Flags` property in `Palette`. This thing can not be overwritten and is even changing live while I was debugging in VS. This is another reason why I didn't keep my version of the code. Since I couldn't fix the flag issue, I would rather rely on the official version to save/load a bitmap since there is …

Serialiser_Engine: Adding serialiser for IntPtr and Bitmap

---

Diffing_Engine/Create/StreamPointer.cs
Serialiser_Engine/Compute/RegisterClassMap.cs
Serialiser_Engine/Convert/Bson.cs
Serialiser_Engine/Objects/BsonSerializers/BitmapSerializer.cs
Serialiser_Engine/Objects/BsonSerializers/ObjectSerializer.cs
Serialiser_Engine/Objects/BsonSerializers/RegexSerializer.cs
Serialiser_Engine/Serialiser_Engine.csproj
Versioning_Engine/Convert/ToNewVersion.cs

https://github.com/BHoM/BHoM/pull/857
https://github.com/BHoM/Test_Toolkit/pull/247
Closes #1620 
Closes #1755 
Closes #1737
Yatta !! Finally got all types working (at least those on my computer).
This fixes the serialiser itself but will be accompanied by a few corrections on the non-compliant types themselves to get it all working (see PRs in the `depends on` section)
https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/BHoM_Engine/Serializer_Engine/serialisationTest.gh?csf=1&web=1&e=1okDsJ
If you have types failing on your machine, please make sure they compliant first. A common issue for example is an incorrect constructor for `IImmutable` classes.
- Move RegisterClassMap and add serialiser for regex
- Take care of the case where a bitmap is null …

Serialiser_Engine:  Fix remaining problems with serialisation

---

Reflection_Engine/Compute/MakeGenericFromInputs.cs
Reflection_Engine/Create/MethodBase.cs
Reflection_Engine/Create/Type.cs

Closes #1768
here's a few things that are now possible: 
- Create types that only exist in the BHoM as a generic definition (i.e still with `<T>`) 
- Create method that only exist in the BHoM as a generic definition
- Deserialise specific instances of generic types and methods definition
Here's a few examples:
The resolution of this was inspired by a problem @kThorsager faced here: https://github.com/BHoM/BHoM_Engine/pull/1740#issuecomment-625330047
While there is a PR that fixes that specific problem, I realised it was impossible to create instances of generic type and method definitions.

Reflection_Engine: Enable creation of Generic methods and types from string

---

Geometry_Engine/Create/PlanarSurface.cs
Geometry_Engine/Query/IsInPlane.cs

https://github.com/BHoM/BHoM/pull/861
Closes #1446 
Updates the Create method to use the new constructor and adds extra checks to ensure the validity of the `PlanarSurface`
See oM PR for more info
https://burohappold.sharepoint.com/:u:/s/BHoM/Ed2ni1X7x2lOhSlTrobaIZ8BIa56APsehBDEObFLFDHkPA?e=un8SPP

Geometry_Engine: Implement necessary methods for immutable PlanarSurface

---

Reflection_Engine/Create/Type.cs
Serialiser_Engine/Objects/BsonSerializers/MethodBaseSerializer.cs
Serialiser_Engine/Objects/BsonSerializers/ObjectSerializer.cs
Serialiser_Engine/Objects/BsonSerializers/TypeSerializer.cs

Closes #1738
Closes #1766 
Methods and types are now upgraded directly during deserialisation, not need to call ToNewVersion separately.
Here's what I have tested on. But I recommend to use the usual serialisation test files on SharePoint:
- Serialisation from #1756 is still giving me a 100% success as before
- I have tested various levels of inclusion of a type that needs upgrading and all seems fine.
Here's the json used in there (in order of complexity, raw type, Custom object containing the type as property, List of that type to cover generic types, method that needs that type to be updated for it to work ):
```
{ "_t" : "System.Type", "Name" : "BH.oM.Geometry.IElement2D" }
```
```
{"Type": { "_t" : "System.Type", "Name" : "BH.oM.Geometry.IElement2D" }, "A": 1}
```
```
{ "_t" : …
```

Serialiser_Engine: Auto-versioning of methods and types during serialisation

---

Structure_Engine/Objects/EqualityComparers/CaseNumberComaprer.cs
Structure_Engine/Structure_Engine.csproj

Closes #1763
Adding comparer checking numbers for ICase objects
Will link to test file making use of the comparer in Robot, as soon as Robot is free to push code to.

Structure_Engine: Adding comparer checking numbers for ICase objects

---

Structure_Engine/Compute/PlasticModulus.cs

Closes #1795 
While the solution seems simplistic, it does work as the only problem was that the foreach loop assumed `PolyCurve` without reason. But SubParts works for `ICurve`. Think is was left over from when it worked differently, but aw well.
Works now.
see issue #1795

Structure_Engine: Plastic modulus, SplitCurve removal of unneeded curve cast

---

Architecture_Engine/Query/NewElement1D.cs
Environment_Engine/Query/NewElement1D.cs
Physical_Engine/Create/IElement/IElement1D/NewElement1D.cs
Spatial_Engine/Create/NewElement0D.cs
Spatial_Engine/Create/NewElement1D.cs
Spatial_Engine/Modify/SetElements0D.cs
Spatial_Engine/Modify/SetOutlineElements1D.cs
Structure_Engine/Create/Elements/IElement0D/NewElement0D.cs
Structure_Engine/Create/Elements/IElement1D/NewElement1D.cs
Structure_Engine/Modify/SetElements0D.cs
Structure_Engine/Modify/SetOutlineElements1D.cs

Closes #1785
As specified in change-log
Tests that the defaulting for the only element (`Bar`) which needs it is working.
https://burohappold.sharepoint.com/:u:/s/BHoM/EXdhou5wJ9xFmUZReD9Inx0B8LoeNgGw6H28RWnIghZkrg?e=yJAyoE
- `ISetElement` `0D` & `1D` methods now defaults if provided a `IGeometry`
- `INewElement` `0D` & `1D` methods are no longer needed and now return the inputted point/curve awaiting removal
No urgent reason to delete the new methods in each project, but will tag them as `ToBeRemoved and raise separate issues to be resolved at toolkit(project?) leads discretion.
raised in #1788 
Not versioning since it not really anything to version to (maybe the components second input to a `IGeometry` holder component? (don't think that's possible))

Spatial_Engine: Restructure ISetElement and INewElement

---

Geometry_Engine/Create/TransformMatrix.cs
Geometry_Engine/Modify/Mirror.cs
Geometry_Engine/Modify/Project.cs
Geometry_Engine/Modify/ProjectAlong.cs
Geometry_Engine/Modify/Rotate.cs
Geometry_Engine/Modify/Scale.cs
Geometry_Engine/Modify/Transform.cs
Geometry_Engine/Modify/Translate.cs

Closes #1818 
Adding the functionality for the Transform methods for most `IGeometry` objects
The main offenders are `NurbsCurve`, `NurbsSurface` & `PlanarSurface`
The Transform methods are:
- `Transform`
- `Translate`
- `Scale`
- `Rotate`
- `ProjectAlong`
- `Project`
- `Mirror`
https://burohappold.sharepoint.com/:u:/s/BHoM/EZr4zXI_K0ZFk2nsaKQjiqIBBHS9g11IXVV77-w3uAsptQ?e=TPJDWB
- Also added a Create.ProjectionMatrix
Think the only controversial part is making the IRotate(IGeometry) work for anything else than vectors and adding private fall backs for the methods.
So more things were annoying, testing revealed that ProjectAlong for Circles did not work, which is what I based the Ellipse method on. So i threw in a ProjectionMatrix as ellipses can turn into not ellipses and circles were …

Geometry_Engine: Transform and Subsequent methods for IGeometry objects

---

Geometry_Engine/Create/PlanarSurface.cs

Closes #1841 
The checks for creating a planarSurface don't work for PolyCurves based on Nurbs or Ellipses either.
This makes sure that they are ignored like the Nurbs and Ellipses, which means that they can be created.
see issue

Geometry_Engine: Fix edgecase for Create PlanarSurface

---

Serialiser_Engine/Compute/RegisterClassMap.cs
Serialiser_Engine/Objects/MemberMapConventions/ImmutableBHoMClassMapConvention.cs

Closes #1851
See issue for more details.
This fixes a bug introduced in https://github.com/BHoM/BHoM_Engine/commit/db0c1bdc1c192ddc46c3fed4e00d98514034f0df
You can also make sure that this change doesn't brake any other serialisation by using https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/BHoM_Engine/Serializer_Engine/serialisationTest.gh?csf=1&web=1&e=d4cOIv
This is a very specific change that cannot break anything else so I am happy to merge it this week. Let me know if you disagree.

Serialiser_Engine: Fixing member mapping for Immutable inheriting from non-abstract class

---

Structure_Engine/Query/Geometry.cs

Closes #1853 
The above is a resolution of current bug to return to similar behaviour before implementation of immutable PlanarSurfaces.
Should resolve original issue here:
https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FModelLaundry%5FToolkit%2FModelLaundry%2DIssue253%5FInvalidPerimeterSnapToGrids&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4
And should now give warnings instead of errors here:
https://burohappold.sharepoint.com/:u:/r/sites/BHoM/Installers/Scripts/BuroHappold_BHoM_v3.2/0010_Model%20Laundry/Structures_ClassicPanelML.gh?csf=1&web=1&e=OIBDJ6

Structure_Engine: Allow Query.Geometry to return invalid PlanarSurfaces for the case of invalid Structure.Panels

---

Geometry_Engine/Query/IsContaining.cs

Closes #1214 
`IsContaining`s algorithm assumed that if a line, with end at point A,'s intersection point with an line L was within the distance tolerance, then any line which endpoint is at the point A will intersect the line L.
unfortunately not true,
This PR adds a relative factor based on their angles to query if the other intersection will happen.
This approach only works for linear cases, so added a sanity check for the `PolyCurve` case to avoid the most horrendous errors
Generic test:
https://burohappold.sharepoint.com/:u:/s/BHoM/EeLGxufNopJMnOX4g1fMMdoBt8NybP-hh7ytJFvGGoWFRw?e=hfBWhG
Specific test:
See issue

Geometry_Engine: Better handling of corner cases in IsContaining

---

Reflection_Engine/Compute/RunExtensionMethod.cs

Closes #1856 
Fixes an issue with thread safety of the RunExtensionMethod.
When a multi-threaded part elsewhere calls methods that depend on RUnExtensionMethod, for the first run, you can end up in strange race conditions, where the dictionary can crash out with a null reference exception, when trying to add a method to it, even though neither the dictionary itself, the key or the value being null.
https://github.com/BHoM/BHoM_Engine/blob/1f3b86537c17c468aae717c28119a626dc45fa05/Reflection_Engine/Compute/RunExtensionMethod.cs#L89
This seem to have to do with the fact that dictionaries are not thread safe for writing, only for reading.
Switching to a `ConcurrentDictionary` seem to have solved the issue on my end. A minor slowdown for the test case could be seen, but still running close to …

Store previously run extension methods in a thread safe dictionary

---

Reflection_Engine/Query/PropertyObjects.cs

The `PropertyObjects` method with `goDeep` set to true was not collecting the objects inside the list properties. This PR fixes that.
This is needed to [this PR in the DataViz toolkit](https://github.com/BuroHappoldEngineering/DataViz_Toolkit/pull/75)
Use `PropertyObjects` component on any object that has a list property.

Reflection_Engine: Making sure PropertyObjects also collects objets in list properties

---

Data_Engine/Create/DomainTreeLeaf.cs
Data_Engine/Data_Engine.csproj
Data_Engine/Query/ItemsInRange.cs
Spatial_Engine/Create/DomainTree.cs
Spatial_Engine/Spatial_Engine.csproj

Closes #
some support methods for DomainTree to alleviate working with it
Not needed
- added tolerance to ItemsInRange as well

Data_Engine: Quality of life for DomainTree

---

Environment_Engine/Environment_Engine.csproj
Environment_Engine/Query/FilterByAdjacencies.cs

Closes #1850  
A new query method that filter panels based on the number of adjacencies they have.

Environment_Engine: Filter by adjacencies query method

---

Structure_Engine/Query/ReinforcementLayout.cs

Closes #1893 
Make sure that minimum cover is used as default parameter for cover for setting reinforcement layouts
https://burohappold.sharepoint.com/:f:/s/BHoM/EpXy3FR30txGs3Q3jTlTwOoBv9zjDu3k-0Z34O9CfSBIBQ?e=ASSrZ2

Structure_Engine: Fix bug for default values for minimum cover for reinforcement layout

---

Diffing_Engine/Convert/ToDiffingByteArray.cs
Diffing_Engine/Convert/TryParseObjectToGuid.cs
Diffing_Engine/Diffing_Engine.csproj
Diffing_Engine/packages.config
Environment_Engine/Environment_Engine.csproj
Environment_Engine/packages.config
Serialiser_Engine/Compute/ReadFromStream.cs
Serialiser_Engine/Compute/WriteToStream.cs
Serialiser_Engine/Convert/Bytes.cs
Serialiser_Engine/Serialiser_Engine.csproj
Serialiser_Engine/packages.config
Versioning_Engine/Compute/VersionKey.cs
Versioning_Engine/Query/VersionKey.cs
Versioning_Engine/Versioning_Engine.csproj
Versioning_Engine/packages.config

Closes #1875 
As mentioned in the issue this upgrades the Bson package to fix the remaining issue we had with serialisation. 
This also centralise better the functionality related to conversions to and from Bson for consistency of behaviour and for simplicity purposes.
There's a few things you can do to test this PR:
- Make sure everything still compile
- Test that the diffing engine is still working fine (@alelom)
- Serialise a few objects by using ToBytes-> FromBytes and makes sure they are still teh same. Personally, I have used the [serialisation test file](https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/BHoM_Engine/Serializer_Engine/serialisationTest.gh?csf=1&web=1&e=nyVLwI) that check that all files serialise properly
- Removing reference …

BHoM_Engine: Upgrade Mongo Bson package and centralise dependencies

---

Geometry_Engine/Query/Centroid.cs
Geometry_Engine/Query/Normal.cs

Closes #1896 
Fixes the Normal method, using average of points instead of just looking at the first. As IsClockwise is being called, the direction of the normal will be fixed there.
Simplifying the Centroid methods for Polyline and PolyCurve. Given that the normal is now checked, and ensured to be in the right direction, should be able to rely on that, and not have to preform the "first normal" checks and direction checks, which was the cause of the problem in the issue.
As this is changing some quite core methods, would like to see quite rigorous testing on methods making use of this. I have tried testing through multiple generic cases, and have so far not had any issues, but would be thankful if more edgecases could be thought of that could have the potential to go wrong.
Issue test: …

Geometry_Engine: Fix for centroid and normal

---

Data_Engine/Compute/DomainTreeClusters.cs
Data_Engine/Create/DomainTree.cs
Data_Engine/Create/Node.cs
Data_Engine/Data_Engine.csproj
Data_Engine/Query/Children.cs
Data_Engine/Query/ClosestData.cs
Data_Engine/Query/ItemsInRange.cs
Data_Engine/Query/Values.cs
Geometry_Engine/Compute/PointClustersDBSCAN.cs

Closes #1881 
Had some hopes about making this general for DBSCAN and making them use `INode`, but there were annoyances as it i not a `IEnumerable`, there are difficulties in changing the objects in the tree without messing with the data and the DBSCAN method would need to be refactored to look at things per Collection rather than per Item.
And just adding clusters for IGeometries or ICurves was also annoying since no general distance method existed and would add a extra layer to this method. And there doesn't seem to be any huge need either so.
But the speed up is considerable, especially for large sets of points. 😁
(40000 points, 1.3m to 3.4s in the test file)
https://burohappold.sharepoint.com/:u:/s/BHoM/Ec8Vk7lcL1dCgXq-QdewJokBfJ4s8jwT5hIATIwiA-3WWg?e=RqtVBu

Geometry_Engine: Update PointClustersDBSCAN to use DomainTree

---

Spatial_Engine/Query/ElementVertices.cs

Closes #1902 
Adds a ElementVerticies method for IElement0D to accomodate the interface method

Spatial_Engine: ElementVerticies for IElement0D

---

Reflection_Engine/Modify/SetPropertyValue.cs
Reflection_Engine/Query/PropertyValue.cs

Closes #1905
I found out that there are a couple of annoying things happening when dealing with CustomObject exclusively:
- The output of GetProperty if the property is a `List<List<T>>` will not return a tree but a list of `List<T>` objects. 
- It is not possible to Set a list as property of a custom object. 
Those two are a UI issue: the UI considers that the property of a custom object is always an object (CustomData is after all a `Dictionary<string, object>`) so will return a list as a single object and will always expect a single object as input. 
I am currently refactoring completely the UI and the problem will be solved there. In the meantime, I have raised an issue here: https://github.com/BHoM/BHoM_UI/issues/296

Reflection_Engine: List support for get set property

---

Structure_Engine/Query/TorsionalConstant.cs

Closes #1925 
Updating formulae for torsional constant calculations to slightly more precise ones from orange book:
https://orangebook.arcelormittal.com/explanatory-notes/long-products/section-properties/
and 'P385 Design of steel beams in torsion'
Testing through all UK sections:
https://burohappold.sharepoint.com/:f:/s/BHoM/Ero08H60-KRLu8jNgEh14PwB853HActz0oTnxSevlKtxtw?e=WCOgGa
FYI @JosefTaylor @peterjamesnugent @rwemay

Structure_Engine: Small improvements to torsion constant calculations

---

Reflection_Engine/Compute/MakeGenericFromInputs.cs
Reflection_Engine/Compute/RunExtensionMethod.cs
Reflection_Engine/Query/IsAssignableFromIncludeGenerics.cs
Reflection_Engine/Query/IsAssignableToGenericType.cs
Reflection_Engine/Reflection_Engine.csproj

Closes #1865 
Multiple fixes and improvements to the Run extension method. See changelog
Testing scripts calling methods making use of RunExtensionMethod still work:
https://burohappold.sharepoint.com/:f:/s/BHoM/EvPhiod3VEVOluLAwReZmD4BPVEzu1U-DibAAAg10tBOjQ?e=mi8zDD
I have added a few test methods locally and tested that they do work appropriately, but do not want to push them to this PR. Example method in Analytical_Engine should make the BEnv panels visable (or any IPanel for that matter):
```
namespace BH.Engine.Analytical
{
public static partial class Query
{
/***************************************************/
/**** Public Methods                            ****/
/***************************************************/
[Description("")]
[Input("", "")]
[Output("", "")]
public static …
```

Reflection_Engine: Consolidate run extension method

---

Data_Engine/Query/Values.cs

Closes #1920
Uncommenting out the code for getting out all values from a table.
This was commented out in https://github.com/BHoM/BHoM_Engine/pull/1833 which did not have anything to do with the tables.
@rolyhudson would you mind testing that the spatial trees are unaffected by this?
Testfiles from PR where this was commented out:
https://burohappold.sharepoint.com/:u:/s/BHoM/EaZM91qyXmVAo4ddZrneV6wB_1m8DlJ-Eq_PbDIsAlHoSQ?e=hxg7KS
And a more lightweight version:
https://burohappold.sharepoint.com/:u:/s/BHoM/Ec3OChqs5IpAvnWqCFjkTm4BJP_IaX6Z52Fg7R4BTgzHXw?e=yaG3zj

Data_Engine: Uncommenting code for getting all values from a Table

---

Structure_Engine/Create/Constraints/LinkConstraint.cs
Structure_Engine/Create/Elements/RigidLink.cs
Structure_Engine/Query/Geometry.cs

/BHoM/BHoM/pull/961
Closes #
https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/BHoM/Structure_oM/Issue921-RigidLink%20property%20rename/Test%20Rigid%20Links%20-%20multi%20adapter.gh?csf=1&web=1&e=iDXtGs

Structure_Engine: Renamed master/slave to primary/secondary

---

Geometry_Engine/Compute/MarchingCubes.cs
Geometry_Engine/Compute/MarchingSquares.cs
Geometry_Engine/Compute/SubMesh.cs
Geometry_Engine/Geometry_Engine.csproj
Geometry_Engine/Query/Vertices.cs

Closes #
Implements the MarchingSquares and MarchingCubes for meshes and mesh3d's respectively.
In essence it allows one to extract a constant value range from a linearly approximated scalar field.
This implementation is general in the sense that it does not require neither squares nor cubes but is general to the degree that the BHoM mesh allows. (only 3 to 4 vertices per face)
And it is also not bound to the world axis but placed in the local space provided by the meshes.
Example: the scalar field = distance from a point.
Anyway could probably also be useful for result display.
[MarchingSquares.zip](https://github.com/BHoM/BHoM_Engine/files/5091004/MarchingSquares.zip)
[MarchingCubes.zip](https://github.com/BHoM/BHoM_Engine/files/5091000/MarchingCubes.zip)

Geometry_Engine: Add MarchingSquares & MarchingCubes

---

Geometry_Engine/Query/DiscontinuityPoints.cs

Closes #1954 
[SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?viewid=a5a93cba%2Dfcca%2D46cc%2Da31a%2D80b8d5cbfd7b&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FBHoM%5FEngine%2FGeometry%5FEngine%2FGeometry%5FEngine%2D%231954%2DimplementDiscontinuityPoints%28PolyCurve%29) - there are two "failing" cases in the test file. They are caused by errors from a grasshopper method. It is pointed in the file. **EDIT: Added another test file to prove versioning works fine.**
- updated `DiscontinuityPoints()` method for the `PolyCurve` class to return real discontinuity points.
- added tolerances to the inputs of every `DiscontinuityPoints()` method.
`[PreviousVersion]` attribute has been used to update methods' inputs so rebuilding …

Geometry_Engine: implementing DiscontinuityPoints(PolyCurve) and adding tolerances to inputs

---

Structure_Engine/Query/PointGrid.cs
Structure_Engine/Query/Visualize.cs

Closes #1965 
https://burohappold.sharepoint.com/:f:/s/BHoM/Em_LdUZqgX1KuIVqdNMiGJcBlPpuLhdHOREUu3lv_eSfTQ?e=ARRPJB
Test files with updated visualisations:
https://burohappold.sharepoint.com/:f:/s/BHoM/EhgghoopPXpHispXwTlB240BQpShlJn1oWapcJUVkzDSUA?e=uSOKbG
- Area load visualisation to make use of LocalOrientation for displaying local loads
- Add support for displaying Arealoads on FEMeshes
- Add support for visualisation of ContourLoad and GeometricLineLoad

Structure_Engine: Update to area loads visualisation

---

Geometry_Engine/Create/NurbsCurve.cs
Geometry_Engine/Create/NurbsSurface.cs

Closes #1955 
Removing all non-referenced create methods with `[NotImplemented]` attribute. `Random` methods are being left over to be implemented later (see #1968).
Not needed.
- Removing not implemented `Create.NurbsCurve` and `Create.NurbsSurface` methods from `Geometry_Engine`.

Geometry_Engine: Clear not implemented create methods for NurbsCurve and NurbsSurface

---

Geometry_Engine/Query/IsEqual.cs

Closes #1958 
Adding a method to compare NurbsCurves. Comparison is comparing the objects properties not the curves geometry. Two geometrically identical curves but of different degrees will be marked as not equal.
[SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?viewid=a5a93cba%2Dfcca%2D46cc%2Da31a%2D80b8d5cbfd7b&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FBHoM%5FEngine%2FGeometry%5FEngine%2FGeometry%5FEngine%2D%231958%2DAddIsEqual%28NurbsCurve%29)
- Add `IsEqual` method in `Geometry_Engine` for `NurbsCurve` class.
- We don't have a specified numerical tolerance for values like control point's weight or knot. Used distance tolerance instead as a temporary solution.
- Didn't manage to create two geometrically identical …

Geometry_Engine: Add IsEqual(NurbsCurve)

---

Geometry_Engine/Query/IsClockwise.cs

Closes #1983 
Adding mroe sample points for checking IsClockwise for arcs. Only taking start-middle-end caused issues for polycurves with large arcs with large both radius and angle span.
Tested third points as well, but was not enough.
Also changed the circle to stay consistent.
https://burohappold.sharepoint.com/:f:/s/BHoM/EhRMIIZQ0aZOgdHKcvcNDeQBDD-uYuRIcmV246ShArWHHw?e=pqYIEg

Geometry_Engine: Adding more sample points to IsClockwise

---

Analytical_Engine/Modify/SetOutlineElements1D.cs
Analytical_Engine/Query/Geometry.cs
Analytical_Engine/Query/OutlineElements1D.cs

https://github.com/BHoM/BHoM/pull/985
https://github.com/BHoM/BHoM/issues/970
Adding IElement2D methods required for IRegion.
https://github.com/BHoM/documentation/wiki/IElement-required-extension-methods
https://burohappold.sharepoint.com/:f:/s/BHoM/ElcGHiplcxxJuRsZYz9ewx8BkczFetyKcjcxAhclljhVSw?e=Pdksu3

Analytical_Engine: Adding support for IRegion

---

Geometry_Engine/Query/Centroid.cs
Spatial_Engine/Query/Centroid.cs

Closes #1705 
<s>Work in progress. Draft version of dealing with redundant code while querying centroids of planar shapes with openings.
Details in the parent issue.</s>
Adding a `Geometry_Engine` method querying a combine centroid of any set of planar, coplanar, non-self-intersecting and closed curves with optional openings. Method itself is rather not meant to be widely used due to lack of checks. Needed to be public for being used in other methods for objects like `IElement2D` or `IProfile`
[Old test file](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?viewid=a5a93cba%2Dfcca%2D46cc%2Da31a%2D80b8d5cbfd7b&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FBHoM%5FEngine%2FGeometry%5FEngine%2FGeometry%5FEngine%2DIssue%231705%20Centroid%20f …

Geometry_Engine: Add Centroid method for outline curves(s) with opening curve(s) in it.

---

MEP_Engine/Create/Elements/DuctSectionProperty.cs
MEP_Engine/Create/Elements/PipeSectionProperty.cs
MEP_Engine/Create/Elements/SectionProfile.cs
MEP_Engine/Create/Elements/WireSectionProperty.cs
MEP_Engine/Query/CircularEquivalentDiameter.cs

Closes #1989 
Closes #1953 
In our workshop on 200911 we applied a fix to allow for better handling of zero thickness elements found within composite section representations. The SectionProfile() will assume 0 thickness unless otherwise provided and provide a null where needed. 
https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/BHoM_Engine/MEP_Engine/200911_MEPoMTest.gh?csf=1&web=1&e=fUfGAB

MEP_Engine: Allow for zero thickness lining and insulation in MEP element section profiles

---

Physical_Engine/Physical_Engine.csproj

Closes #1995 
Common_oM does no longer exist and should not be referenced.
Not sure how this snuck by the major purge of Common_oM/Engine, but better late than never.
No needed. Only removing reference to a dll no longer used/existing.

Physical_Engine: Removing reference to Common_oM

---

MEP_Engine/MEP_Engine.csproj
MEP_Engine/Query/CompositeSolidVolumes.cs
MEP_Engine/Query/SolidVolume.cs

Closes #1997 
```SolidVolume()``` now outputs a single double for combined section profile values. 
```CompositeSolidVolumes()``` created to provide a profile-specific breakdown of solid volume values.
https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/BHoM_Engine/MEP_Engine/Issue%20%231997-SolidVolume/200917_MEPEngine_SolidVolume.gh?csf=1&web=1&e=6ubHh2

MEP_Engine: Single value for SolidVolume 

---

Reflection_Engine/Compute/LoadAllAssemblies.cs
Reflection_Engine/Query/AssemblyList.cs
Reflection_Engine/Query/MethodList.cs
Reflection_Engine/Query/TypeDictionary.cs
Reflection_Engine/Query/TypeList.cs
Reflection_Engine/Query/UsedAssemblies.cs
Serialiser_Engine/Convert/Bson.cs

Closes #2003
Adding padlocks around methods calling ExtractAllMethods and ExtractAllTypes to make methods threadsafe.
This is an attempt of solving the https://github.com/BHoM/BHoM_UI/issues/305 issue.
Note that the `m_GetMethodsLock` in the Engine types is intentional, as engine types currently is extracted when extracting methods. Something we might want to change in the future, but outside the scope of this PR.
**EDIT:** Had a look through and added locks to other potentially unsafe places for the BHoMAnalytics as well as making sure the whole Reflection_Engine got covered. This includes LoadAllAssemblies, AssemblyList and RegisterTypes in BSON converts. Not sure if the one is BSON is needed, as Mongo might be threadsafe and able to cope with it, but rather safe than sorry.
No real …

Reflection_Engine: Adding in pad locks for method and type extraction

---

Spatial_Engine/Query/ElementVertices.cs

Closes #2017
On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FBHoM%5FEngine%2FSpatial%5FEngine%2FIssues%2FSpatial%5FEngine%5F%232017%5FElementVerticesBug&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4) - both issue specific test as well as updated general test
Following #2017, my understanding of different types of points in relationship to their parent curve:
> * control points - control points of a curve in its nurbs form (currently simplified for `Arc` and `Circle` in the BHoM)
> * discontinuity points - points at geometrical discontinuities of a curve (discrete change in the tangent)
> * vertices - control points in case of a `Polyline` (see the example …

Spatial_Engine: ElementVertices fixed to return actual vertices

---

Geometry_Engine/Modify/Offset.cs

Closes #2021 
Replaced former solution with explicit casting to avoid missing control points (especially for closed curves).
[Issue specific](https://burohappold.sharepoint.com/:f:/s/BHoM/EoUweCi8HYVBsS42hfgiDq4BwcSR1vzY7mbYByRTZM7mkA?e=MhFHHx)
[General offset test](https://burohappold.sharepoint.com/:f:/s/BHoM/EtBlmGmRgQNFrZn2dLnm0EUBD5LFSAt13Lz7uL01kJxpFg?e=du27WM)
- Modified `Offset(Polyline)` method in the `Geometry_Engine`

Geometry_Engine: Using explicit casting in Offset to avoid losing cPts while passing arguments to Polyline method

---

Spatial_Engine/Query/Area.cs
Spatial_Engine/Query/Centroid.cs
Spatial_Engine/Query/ControlPoints.cs
Spatial_Engine/Query/ElementCurves.cs
Spatial_Engine/Query/IsSelfIntersecting.cs

Closes #2019
Not needed - obvious cases added. But I encourage to read the code carefully and randomly test the changes!
Missing Spatial_Engine methods added:
- IsSelfIntersecting (`IElement0D`, interface)
- ElementCurves(`IElement0D`)
- ControlPoints(`IElement0D`, interface)
- Centroid(`IElement0D`, interface)
- Area(`IElement0D`, `IElement1D`, interface)

Spatial_Engine: Missing methods added

---

Environment_Engine/Environment_Engine.csproj
Environment_Engine/Modify/SetPanelConstructionByType.cs

#1975 Environment_Engine: Method for assigning Construction by Panel/Opening.Type
Closes #1975
Panels can now be assigned to newContruction by ConstructionType

Environment_Engine: assign construction by type

---

Reflection_Engine/Modify/SetPropertyValue.cs

One PR on the BHoM_UI depends on this: https://github.com/BHoM/BHoM_UI/pull/326
Closes #2065 
As discussed in https://github.com/BHoM/admin/issues/9, I have removed the cloning inside the only reflection method that was doing it.
Note that the BHoM_UI is already doing the cloning for the `Modify` and `SetProperty`. 
I have also cleaned the methods here because a lot of it was outdated legacy code:
- I have removed the `Modify.PropertyValue` because it was 
- non-compliant in term of name
- only working on BHoM object (for no reason since it was calling `SetProperty(this object,...)` anyways
- was redundant with `SetProperty` method
- I have changed the output of `SetProperty` method to be compliant with the current state of the code. Note that that methods was not used anywhere in any …

Reflection_Engine: Remove calls to Clone methods and Clean SetProperty methods

---

Spatial_Engine/Compute/DistributeOutlines.cs
Spatial_Engine/Create/ShapeProfiles/FreeFormProfile.cs
Spatial_Engine/Query/PointLayout.cs

Closes #2085 
Fixing wrong area methods being called in Spatial_Engine. Putting as critical as this is currently stopping some quite key methods from at all working, so would be good to get this merged ASAP.
Even more incentive to get rid of the Area method for `IElement1D` as I am sure we will stumble upon this again in the future. Issue for it raised here:
https://github.com/BHoM/BHoM_Engine/issues/2086
before the above is resolved, resorting to explicit calls to the geometry engine.

Spatial_Engine: Updating Area calls to Geometry_Engine instead of Spatial_Engine

---

Reflection_Engine/Query/DistinctProperties.cs

Closes #2088 
Adding null checks for extraction of list and group properties.
Without the checks this could cause some really bad memory exceptions, causing Rhino to crash for cases where null lists where put on an object.
https://burohappold.sharepoint.com/:f:/s/BHoM/EsrZ8NzoZutMvj0WdoqWyQwBiorw88q9EBneNlaBCTTIeA?e=aKnruv

Reflection_Engine: Adding nullchecks for lists in DistinctProperties

---

BHoM_Engine/Objects/EqualityComparers/BHoMObjectNameComparer.cs
BHoM_Engine/Objects/EqualityComparers/BHoMObjectNameOrToStringComparer.cs
Structure_Engine/Objects/EqualityComparers/BarEndNodesDistanceComparer.cs
Structure_Engine/Objects/EqualityComparers/Constraint4DOFComparer.cs
Structure_Engine/Objects/EqualityComparers/Constraint6DOFComparer.cs
Structure_Engine/Objects/EqualityComparers/NameOrDescriptionComparer.cs
Structure_Engine/Objects/EqualityComparers/NodeDistanceComparer.cs

Closes #2029 
- Removes references to BHoM_Guids from comparers
- Additional null checks added
- Fixes wrong GetHashCode method used for the BarEndNodeDistanceComparer

Structure_Engine: Remove guid from comparers

---

Reflection_Engine/Query/Description.cs

Closes #2097
Not needed I think. Rather a simple change, seems not to break things in GH (one simply needs to remember about rebuilding BHoM_UI and Grasshopper_Toolkit @IsakNaslundBh 😆), but would be good to double check by more educated ones.
This PR should not conflict neither with #1805 nor with #2062.
I would like to get the approval of @adecler before this gets merged - just to make sure we do not blow up the UI 😉

Reflection_Engine: Extraction of MemberInfo/ParameterInfo description without type description enabled

---

BHoM_Engine/BHoM_Engine.csproj
BHoM_Engine/Query/Hash.cs

Closes #2103 
Closes #2104
https://burohappold.sharepoint.com/:f:/s/BHoM/EqKWsGEj8cNCuWm1KsWSMSIBiRBvjfLusj572G0zq62exA?e=9AdD5w

BHoM_Engine: Added global & property-specific fractional precision in `Query.Hash()`

---

Geometry_Engine/Geometry_Engine.csproj
Geometry_Engine/Query/Volume.cs

Closes #2046 
See test file here:
https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FBHoM%5FEngine%2FGeometry%5FEngine%2FGeometryEngine%2D%232046%2DVolumeQueryForISolids&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4
- Volume for BoundaryRepresentation is a straight exposure of the Get only Volume Property stored on the object and set at conversion
- All other ISolid volumes are derived from the analytical formulae comprised from defining properties.

Geometry_Engine: Addition of Query.Volume methods for ISolids

---

BHoM_Engine/Create/CustomObject.cs

Closes #1981
Assigning properties like `Name`, `BHoM_Guid`, `Tags`, and `Fragments` now tries to assign it to the corresponding property (if type is valid) instead of directly into the `CustomData` dictionary.

BHoM_Engine: Correctly assign CustomObject properties like Name and Tags

---

Physical_Engine/Physical_Engine.csproj
Physical_Engine/Query/BottomCentreline.cs
Physical_Engine/Query/TopCentreline.cs

Closes #2079 
[https://github.com/BHoM/BHoM_Engine/pull/2115](url)
[Spatial_Engin#2115_Test File.zip](https://github.com/BHoM/BHoM_Engine/files/5475190/Spatial_Engin.2115_Test.File.zip)
Creating two query methods returning the top/ bottom centreline of an IFramingElement.

Physical_Engine: Query the top/bottom centreline of an IFramingElement

---

Spatial_Engine/Query/IsNearLevel.cs
Spatial_Engine/Spatial_Engine.csproj

Closes #2054 
Adds Query.IsNearLevel() method to Spatial_Engine. This method accepts an IElement, a Level, and a double maxDistance as input, and tests the IElement for proximity to the Level, returning true if the distance is lower than or equal to maxDistance.
[IsNearLevel-Test.zip](https://github.com/BHoM/BHoM_Engine/files/5486948/IsNearLevel-Test.zip)
`Query.IsNearLevel()` Query method added in the `Spatial_Engine` for `IElement` class
While this method is heavily based on IsNearGrid(), creating it was not as straightforward, as there are no existing methods to measure the distance to a Level or even a Plane as far as I could tell. I tried to find a reasonably simple approach using the methods that were available, but I would like your feedback and suggestions if you have any.

Spatial_Engine: Add Query.IsNearLevel() method

---

Spatial_Engine/Query/IsNearGrid.cs

Adds a fallback method to IsNearGrid, which was originally merged into master with pull request #2093, and currently does not have one. See that and issue #2055 for general details.

Spatial_Engine: Add fallback method to Query.IsNearGrid()

---

Spatial_Engine/Query/PointLayout.cs

Closes #2153 
Replacing the only `Spatial_Engine` call to Clone with a call to ShallowClone
Original test file for PointLayout method is [here](https://burohappold.sharepoint.com/:f:/s/BHoM/Emvmzm2j1xBNhG1JBGXJhUwBfpkHzOg5NOSmEexzbWxDBw?e=m1CT07) named `Spatial_Engine-#1608-AddPointLayoutMethodsToLayoutObjects.gh`.
- call to `Clone` replaced with `ShallowClone`

Spatial_Engine: Replace clone methods

---

Spatial_Engine/Create/ShapeProfiles/AngleProfile.cs
Spatial_Engine/Create/ShapeProfiles/ChannelProfile.cs
Spatial_Engine/Create/ShapeProfiles/FabricatedBoxProfile.cs
Spatial_Engine/Create/ShapeProfiles/FabricatedISectionProfile.cs
Spatial_Engine/Create/ShapeProfiles/FreeFormProfile.cs
Spatial_Engine/Create/ShapeProfiles/GeneralisedFabricatedBoxProfile.cs
Spatial_Engine/Create/ShapeProfiles/GeneralisedTSectionProfile.cs
Spatial_Engine/Create/ShapeProfiles/KiteProfile.cs
Spatial_Engine/Create/ShapeProfiles/TSectionProfile.cs

Closes #2148 
Making sure all non-symmetrical profiles have their centroid of the curves aligned with the origin
https://burohappold.sharepoint.com/:f:/s/BHoM/EvwQushTTIdBnbiI0b_XPD0BtYWuomLySsxlJY6Yb6W7IQ?e=OFgPjD

Spatial_Engine: Align centroid with origin when creating profiles

---

Environment_Engine/Compute/MapRegions.cs

Closes #2151 
Regions that line intersect with the original region without overlapping is now sorted to regionsNotMatched output.
[testing.zip](https://github.com/BHoM/BHoM_Engine/files/5554277/testing.zip)

Environment_Engine: Add skipped regions to regionsNotMatched output

---

Environment_Engine/Modify/Copy.cs
Environment_Engine/Modify/RemoveOpening.cs
Environment_Engine/Modify/RemoveOpeningsByName.cs
Environment_Engine/Modify/SetGeometry.cs
Environment_Engine/Modify/SplitOpeningByGeometry.cs
Environment_Engine/Modify/SplitPanelByGeometry.cs
MEP_Engine/Modify/SetGeometry.cs

Closes #2173 
Removes the boolean input for ShallowClone in Environment_Engine and MEP_Engine

Environment_Engine: Remove boolean input for ShallowClone

---

Reflection_Engine/Modify/SetPropertyValue.cs
Reflection_Engine/Query/PropertyValue.cs

Closes https://github.com/BHoM/BHoM/issues/477
We can now access fragments through `GetProperty` by providing the name of the fragment type.
I have also mirrored that behaviour in SetProperty. This is a bit weirder because of the `name` input but this, at least, provide a functioning solution for those that don't know about `AddFragment`.
Definitely recommend trying your own thing but here's what I did:
I would prefer if https://github.com/BHoM/BHoM_Engine/pull/2142 was merged first as the two PRs are modifying the same file (although not the same lines) and this one is easier to fix if rebase doesn't work.

Reflection_Engine: Access fragment properties

---

Analytical_Engine/Modify/SetGeometry.cs
Analytical_Engine/Modify/SetInternalElements2D.cs
Analytical_Engine/Modify/SetOutlineElements1D.cs

Closes #2167
Note that the behaviour of `SetGeometry` and `SetOutlineElements1D` has now been updated to no longer update Guid in line with compliance and our strategy for persistency of the BHoM_Guids 
Noting @rolyhudson - your PR on Analytical Engine here https://github.com/BHoM/BHoM_Engine/pull/2145 - but touching different files.

Analytical_Engine: Replace calls to Clone methods with calls to Base DeepClone or ShallowClone

---

Geometry_Engine/Query/Normal.cs

Closes #2179
Changing the `Normal()` for `Polyline` and `PolyCurve` so it'll return a results even for self intersecting curves (with a proper warning).
The reason for that is because there exist some cases when the curve is distorted and is read as self-intesecting (because of e.g. tiny overlapping segments) but calculating correct normal vector is possible despites the distortion. 
On the other hand, failing other checks (closure and planarity) makes it always impossible to calculate normal. In these cases error is raised and null returned.
[Issue specific](https://burohappold.sharepoint.com/:f:/s/BHoM/Ev0hASsgYEFMtKvjgKEDinQB8e5CMzNdL_kl9JiuU7cwgw?e=ucs0iE) - BooleanUnion was crashing because of missing Normal of a distorted region. Now should work as expected.
[General test for …

Geometry_Engine: Normal() returns null with a warning instead of an error

---

Physical_Engine/Query/BottomCentreline.cs
Physical_Engine/Query/TopCentreline.cs

Closes #2190
On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FBHoM%5FEngine%2FPhysical%5FEngine%2FPhysical%5FEngine%2D%232190%2DTopBottomCenterlineBug&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4) - both curves should be exactly at 0, minor offset is caused by the difference in centroid calculation in Revit and BHoM.
- `TopCentreline` and `BottomCentreline` fixed to return correct curves

Physical_Engine: TopCentreline and BottomCentreline fixed to return correct curves

---

Physical_Engine/Physical_Engine.csproj
Physical_Engine/Query/BoundingBoxCentreline.cs
Physical_Engine/Query/GeometricalCentreline.cs

[Test File](https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/BHoM_Engine/Physical_Engine/Query/GeometricalCentreline.gh?csf=1&web=1&e=lFOaJv)
Additional method to be used in the [Revit_Toolkit PR #895](https://github.com/BHoM/Revit_Toolkit/pull/895). Creating an additional method similar to the TopCentreline and BottomCentreline methods. Returns the element's section bounding box geometrical centreline.

Physical_Engine: Add query method moving location line to the centre of the IFramingElement's section bounding box

---

Geometry_Engine/Modify/Rotate.cs
Geometry_Engine/Query/Angle.cs
Geometry_Engine/Query/Product.cs

Does not strictly speaking depend on, but solves an issue in conjunction with #2149 
Relates to #2109
Adds null checks to certain Vector methods in the Geometry_Engine:
* `Modify.Rotate()`
* `Query.Product()`
* `Query.Angle()`
This helps fix crashes related to pulling in Structures_Engine Panels, in conjunction with the fixes on the Structures side of things as adressed by #2149

Geometry_Engine: Add null checks to certain Vector methods

---

Serialiser_Engine/Objects/MemberMapConventions/BHoMDictionaryConvention.cs

Closes #2196 
Adding `ReadOnlyDictionary` type to the `BHoMDictionaryConvention` to allow for it to (de)serialise properly. Was causing issues with versioning that could be seen in https://github.com/BHoM/Versioning_Toolkit/pull/105
See https://github.com/BHoM/Versioning_Toolkit/pull/105 and general serialisation test here https://burohappold.sharepoint.com/:u:/s/BHoM/EWw_delJFgdHhDvtUCu4yWsBSYSs2QpDks-Wd2obaPte3g?e=oh5JLf

Serialiser_Engine: Treat ReadOnlyDictionary as Dictionary in Convention

---

BHoM_Engine/Query/FindFragment.cs

Closes #2211
Removing the added duplicate non-generic method for FindFragment. Having both causes the UI to crash.
@alelom could not find it used anywhere?
Any script that uses find fragment, or try to create a ne one

BHoM_Enigne: Remove duplicate FindFragment method

---

Facade_Engine/Compute/UniqueAdjacencies.cs
Facade_Engine/Query/IsAdjacent.cs

Closes #2215 
Fixes dictionary handling issues leading to non matching adjacency elements.
[201204-TestFacadeEngineAdjacencyAndAreaMethods.zip](https://github.com/BHoM/BHoM_Engine/files/5646190/201204-TestFacadeEngineAdjacencyAndAreaMethods.zip)

Facade_Engine: Fixed dictionary bug for adjacency check

---

Structure_Engine/Create/MaterialFragments/Aluminium.cs
Structure_Engine/Create/MaterialFragments/Concrete.cs
Structure_Engine/Create/MaterialFragments/Steel.cs
Structure_Engine/Create/MaterialFragments/Timber.cs
Structure_Engine/Query/EmbodiedCarbon.cs

https://github.com/BHoM/BHoM/pull/1121
https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/BHoM/Structure_oM/Issue1070-RemoveEmbodiedCarbonFromMaterialFragments?csf=1&web=1&e=A2B66W
- Removed `EmbodiedCarbon` from `Create` methods for `MaterialFragments` 
- Added `PreviousVersion` attribute for `MaterialFragments` `Create` methods
- Removed Engine methods that calculate the embodied carbon of `Bar` and `Panel` objects

Align with changes to Structure_oM with removal of EmbodiedCarbon from MaterialFragments

---

BHoM_Engine/Query/Hash.cs

BHoM_Engine: Query.Hash() to return a Hash also when an object with all empty or null properties is input

---

.ci/code/Serialiser_Test/Helpers/TestObjects.cs
.ci/code/Serialiser_Test/Helpers/TypesToTest.cs
.ci/code/Serialiser_Test/Properties/AssemblyInfo.cs
.ci/code/Serialiser_Test/Serialiser_Test.csproj
.ci/code/Serialiser_Test/Verify/ToFromJson.cs
.ci/code/Verification.sln

- https://github.com/BHoM/BHoM/pull/1122
- https://github.com/BHoM/Test_Toolkit/pull/307
Closes #2221
This provides the Verification of the `Serialiser_Engine` in a format that can be executed by the BHoMBot.
Just run the TestRunner in `ProgramData/BHoM/Assemblies` by providing `Serialiser` as first argument.
If the BHoMBot is already capable of running this, you can also test it that way.
@FraserGreenroyd , I suppose the key thing here is to make sure that you are happy with the general framework on this PR and the two it depends on. From our discussion yesterday, I feel this should be quite close but happy to modify as needed.

CI: Add CI test for Serialiser_Engine

---

Geometry_Engine/Query/Area.cs

Closes #2219 
Added null check to `Area(pSurf)` to allow calculations to continue if there are no openings found within the sample. 
[Test File](https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/BHoM_Engine/Geometry_Engine/%232220-Element2DAreaQuery.gh?csf=1&web=1&e=ETPGtS)
- Update `Area()`

Geometry_Engine: Add null check to Area(pSurf)

---

Facade_Engine/Compute/EdgeAdjacencies.cs
Facade_Engine/Query/IsAdjacent.cs

Closes #2238 
Fixes bug for checking adjacency of matching edges.
[201204-TestFacadeEngineAdjacencyAndAreaMethods.zip](https://github.com/BHoM/BHoM_Engine/files/5646190/201204-TestFacadeEngineAdjacencyAndAreaMethods.zip)

Facade_Engine: Adjacency check bugfix for matching edges

---

Serialiser_Engine/Objects/BsonSerializers/CustomObjectSerializer.cs
Serialiser_Engine/Objects/BsonSerializers/DeprecatedSerializer.cs
Serialiser_Engine/Objects/BsonSerializers/ObjectSerializer.cs

Closes #2200
The serialiser was not calling the versioning toolkit for classes that had only seen a change of their properties. This PR fixes that.
See issue

Serialiser_Engine: Fix serialisation of non upgraded objects with modified properties

---

Serialiser_Engine/Objects/BsonSerializers/DeprecatedSerializer.cs

Closes #2240 
Rolling back https://github.com/BHoM/BHoM_Engine/pull/2217 changes as it caused issues with de-serialising the same type of object multiple types. Stack counter was never reset, which meant 10 items of a specific type was versioned correctly, then all the rest, for the entire session of rhino/GH, never could upgrade an object of that type any longer.
Especially issue when you have multiple objects referring to the same object (with same id) needing upgrading.
Testing shows that this code was not needed, giving the same result on the verification scripts with or without this. Removing this code however, get some scripts with significant amounts of serialised obejct working, that where previously failing (see Create Walls script in test files folder).
Also, Spaces are …

Serialiser_Engine: Roll back counter from Deprecated serialiser

---

Serialiser_Engine/Objects/BsonSerializers/TypeSerializer.cs

Closes #2242 
This solves the problem described in https://github.com/BHoM/BHoM_Adapter/issues/271#issuecomment-747968997 for me.
Why is the Error thrown even if FullName is empty? Why is deserialization attempted with FullName emtpy?
It seems it comes from a limitation in Mongo, that we are dealing with when serializing on line 59:
https://github.com/BHoM/BHoM_Engine/pull/2243/files#diff-97ac4289062918885fd1d3f995c876f456d9be4b96b3c21b0b5818bdda4c9881L59-L66
in order to make the structure symmetric, this PR "mirrors" this in the deserialization.

Serialiser_Engine: check if FullName is empty before returning Error in TypeSerializer

---

Geometry_Engine/Query/Centroid.cs

Closes #2254 
Changing logged warning into an error in case of self-intersection following the rule of _returning no result -> error_.
Also unified error messages.
Not needed as only descriptions and type of event is changed. [Here](https://burohappold.sharepoint.com/:f:/s/BHoM/Em--fsAco_FLhMZiO5irRVIB3aAnOxh9kJpZZhZeNolmOA?e=t996WA) is the general test file for `Centroid()`.
- Updated logged events in `Centroid()` methods in the `Geometry_Engine`.

Geometry_Engine: Correcting logged events in Centroid methods

---

Reflection_Engine/Query/TypeList.cs

Closes #2258
See issue for details
Make sure that the `CreateEnum` component doesn't have an empty menu anymore and that `CreateType` is able to create enum types

Reflection_Engine: Remove the condition that BHoMTypeList can only contain IObjects

---

Reflection_Engine/Convert/ToText.cs
Reflection_Engine/Query/AssemblyList.cs
Reflection_Engine/Query/UsedAssemblies.cs

Provide support for this UI PR: 
A few small fixes needed for the new RunCode component to work properly (see changelog).
- Fix hard-coded separator instead of using the one provided as input in the ToText method
- Make sure assemblies are collected only once even for BHoM dlls
- Allow to collect indirect references in UsedAssemblies

Reflection_Engine: Fixes necessary for the RunCode component

---

Environment_Engine/Query/BottomLeft.cs
Environment_Engine/Query/BottomRight.cs
Environment_Engine/Query/NormalAwayFromSpace.cs
Environment_Engine/Query/TopRight.cs
Geometry_Engine/Query/Centre.cs

Pull requests removing references to `Centre()`:
- [XML_Toolkit](https://github.com/BHoM/XML_Toolkit/pull/519)
- [IES_Toolkit](https://github.com/BHoM/IES_Toolkit/pull/168)
Closes #944 
Deprecating `Query.Centre(Polyline)` as it is generally incorrect. All references are being changed to `Centroid()`.
Not needed as it doesn't affect a logic of any method, however [here](https://burohappold.sharepoint.com/:u:/s/BHoM/ETgDDrmqBoZNvApme34KNDcBOT7zjI5DWfZlWrTE3oOcAA?e=Jr2EtM) is the script I used to check if any reference has been missed.
- Deprecating `Query.Centre(Polyline)` method in the `Geometry_Engine`.
- Updating methods in `Environment_Engine` to call for an average non-duplicated control point.

Geometry_Engine: Removing Centre(Polyline)

---

Geometry_Engine/Query/Area.cs
Geometry_Engine/Query/IsContaining.cs
Geometry_Engine/Query/Length.cs
Geometry_Engine/Query/Radius.cs
Graphics_Engine/Convert/ToSVGString.cs

Closes #945
Closes #946
Deprecating `Query.Radius(Arc)` as `Radius` is a public property of the `Arc` class.
**EDIT**
Decided to merge this one with #946 as they both update `Area.cs` and I didn't want to wait until this one get merged 😉 
**/EDIT**
**945**
Not needed as it doesn't affect a logic of any method, however [here](https://burohappold.sharepoint.com/:u:/s/BHoM/EW9cmLWzc7ROrZw_5Sb7UHMBU36t3W9nmSuP3ElJ3YvY0A?e=xCspMY) is the script I used to check if any reference has been missed.
**946**
Not needed - only added warnings.
- Deprecating `Query.Radius(Arc)` method in the `Geometry_Engine`.
- Updating methods in `Geometry_Engine` to call for `Radius` _property_ instead of `Radius()` _method_.
- Adding warnings to `Query.Area` methods in the `Geometry_Engine` in cases of open curves.

Geometry_Engine: Removing Radius(Arc) and adding warnings to Area() methods

---

Reflection_Engine/Modify/SetPropertyValue.cs

Closes #2284
Changing a value stored in CustomData is now possible even if the corresponding key already exists
See issue

Reflection_Engine: Fix SetProperty of CustomData

---

Facade_Engine/Facade_Engine.csproj
Facade_Engine/Modify/DefineOffset.cs
Facade_Engine/Modify/SetOffsetFromFacetoFaceDist.cs

Closes #2266 
Added method SetOffsetFromFacetoFaceDefinition to Facade_Engine Methods. This method takes a user input offset (defined from face of glazing to face of panel) and applies it as a ConstructionOffsetFragment to an opening.

Facade_Engine: ConvertOffsetDefinition

---

Reflection_Engine/Create/MethodBase.cs
Reflection_Engine/Create/Type.cs
Reflection_Engine/Modify/MakeFromGeneric.cs
Versioning_Engine/Convert/ToNewVersion.cs
Versioning_Engine/Query/VersionKey.cs

Supports this PR in the Versioning Toolkit: https://github.com/BHoM/Versioning_Toolkit/pull/134
See that PR for more details

Versioning_Engine: Add support for custom message on items without an upgrade

---

.ci/code/Serialiser_Test/Helpers/ObjectTypesToTest.cs
.ci/code/Serialiser_Test/Serialiser_Test.csproj
.ci/code/Serialiser_Test/Verify/MethodsToFromJson.cs
.ci/code/Serialiser_Test/Verify/ObjectsToFromJson.cs
.ci/code/Serialiser_Test/Verify/TypesToFromJson.cs
Reflection_Engine/Create/MethodBase.cs
Serialiser_Engine/Convert/Bson.cs
Serialiser_Engine/Objects/BsonSerializers/MethodBaseSerializer.cs
Serialiser_Engine/Objects/BsonSerializers/ObjectSerializer.cs

Closes #2299
- Aligns the code with the recent changes to the Test_oM and Test_engine
- Adds serialisation verification for methods and types on top of the existing one for objects.
Call the TestRunner with the `Serialiser` parameter. Here's the result that I get:
```
PS C:\ProgramData\BHoM\Assemblies> .\TestRunner.exe Serialiser
Serialisation of Methods via json: 4383 methods available.
1 errors and 0 warnings reported.
Inner results:
BH.Engine.Adapter.Query.AdapterId(IBHoMObject bHoMObject, Type adapterIdFragmentType)
Error: Method BH.Engine.Adapter.Query.AdapterId(IBHoMObject bHoMObject, Type adapterIdFragmentType) is not equal to the original after serialisation.
Serialisation of Types via json: 1536 types available.
0 errors and 0 warnings reported.
Serialisation of Objects via json: …
```

CI/CD: Serialisation verification for methods and types

---

Reflection_Engine/Compute/RecordEvent.cs
Reflection_Engine/Query/Events.cs

https://github.com/BHoM/Grasshopper_Toolkit/pull/604
https://github.com/BHoM/BHoM_UI/pull/370
Provide changes required for fileName and project code to be saved by analytics. Two things were required here:
- `RecordEvent(Event)` needed to be public to save other types of events (ses code in the BHoM_UI PR for where it is needed)
- Fix a by where the private list of events was passed by the `CurrentEvents` method instead of a copy (see code in the Grashopper PR for where it is needed).
Will be tested alongside the [BHoMAnalytics PR](https://github.com/BHoM/BHoMAnalytics_Toolkit/pull/16)

Reflection_Engine: Make the RecordEvent(Event) method public

---

Analytical_Engine/Query/Geometry.cs

Closes #2324
Any object with a nul geometry property would cause the component in the UI to turn red due to missing null checks in the Geometry methods. This PR fixes that by adding `?` everywhere it is relevant.
Just drop an auto-constructor component for a Bar for example.

Analytical_Engine: Add null checks to Geometry methods

---

BHoM_Engine/BHoM_Engine.csproj
BHoM_Engine/Query/Geometry.cs
BHoM_Engine/Query/Geometry3D.cs
Physical_Engine/Physical_Engine.csproj
Physical_Engine/Query/Geometry3D.cs
Structure_Engine/Query/Geometry3D.cs
Structure_Engine/Structure_Engine.csproj

Closes #2304 
Closes #2314 
Closes #2315 
Adds the methods `Geometry3D` for objects. The main method `Geometry3D()` is in the base engine and works like the `Geometry()`. The other methods are reached through `RunExtensionMethods`. I have added only one methods for `Physical.Beam` objects. More will be added in later PRs.
Build a `Beam` and compute its `Geometry3D`:
to visualise it, because currently our BHoM Extrusions are not visualised, you need https://github.com/BHoM/TriangleNet_Toolkit/ `RenderMesh()` method.

BHoM_Engine: adding Geometry3D methods

---

Data_Engine/Compute/SplitRequestTreeByType.cs
Data_Engine/Modify/SimplifyRequestTree.cs
Data_Engine/Query/AllRequestsOfType.cs
Data_Engine/Query/Requests.cs

Closes #2310
[This](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FIssue%2FBHoM%2FBHoM%5FEngine%2FData%5FEngine%2F%232310%2DNestedRequestIssues%2Egh&parent=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FIssue%2FBHoM%2FBHoM%5FEngine%2FData%5FEngine) is an issue-specific file. However, all other files from [this folder](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FIssue%2FBHoM%2FBHoM%5FEngine%2FData%5FEngine&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4) should still work correctly.
- issues related to handling of nested requests have been fixed:
- …

Data_Engine: Handling of nested request issues fixed

---

Reflection_Engine/Compute/RunExtensionMethod.cs
Reflection_Engine/Query/ExtensionMethodToCall.cs
Reflection_Engine/Reflection_Engine.csproj

Closes #2328
On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FBHoM%5FEngine%2FReflection%5FEngine%2F%232331%2DExtensionMethodToCall%2Egh&parent=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FBHoM%5FEngine%2FReflection%5FEngine) - it only proves that the mechanism used up to date still works - the benefits coming from this PR will be tested more explicitly in #2321.
- `ExtensionMethodToCall` method isolated from `RunExtensionMethod`
What I do not like about the solution proposed in this PR is the fact that in case of execution failure the error message is missing the information about …

Reflection_Engine: ExtensionMethodToCall isolated from RunExtensionMethod

---

Reflection_Engine/Modify/SortExtensionMethods.cs

Closes #2326
On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FBHoM%5FEngine%2FReflection%5FEngine&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4) - the file is a bit lame, but I could not come up with a better example 🙈. I hope the code change will be self-explanatory.
- `SortExtensionMethods` improved to return the most relevant method when the type-specific one does not exist
`type` parameter is now used to filter out the methods that are not relevant at all - possibly it could be removed, based on assumption that the methods are already prefiltered.
I was a bit concerned about the performance of `GetParameters` - I have tested it explicitly and there …

Reflection_Engine: SortExtensionMethods improved to return the most relevant method

---

Reflection_Engine/Modify/SortExtensionMethods.cs

Closes #2344
On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FBHoM%5FEngine%2FReflection%5FEngine%2F%232345%2DSortExtensionMethodsOnGenerics%2Egh&parent=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FBHoM%5FEngine%2FReflection%5FEngine) - the results do not matter, the methods should just trigger.
- `SortExtensionMethods` fixed to work on generics
@adecler it would be great if you could prioritise this PR as it breaks quite a few things across the entire engine 😭 
An alternative fix could also be move the -1 level methods to the end of the returned list instead of ruling them out: …

Reflection_Engine: SortExtensionMethods fixed to work on generics

---

Spatial_Engine/Compute/OrientationAngleLinear.cs
Spatial_Engine/Spatial_Engine.csproj
Structure_Engine/Compute/OrientationAngle.cs
Structure_Engine/Create/Elements/Bar.cs
Structure_Engine/Modify/SetNormal.cs

Closes #2336
On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FBHoM%5FEngine%2FSpatial%5FEngine%2F%232337%2DOrientationAngleLinear%2Egh&parent=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FBHoM%5FEngine%2FSpatial%5FEngine) - only versioning is tested, nothing else had changed effectively. Please remember to rebuild Versioning_Toolkit before testing.
- `OrientationAngleBar` migrated to Spatial_Engine and renamed to `OrientationAngleLinear`

Spatial_Engine, Structure_Engine: OrientationAngleBar migrated to Spatial_Engine and renamed to OrientationAngleLinear

---

Structure_Engine/Modify/Transform.cs
Structure_Engine/Structure_Engine.csproj

Contributes to resolving #2322
On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FBHoM%5FEngine%2FStructure%5FEngine%2F%232322%2DTransform%2Egh&parent=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FBHoM%5FEngine%2FStructure%5FEngine). I have disabled the test of FEMeshes because for some weird reason they slow GH down badly even if a completely unrelated part of the script gets modified - I could not come up with an explanation for that, maybe the reviewer will have an idea 😃 However, this is outside of the scope of this PR, because the above issue does not affect the correctness of the …

Structure_Engine: Transform methods added for structural elements

---

Reflection_Engine/Compute/TryRunExtensionMethod.cs
Reflection_Engine/Reflection_Engine.csproj

Closes #2348
Adds a TryRunExtensionMethod. If no method is found, returns false. Otherwise, invokes the method and passes the output in the `out` parameter, then returns true.
Test with any choice of extension methods.

Reflection_Engine: Added TryRunExtensionMethod

---

Reflection_Engine/Compute/RunExtensionMethod.cs

Temp solution for #2377 as explained in the issue
On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FBHoM%5FEngine%2FReflection%5FEngine%2F%232378%2DRunExtensionMethodError%2Egh&parent=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FBHoM%5FEngine%2FReflection%5FEngine)
- null method message introduced in RunExtensionMethod commented out temporarily

Reflection_Engine: Null method message introduced in RunExtensionMethod commented out temporarily

---

Data_Engine/Query/Requests.cs

Closes #2332
Versioning tested [here](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FBHoM%5FEngine%2FData%5FEngine%2FData%5FEngine%2D%232385%2DRequestsInWrongClass%2Egh&parent=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FBHoM%5FEngine%2FData%5FEngine) - please remember about rebuilding Versioning_Toolkit.
- `Requests` method moved to `Query` class

Data_Engine: Requests method moved to Query class

---

Facade_Engine/Facade_Engine.csproj
Facade_Engine/Modify/Transform.cs

Contributes to resolving #2383
On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FBHoM%5FEngine%2FFacade%5FEngine%2F%232383%2DTransform) - a trick with a cluster converting `FrameEdge` to `Bar` has been used to validate the results.
- `Transform` methods added for facade elements: `FrameEdge`, `Opening`, `Panel` and `CurtainWall`

Facade_Engine: Transform methods added

---

Humans_Engine/Query/CvalueAnalysis.cs

https://github.com/BHoM/BHoM/issues/1221
Property name change versioned for CValueSettings
Previous version attribute for the CValueAnalysis method
Closes #2391 and https://github.com/BHoM/BHoM/issues/1221
Old components and old json strings in this [file](https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/BHoM/Humans_oM/%231221-CvalueVersioning/%231221_cvalueversioning.gh?csf=1&web=1&e=D0d4O0)

Humans_Engine: Add previous version attribute to CvalueAnalysis

---

Geometry_Engine/Query/Normal.cs
Structure_Engine/Modify/Transform.cs

Closes #2397
On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FBHoM%5FEngine%2FStructure%5FEngine%2F%232398%2DPanelTransformBug&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4).
- `Transform` stopped from crashing for panels with nurbs edges
Component going red due to the underlaying error looks a bit weird, but at least the method works...

Structure_Engine: Transform stopped from crashing for panels with nurbs edges

---

Geometry_Engine/Modify/Transform.cs

Closes #2339 
Replacing former matrix determinant check with new `IsRigidTransformation` query.
[Here](https://burohappold.sharepoint.com/:f:/s/BHoM/En2Ibg00v25HmGzTJBBz76cBJaFHnTPrNFJoBsnZQo7SVQ?e=aRLQKc) sits the general test for transfom. We can also just run the unit test ☺️ 
- Added `IsRigidTransformation` check to the `Transform` methods in the `Geometry_Engine`.

Geometry_Engine: Adding proper rigidness check to the Transform methods

---

Reflection_Engine/Query/InheritedTypes.cs

Closes #2330
On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FBHoM%5FEngine%2FReflection%5FEngine%2F%232402%2DNullInInheritedTypes%2Egh&parent=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FBHoM%5FEngine%2FReflection%5FEngine).
- InheritedTypes stopped from passing nulls to output

Reflection_Engine: InheritedTypes stopped from passing nulls to output

---

Facade_Engine/Query/FrameGeometry2D.cs
Facade_Engine/Query/SolidVolume.cs
Facade_Engine/Query/WidthIntoOpening.cs

Closes #2403 
Resolved issues with how some engine methods were handling null frame edge properties so that handling is improved and warnings are clearer where applicable.
[Test Script and Rhino File](https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/03_Alpha/BHoM/BHoM_Engine/Facade_Engine?csf=1&web=1&e=bu66s8)
(Test by changing one or more of the FrameEdgeProperties assigned to the openings to null / empty)

Facade_Engine: Added null FrameEdgeProperty handling and improved warnings and errors

---

Physical_Engine/Modify/Transform.cs

Closes #2415
On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FBHoM%5FEngine%2FPhysical%5FEngine%2F%232415%2DTransformPolySurface%2Egh&parent=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FBHoM%5FEngine%2FPhysical%5FEngine)
- `BH.oM.Physical.Elements.ISurface` stopped from failing to transform when their Location is not `PlanarSurface`
Hopefully it will be an easy one to review since there were a few similar PRs in the near past. Please note that a wider discussion about the possibility of applying a non-planar surface to an `IElement2D` has been started in …

Physical_Engine: ISurface stopped from failing to transform when their Location is not PlanarSurface

---

.ci/code/Engine_Test/Engine_Test.csproj
.ci/code/Engine_Test/Properties/AssemblyInfo.cs
.ci/code/Engine_Test/Verify/NullChecks.cs
.ci/code/Serialiser_Test/Properties/AssemblyInfo.cs
.ci/code/Verification.sln

Closes #2335
Note that I have considered, for now, that it is acceptable to assume that strings and Lists will be at worst empty, never null.
This is because the UI can be used as a safe-guard on those two. That doesn't obviously protect against internal calls that could provide a null for those,. But I think we can start by focussing on the null objects given how many methods are failing even that right now (1729).
Run `./TestRunner NullChecks`. 
The full result is exceeding the content of the command window right now. So I have added a few lines to write to an temp file that you can uncomment.
- There was a method in `LifeCycleAssessment` that was causing a stack overflow. Since we cannot catch those, I have just added the method to the list of exception for now until it is fixed.
- …

CI/CD: Add test to make sure all methods can work with null inputs

---

BHoM_Engine/Query/FilterByType.cs

Closes #2237
The `IsAssignableFrom` was used backwards. This PR fixes that.
https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/BHoM_Engine/BHoM_Engine/%232237-FixFilterByType?csf=1&web=1&e=mFMbIK

BHoM_Engine: Fix FilterByType

---

BHoM_Engine/Create/IObject/RandomObject.cs

Closes #2408 
Added code suggestion made in the issue with a few minor tweaks. 
Create random objects of any type that has a `DateTime` property (I used Issue).

Base_Engine: Create a useable DateTime for RandomObject

---

Reflection_Engine/Modify/SetPropertyValue.cs

Reflection_Engine: Make sure no warning is shown when setting property of a CustomObject

---

Analytical_Engine/Query/Geometry.cs
Architecture_Engine/Query/Geometry.cs
Environment_Engine/Query/Geometry.cs
Geometry_Engine/Query/Geometry.cs
MEP_Engine/Query/Geometry.cs
Physical_Engine/Query/Geometry.cs
Structure_Engine/Query/Geometry.cs

Closes #2417 
Adding the necessary null checks on `Query.Geometry` methods.
the `Query.Geometry(IFace)` method actually records errors on its own. Not sure if we should keep them or not. They make sense for that very specific case so I'm happy either way.
https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/BHoM_Engine/Geometry_Engine/%232417-NullChecksForGeometryMethods/GeometryNullChecks.gh?csf=1&web=1&e=ZXKtpw
@FraserGreenroyd , those changes are purely adding null checks so I assume this is safe to merge (after thorough review of course). But happy to wait if you disagree.

BHoM_Engine: Adding null checks on geometry methods

---

Serialiser_Engine/Convert/Json.cs

Closes https://github.com/BHoM/Excel_Toolkit/issues/279
Excel internalised its data by saving the dictionary of internalised objects as json into an hidden sheet.
Unfortunately, some code added to the ToJson method to tackle serialisation of arrays and lists (by checking for `IEnumerable`) modified the serialisation result of Dictionaries. Fortunately, this only affected the serialisation of Dictionaries as top object, not as properties. 
This PR makes sure that dictionaries are not treated as arrays when serialised. Thankfully, the change required was such that it doesn't risk to break anything else.
https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/BHoM_Engine/Serialiser_Engine/Excel%23279-FixSerialisationOfDictionaries?csf=1&web=1&e=J4KAgY …

Serialiser_Engine: Fix serialisation of Dictionary as top level object

---

Serialiser_Engine/Compute/RegisterClassMap.cs

Closes #2455 
The changes made in [this PR](https://github.com/BHoM/BHoM_Engine/pull/2453) broke the serialisation of components. When moving the code around, one behaviour was changed: Generic types were trying to add their discriminator conventions every time they were serialised instead of just the first time (since the code for registering types for the first time and on the fly was merged into one). Unfortunately, Mongo throws an exception when you try to do that.
So here's the changes that I have made:
- Only skip the registration of the class map if the type is a generic type definition (e.g. `List<T>`), not just a generic type (e.g. `List<string>`. This should have been done this way from the very beginning so this is an improvement on the original code too. The reason why class …

Serialisation_Engine: Fix Serialisation of Generics

---

BHoM_Engine/Query/Geometry.cs
BHoM_Engine/Query/Geometry3D.cs
BHoM_Engine/Query/GetAllFragments.cs
BHoM_Engine/Query/Hash.cs
BHoM_Engine/Query/UniquenessRestrictions.cs

BHoM_Engine: Handle nulls

---

Environment_Engine/Modify/SetAdjacentSpaces.cs

Fixes #2474 
Have versioned as well for the change so this should be good to go if the checks come back green.

Environment_Engine: Fix typo in method name + versioning for method as appropriate

---

MEP_Engine/Compute/PlumbingFixtureWaterDemandPerDay.cs
MEP_Engine/Create/Elements/CableTraySectionProperty.cs
MEP_Engine/Create/Elements/Duct.cs
MEP_Engine/Create/Elements/DuctSectionProperty.cs
MEP_Engine/Create/Elements/Pipe.cs
MEP_Engine/Create/Elements/PipeSectionProperty.cs
MEP_Engine/Create/Elements/WireSectionProperty.cs
MEP_Engine/Create/Elements/WireSegment.cs
MEP_Engine/MEP_Engine.csproj
MEP_Engine/Query/Centreline.cs
MEP_Engine/Query/CircularEquivalentDiameter.cs
MEP_Engine/Query/FaceAreaByVelocity.cs
MEP_Engine/Query/HydraulicDiameter.cs
MEP_Engine/Query/MaterialComposition.cs
MEP_Engine/Versioning_42.json
Security_Engine/Query/Centreline.cs
Security_Engine/Query/Geometry.cs

Fixes #2460 
@enarhi I have also fixed the methods in Security_Engine which were failing too. This includes the query method of Geometry for a `CameraDevice` which was incorrectly in the `BH.Engine.MEP` namespace instead of the `BH.Engine.Security` namespace. I have versioned this change appropriately and should be evidenced by the green ticks when the checks finish.

MEP_Engine: Fix null handling

---

Reflection_Engine/Modify/SetPropertyValue.cs

https://github.com/BHoM/Excel_Toolkit/pull/283
Provides support for https://github.com/BHoM/Excel_Toolkit/pull/283 although this can be merged separately.
Otherwise as the title said, this enables setting an enum property by providing a string directly instead of an enum of the correct type.
https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/BHoM_Engine/Reflection_Engine/ExcelToolkit%23158-SetEnumPropertyWithString.gh?csf=1&web=1&e=lFCcQN
Although I find testing in Grasshopper easier, you can obviously test this in Excel VBA using something like this:
```vba
Dim bhom As New Excel_UI.Server
Dim obj As New Excel_UI.Object
Call obj.SetType("BH.oM.Acoustic.Rasti")
Call obj.SetProperty("Frequency", "BH.oM.Acoustic.Frequency.Hz125")
Dim objJson As …
```

Reflection_Engine: Add support for setting an enum property from a string

---

Diffing_Engine/Compute/DiffRevisions.cs
Diffing_Engine/Convert/TryParseObjectToGuid.cs
Diffing_Engine/Create/Delta.cs
Diffing_Engine/Create/Revision.cs
Diffing_Engine/Query/RevisionFragment.cs

Fixes #2468 - ain't never too late!
Bonus points to whoever gets the reference after the issue number...

Diffing_Engine: Handle nulls

---

Environment_Engine/Create/Panel.cs
Environment_Engine/Query/OpeningsFromPhysical.cs

Closes #2496 
Fixes the bug where PanelsFromPhysical and Panel components are not running for panels with openings without internal edges.
[TestFiles.zip](https://github.com/BHoM/BHoM_Engine/files/6420173/TestFiles.zip)

Environment_Engine: Skip IInternalEdges when set to null

---

Serialiser_Engine/Objects/BsonSerializers/ColourSerializer.cs

Closes #2501
On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FIssue%2FBHoM%2FBHoM%5FEngine%2FSerialiser%5FEngine%2F%232501%2DColourSerialisationBug&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4).

Serialiser_Engine: colour serialisation bug fixed

---

Reflection_Engine/Convert/ToText.cs

Closes #2505
See issue
https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/BHoM_Engine/Reflection_Engine/%232505-TypeToTextBug.gh?csf=1&web=1&e=JI7rMJ
Note that `[,]` is used to represent a matrix and is considered as a single type. So the separator is not applied there (Excel deals with that separately).

Reflection_Engine: Fix recursive ToText on types

---

Serialiser_Engine/Compute/RegisterClassMap.cs
Serialiser_Engine/Convert/Bson.cs
Serialiser_Engine/Objects/BsonSerializers/ColourSerializer.cs
Serialiser_Engine/Objects/BsonSerializers/CustomObjectSerializer.cs
Serialiser_Engine/Objects/BsonSerializers/DictionarySerializer.cs
Serialiser_Engine/Objects/BsonSerializers/EnumSerializer.cs
Serialiser_Engine/Objects/BsonSerializers/ObjectSerializer.cs
Versioning_Engine/Modify/AddVersion.cs

Closes #2346
This add the versioning info to each object during serialisation. 
It is important to note that only version 4.1 will be able to open files from version 4.2. We've never had a good support for backward compatibility. So it was already not recommended to open a file from a version more recent than what is installed on your machine since modified objects/methods would likely break. This, however would break every single component for version 4.0 and older trying to open a file from version 4.2. Looking at BHoM analytics, we currently have around 45% of the people using version 4.0 or older.   
Again, this only affects versions 4.0 and older opening files from 4.2 BUT I would not merge this PR until:
- We've properly communicated this change to our user base
- Everyone on this …

Versioning_Engine: Add BHoM version in serialisation

---

.ci/code/Engine_Test/Verify/NullChecks.cs
Facade_Engine/Compute/UValueOpeningCAM.cs
Facade_Engine/Compute/UValueOpeningSAM.cs
Facade_Engine/Compute/UValueOpeningsCAM.cs
Facade_Engine/Compute/UValueOpeningsSAM.cs
Facade_Engine/Facade_Engine.csproj

https://github.com/BHoM/BHoM/pull/1251
Closes #2508 
This PR adds methods for calculating effective UValue of one or many openings based on their constituent frame and glazing U values using two common methods: Single Assessment Method and Component Assessment Method.
https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/BHoM_Engine/Facade_Engine/%232508-UValueCalculationMethods?csf=1&web=1&e=D8xviw

 Facade_Engine: Added Methods to calculate UValues on elements based on new U and Psi fragments 

---

.ci/code/Engine_Test/Verify/NullChecks.cs

Closes #2529 
Adding check if the method is a Generic method, and if so, making use of the MakeFromGeneric method to make sure it can be called.
Code without this change simply crashes for all generic methods.
Testfile for a couple of methods here:
https://burohappold.sharepoint.com/:f:/s/BHoM/EjNwbhC-4KFMkZBRlmhKV0gBNiFkDp-F0fKFZXf2tBeuuQ?e=pWaxCa
Note that all of the methods in the testfile are not passing, but that they now throw more appropriate errors and warnings, not failing to cast errors.

Verification: Make sure NullCheck method can call Generic methods

---

Reflection_Engine/Modify/SetPropertyValue.cs

Closes #2534
This is as good as it can get without providing the format of the string containing the date. The C# method `dateTime.TryParse` does its best to figure out the format (e.g. even if only the date is provided without the time) but there will always be cases that are unsolvable. For example the American `mm-dd-yyyy` vs the British `dd-mm-yyyy`.  Better than what we had before without breaking anything so I am happy with the state of this PR.
This was mainly created within the context of the [Building Performance Excel form](https://github.com/BuroHappoldEngineering/BuildingPerformance_Toolkit/pull/6). So I recommend to make sure invalid dates are now properly handled within that context.

Reflection_Engine: Provide better support for setting a DateTime property with a string input

---

Geometry_Engine/Geometry_Engine.csproj
Geometry_Engine/Query/IsOrthogonal.cs
Spatial_Engine/Query/DominantVector.cs
Spatial_Engine/Spatial_Engine.csproj

Closes #2537
This new method queries `IElement1D` and `IElement2D` for their dominant vector (orientation). The logic is very simple, it groups all similar vectors and sort them by summed lengths. The longest length is the dominant vector and hence it's selected. The method also allows for orthogonal vector priority, where if true it tries to return orthogonal vectors, and a angle discrepancy tolerance when grouping vectors.
Test file is [here](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4&viewid=a5a93cba%2Dfcca%2D46cc%2Da31a%2D80b8d5cbfd7b&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FBHoM%5FEngine%2FSpatial%5FEngine%2F%232537%2DAddQueryDominantVector). I have not included …

Spatial_Engine: Add query dominant vector

---

Structure_Engine/Compute/PlasticModulus.cs
Structure_Engine/Modify/Transform.cs

Closes #2201
- Replaced calls to Geometry.Clone and Geometry.IClone to calls to Engine.Base.DeepClone(). Feel free to use Engine.Base.ShallowClone() where you feel appropriate.
- Replaced calls to GetShallowClone with calls to Engine.Base.ShallowClone()
Just compliance, no functional change.
- Review the code itself to make sure it compiles and makes sense
- Run the standard testing procedure that involve the structure engine

Structure_Engine: Replace calls to Clone, IClone, and GetShallowClone methods with calls to DeepClone and ShallowClone 

---

Geometry_Engine/Compute/DistributeOutlines.cs
Geometry_Engine/Create/PlanarSurface.cs
Geometry_Engine/Query/Area.cs

Closes #2575 
Tolerance param has been added to the create planar surface method and the `IArea` method that it relies on by way of the `DistributeOutlines` method. Take note of the change this has on the `IArea` method, as it now invokes tolerance but only a couple of the overloads actually use this tolerance (eg if `IIsClosed` is called before getting the area).
https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/BHoM_Engine/Geometry_Engine/%232575-ToleranceForPlanarSurfaceCreate?csf=1&web=1&e=Y0M3jI
Note that the test file shows a specific example of tolerance behaving as desired, but does not cover all existing unit tests and the like. @pawelbaran @rolyhudson please add a link here to any relevant test files we already have for this create …

Geometry_Engine: Added tolerance to Create PlanarSurface and methods it relies on

---

Geometry_Engine/Compute/DistributeOutlines.cs

Closes #2591
In the test file of https://github.com/BHoM/BHoM_Engine/pull/2528, see if `ConcreteFreeFormSection` turns red.

Geometry_Engine: DistributeOutlines fixed not to require the collection of openings not to be empty

---

Reflection_Engine/Modify/SetPropertyValue.cs

Closes #2613
Closes #2614 
- FragmentSet: The best way to test this is to try to push load combinations using [this file](https://burohappold.sharepoint.com/:x:/r/sites/Direction/designtechnology/RandDWishlist/00270_Load%20Case%20and%20Combinations%20Excel%20Tool/BuroHappold_BHoM_v4.3.beta_Loadcases%20and%20Combinations.xlsm?d=w20416a094cc24266aa6225fad5d7a64b&csf=1&web=1&e=RkFIKq)
- DateTime: [this file](https://burohappold.sharepoint.com/:x:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/BHoM_Engine/Reflection_Engine/%232614-DatetimeTest.xlsx?d=wb41a7dd8771d42b3ae21ae122eb662e3&csf=1&web=1&e=gSkxtv)

Reflection_Engine: Add ability to set Fragment property from list of objects

---

Facade_Engine/Query/MaterialComposition.cs
Facade_Engine/Query/SimpleGeometry.cs

Closes #2607 
Fixed bugs with the Facade MaterialComposition method, and improved error reporting accordingly.
https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/BHoM_Engine/Facade_Engine/%232607-MaterialCompositionImprovements?csf=1&web=1&e=jdFVHT

Facade_Engine: Fixed error handling and improved error/warning reporting for MaterialComposition

---

Geometry_Engine/Compute/DistributeOutlines.cs
Geometry_Engine/Create/PlanarSurface.cs

Closes #2621
Problem-specific test file has been uploaded on [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FBHoM%5FEngine%2FGeometry%5FEngine%2F%232622%2DDistributeOutlinesChecks&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4)
On top of that, worth running it in parallel with https://github.com/BHoM/Revit_Toolkit/pull/1082 and check the test files there (this was the original source of the issue actually).
This PR is as minimalistic as possible, it only sorts out the checks and messages, but does not change the return values etc. to avoid breaking changes if possible - to merge it safely before the Beta release. Possible future improvements in the next …

Geometry_Engine: planar surface creation and DistributeOutlines checks/messages refined

---

Serialiser_Engine/Convert/Bson.cs
Serialiser_Engine/Objects/BsonSerializers/MethodBaseSerializer.cs

Closes #2678
On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FBHoM%5FEngine%2FSerialiser%5FEngine%2F%232679%2DMethodInfoPropertyBug&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4).
As discovered together with @IsakNaslundBh, registering `MethodBaseSerializer` for `MethodInfo` seems to fix the issue. However, when we wanted to push it forward and do the same for other types such as `Type.GetType("System.RuntimeMethodInfo")` or `Type.GetType("System.RuntimeConstructorInfo")`, we broke the entire serialisation system. Therefore, the intervention I am proposing in this PR is as small as possible, with any further changes to be done in a separate, dedicated …

Serialiser_Engine: Serialisation of properties of type MethodInfo enabled

---

Reflection_Engine/Compute/LoadAllAssemblies.cs

Closes #2688
Closes #2691
On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FBHoM%5FEngine%2FReflection%5FEngine%2F%232690%2DLoadAllAssembliesRefinement&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4).
**Important:** please remember to rebuild BHoM_UI - a defaulted parameter has been added to `LoadAllAssemblies` signature, so the binding will be broken, even though CI check core will pass.

Reflection_Engine: LoadAllAssemblies refined to accept regular expression filters and allow parsing subfolders

---

Architecture_Engine/Query/Geometry.cs

Closes #2704
It is a simple property return, so no tests should be needed.
This is a breaking change (different return type compared to the original version of the method) - this cannot be avoided taken the nature of the bug (`Geometry()` _has to_ return `Point` for all types that implement `IElement0D` interface). Luckily, I do not think this type has been heavily used so far (if at all), taken it does not provide any interop features atm.
@IsakNaslundBh please shout if you are concerned about it and you have ideas how to lower the risk I introduce with this change.

Architecture_Engine: Geometry() query for BuildersWork.Opening refactored to return Point

---

BHoM_Engine/Modify/PropertyNamesToFullNames.cs
BHoM_Engine/Query/Hash.cs

Closes #2714
@FraserGreenroyd can you fill this in with your script?
Edit from @FraserGreenroyd :
@jamesramsden-bh and myself will be using the `XML_Toolkit_Push_Model.gh` file available [here](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?newTargetListUrl=%2Fsites%2FBHoM%2F02%5FCurrent&viewpath=%2Fsites%2FBHoM%2F02%5FCurrent%2FForms%2FAllItems%2Easpx&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F03%5FAlpha%2FBHoM%2FXML%5FToolkit&viewid=a5a93cba%2Dfcca%2D46cc%2Da31a%2D80b8d5cbfd7b) in line with the test procedure [here](https://burohappold.sharepoint.com/:w:/r/sites/BHoM/01_Master%20File/09_QAQC/04%20-%20Testing%20Procedures/0005_Environment/0001_XML_Toolkit.docx?d=w05e62d00b2c74e24a778fbed2cf33771&csf=1&web=1&e=qRBtNJ).

BHoM_Engine: fix for `Hash()` not dealing correctly with Enum types 

---

BHoM_Engine/Query/Hash.cs
Diffing_Engine/Compute/DiffWithHash.cs
Diffing_Engine/Compute/IDiffing.cs
Diffing_Engine/Query/ObjectDifferences.cs

https://github.com/BHoM/BHoM/pull/1333
Closes #2716 
Closes #2717 
Just run the following test file:
https://burohappold.sharepoint.com/:f:/s/BHoM/Epjl618V1IpNn0uEae_uFR0Bey9CYMXSDPNE-iUFuyYYoQ?e=bJt14l
and check that the panels correctly contains the objects as per text:
The correct execution of this test file guarantees that all changes in this PR work correctly. Further testing is not needed, but more tests can be found in:
https://burohappold.sharepoint.com/:f:/s/BHoM/ElkWAuBU0CpNhyNhwF96LlEBqkxJgHX3AhBOGlnA4bBwag?e=Kr2FMc
- Aligned the Diffing_Engine and base BHoM_Engine to the renamed `ComparisonConfig.CustomDataToConsider`
- Bug fix in `ObjectDifferences()`: `ComparisonConfig.NameSpaceExceptions` now correctly used
- Bug fix in `ObjectDifferences()`: `ComparisonConfig.MaxNesting` …

Diffing_Engine: alignments to changes to ComparisonConfig; minor bug fixes

---

Reflection_Engine/Compute/LoadAllAssemblies.cs

Closes #2712
On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?newTargetListUrl=%2Fsites%2FBHoM%2F02%5FCurrent&viewpath=%2Fsites%2FBHoM%2F02%5FCurrent%2FForms%2FAllItems%2Easpx&isAscending=true&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FBHoM%5FEngine%2FReflection%5FEngine%2F%232713%2DLoadAssembliesWithDots&sortField=LinkFilename&viewid=a5a93cba%2Dfcca%2D46cc%2Da31a%2D80b8d5cbfd7b).
This bug should not affect the Beta release (it was found while working on https://github.com/BHoM/Revit_Toolkit/pull/1137), so I am not pushing it - up to the framework lead whether worth merging now or after the end of the milestone @FraserGreenroyd.

Reflection_Engine: LoadAllAssemblies fixed to load assemblies with dot in name

---

Environment_Engine/Convert/OpeningFromPanel.cs

Closes #2595 
Created a method to create openings from a panel.

Environment_Engine: Create openings from a panel

---

Results_Engine/Query/DisplayMeshResults.cs
Results_Engine/Results_Engine.csproj

check if cased result for error message
https://github.com/BHoM/BHoM/pull/1328
Changing so that error message is only mentioning result case if the result is a cased result.
- Tweaking the way the result values are extracted to increase the performance.
Testing the MeshResultDisplay:
https://burohappold.sharepoint.com/:f:/s/BHoM/EmRmiGKVt5FFmQh7cOWCowQBR_MoUeNS5qPoemEjJmXrNw?e=sTvNF8

Results_Engine: Update DisplayMeshResults to work with simplified interface requirements

---

.ci/code/Engine_Test/Verify/NullChecks.cs

Closes #2513
- Changing from If to while statement to get nested inner exception. needed to fetch the actual exception for edge cases
- Adding `ArgumentNullException` as an explicit exception to raise as an error
- Adding `RuntimeBinderException` as an explicit exception to be raised as an error. Generally the exception thrown when calling an interface method with null, while it is trying to case as dynamic and fails to find a method matching
- Calling LoadAllAssemblies in begining, as no longer done by MethodList
- initialising empty dictionaries and hashsets instead of lists for those types.

Verification: Additional exceptions as errors for null checks

---

Facade_Engine/Compute/UValueOpeningAW.cs
Facade_Engine/Compute/UValueOpeningCAM.cs
Facade_Engine/Compute/UValueOpeningSAM.cs
Facade_Engine/Compute/UValueOpeningsAW.cs
Facade_Engine/Compute/UValueOpeningsCAM.cs

Closes #2662 
Fixed reliance on Psi/U Value fragments assigned to Construction properties rather than the element itself, and added multiple opening area weighted functionality.
https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/BHoM_Engine/Facade_Engine/%232662-SAMandCAMMethodUpdates?csf=1&web=1&e=HgP13D

SAM and CAM methods fixed and improved

---

Reflection_Engine/Query/IsDeprecated.cs

Fixes #2739 
Brings back in the checks for `Replaced` and `ToBeRemoved` attributes in the `IsDeprecated` method. Am keeping the method name for now as the name is fit for purpose in my book.

Reflection_Engine: Include Replaced and ToBeRemoved back to the IsDeprecated check

---

Humans_Engine/Query/AvalueAnalysis.cs
Humans_Engine/Query/CvalueAnalysis.cs
Humans_Engine/Query/EvalueAnalysis.cs

Aligns with https://github.com/BHoM/BHoM/pull/1358/commits/32809fc10519e474db31b0fddeafe41d247827ca
https://github.com/BHoM/BHoM/pull/1358
align the engine with changes made for https://github.com/BHoM/BHoM/issues/1350
Methods generating ViewQualityResults made to call the added constructor.

Humans_Engine: Align with making ViewQualityResults immutable

---

BHoM_Engine/Compute/ClearCurrentEvents.cs
BHoM_Engine/Compute/RecordEvent.cs
BHoM_Engine/Compute/RemoveEvent.cs
BHoM_Engine/Objects/Global.cs
BHoM_Engine/Query/DebugLog.cs
BHoM_Engine/Query/Events.cs
Data_Engine/Query/Children.cs

Closes #2009
Closes #2745
Not sure how to test it meaningfully - the code still works as previously and does not show any signs of issues. I think that the best way of tasting can be simply merging the change and watching the logs carefully for the coming 2 sprint to make sure that this does not break anything.
The approach taken has been discussed with @IsakNaslundBh: it seems to deliver best value for price:
- the log sits safely behind the lock
- the lock is `Global`, so it can be used across the entire project
- `Query.DebugLog` has already been `internal` so there is no risk of the collection being modified from the outside
An alternative that we discussed with @IsakNaslundBh was moving `BH.oM.Base.Debugging.Log` to the engine's `Objects` and encapsulating it properly. However, this …

BHoM_Engine: ThreadStatic attribute taken off the debug log and replaced by a lock

---

Geometry_Engine/Query/Bounds.cs

Closes #2755 
Adding empty return methods for Bounds of Face, TransformMatrix and Basis. This is mostly done to help with the UI:s that are calling those methods implicitly through the display pipeline, and in some cases this leads to non-sensical errors being thrown.

Geometry_Engine: Add empty bounds methods for Face, Basis and TransformMatrix

---

Results_Engine/Query/DisplayMeshResults.cs

https://github.com/BHoM/BHoM/pull/1360
Simplifies the generics of the DisplayMeshResults method made possible by changes in https://github.com/BHoM/BHoM/pull/1360
https://burohappold.sharepoint.com/:f:/s/BHoM/ElA50AT7KLJMmsPyw-40LhEBbfpjAEGTGpguxyR8mER5pQ?e=l3a5JP

Results_Engine: Simplifying Method Signature of DisplayMeshResults

---

.ci/code/Engine_Test/Verify/NullChecks.cs

CI: Exclusion added to the null checks

---

Facade_Engine/Modify/ExtendMullion.cs
Facade_Engine/Modify/ExtendProfile.cs

Closes #2770 
Adds two new methods. ExtendProfile extends profile edge curves relative to a provided extension box curve. ExtendMullion modifies a FrameEdgeProperty by extending profile curves relative to an extensionbox fragment assigned to the FrameEdgeProperty.
https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/BHoM_Engine/Facade_Engine/%232770-ModifyMullionDepth?csf=1&web=1&e=LtFp75

Facade_Engine: Method to Modify Section Profile Depth within FrameEdgeProperty

---

Results_Engine/Query/FilterResults.cs

https://github.com/BHoM/BHoM/pull/1376
Filtering strings rather than by IComparable to improve UX.
https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/BHoM/Analytical_oM/%231376-ChangeResultFiltersToStringHashSets?csf=1&web=1&e=ZxWpLB

Results_Engine: Checking ToString properties instead of IComparable for ResultFiltering

---

BHoM_Engine/Modify/SetGeometry.cs

Closes #2777
This method was not doing anything before and not even raising any warnings/errors that that was the case. Made sure it it correctly tries to dispatch to a SetGeometry method compatible with the object type and geometry type provided, and if failing to do so, raises an error.
https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/BHoM_Engine/BHoM_Engine/%232778-ISetGeometry-to-call-TryRunExtensionMethod?csf=1&web=1&e=aa36GG

Base_Engine: Making SetGeometry call TryRunExtensionMethod

---

Diffing_Engine/Query/NumericalDifferenceInclusion.cs

Closes #2807
Run [DiffingTests_Prototypes](https://github.com/BHoM/DiffingTests_Prototypes). The tests on RevitParameters should work (with the latest commit https://github.com/BHoM/DiffingTests_Prototypes/commit/74934df94a913c053d5c5393c74f6f9d4a766aa6, all tests should work).

Diffing_Engine: fix `NumericalDifferenceInclusion()` that did not trigger check on `IsNumerical()` correctly

---

Diffing_Engine/Compute/DiffWithCustomIds.cs
Reflection_Engine/Modify/SetNewEmptyIEnumPropsIfNull.cs

Closes #2806
Run [this test](https://github.com/BHoM/DiffingTests_Prototypes/commit/cfca2016d654603b39fd7cf6d8013a6779a9f58c) in the DiffingTests_Prototypes. If the test is run before compiling this PR, it will fail; otherwise, it will succeed.

Diffing_Engine: more null guarding against empty IEnumerables in the ComparisonConfig

---

Environment_Engine/Create/Opening.cs
Environment_Engine/Query/IsContaining.cs

Tolerance added to Opening, as per linked issue. 
Closes #2816
To test, create a Panel object, and place a point as the location along the bottom edge of the panel. Attempt to create a doorway. Then, move the point a tiny distance away (e.g. 0.001m). Then, adjust the tolerance value, and ensure the door is created successfully only when the tolerance is greater than this distance.

Environment_Engine: Add tolerance param to Opening

---

Data_Engine/Query/ValuesAt.cs

Data_Engine: Set Name and Tag in AsCustomObject()

---

Structure_Engine/Query/MaterialComposition.cs

Closes #2818 
Makes sure MaterialComposition works if no rebar is applied to concrete section
https://burohappold.sharepoint.com/:f:/s/BHoM/ErwwHG8L9P1Fk0W1tFnUujUBOVdXenAfUd1mCggfPl6N_A?e=v0Kb7r

Structure_Engine: Add null check for reinforcement in material composition

---

Data_Engine/Query/ValuesAt.cs

Closes #2825 
[on Sharepoint](https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/BHoM_Engine/Data_Engine/Data_Engine-%20%232827%20handle%20empty%20tags?csf=1&web=1&e=jd25g4)

Data_Engine: handle empty tags

---

Results_Engine/Query/FilterResults.cs

Closes #2837
Code change is hopefully quite self-evident. The method was always re-filtering the input collection, rather than stacking the filtering.
@alelom putting you as a reviewer as you been part of this part of the code before. Please let me know if you do not have capacity to review, and I will find someone else 😄 
https://burohappold.sharepoint.com/:f:/s/BHoM/EnZ2F3XH5JFEnUylsv_fHE4BwlswbS4zG1J8a9qv-QQDjg?e=JgS9OB

Results_Engine: Fix FilterBy not filtering by all properties.

---

Geometry_Engine/Create/IElement2D/NewInternalElement2D.cs
Geometry_Engine/Modify/SetInternalElements2D.cs
Geometry_Engine/Modify/SetOutlineElements1D.cs
Geometry_Engine/Query/InternalElements2D.cs
Geometry_Engine/Query/OutlineElements1D.cs

https://github.com/BHoM/BHoM/pull/1390
Closes #2812
Adding methods required for IElement2D.
For planar surfaces, the InternalElement2Ds will be returned as a set of new PLanarSurfaces, with ExternalBoundaries correpsonding to the InternalBoundaries of the host PlanarSurface. This is to fullfill the requirement that the openings must also be IElement2D, which is not the case for the closed curves. This workaround alows for the methods to behave as expected.
Potential at one point to add some form of Region class, that is like the PlanarSurface, but without any openings. There is no practical use for that class though, that can not be achieved with a PlanarSurface with no openings, more than clarity for methods like this. For now, I think this is the best solution forward, even it it at …

Geometry_Engine: Adding methods required by IElement2D for PlanarSurface

---

Library_Engine/Library_Engine.csproj
Library_Engine/Query/Library.cs
Library_Engine/Query/ValidatePath.cs
Versioning_Engine/Query/DatasetToMessageForDeleted.cs
Versioning_Engine/Query/DatasetToNewPaths.cs
Versioning_Engine/Query/DatasetToOldPaths.cs

Closes #1864 
- Add method for extracting Dataset upgrader paths in the Versioning_Engine
- Add method in Library_Engine to validate paths
- Add old paths to custom paths when extracting a library
The strategy is to make use of the ToNew for upgrading the UI components (updating the links for dropdowns) and the ToOld to supply additional paths for the library paths to search through.
This way more granular control is allowed over how the system should be working.
Files in https://github.com/BHoM/BHoM_Datasets/pull/122 can be used to test that the upgrade of components is functioning as intended
The reason this is not done via the versioning toolkit as other things is that the library engine requires access to the old paths to make sure old scripts with custom calls to the libraries still …

Library_Engine: Add versioning for libraries

---

Facade_Engine/Query/MaterialComposition.cs
Facade_Engine/Query/SolidVolume.cs

Closes #2848 
Errors and warnings have been improved, and the methods have been tweaked to improve quality of method outputs for various cases.
[#2848 GH and Rhino test files](https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/BHoM_Engine/Facade_Engine/%232848-VolumeAndCompositionAlignment?csf=1&web=1&e=WUsmvF)
To test, flip through the different dropdown options for FrameEdge, Opening, and Panel and constructions and confirm that the results / errors that result are as expected, and help inform the user what they need to provide to get the method to work accordingly.

Facade_Engine: Improvements to Facade SolidVolume and MaterialComposition Methods

---

BHoM_Engine/Query/Hash.cs

Closes #2844
The issue was that there was an old piece of code in the Hash function that was supposed to grab the Key of the CustomData dictionary when the input object was a CustomObject, to then determine what to do with this key. This part was not implemented properly. It was not discovered earlier due to lack of usage of this workflow. This is now fixed by moving the code in the correct area of the algorithm. I also added tests in the DiffingTests prototypes to capture this usage, see below.
- See #2844 (simply try to compute the Hash of any CustomObject) and/or
- run the DiffingTests in https://github.com/BHoM/DiffingTests_Prototypes. There are two new tests that cover this workflow within the `HashTests` class: [`CustomObjects_EqualHash`](https://github.com/BHoM/DiffingTests_Prototyp …

BHoM_Engine: fix Hash() method not working with CustomObjects

---

Diffing_Engine/Query/ObjectDifferences.cs

Closes #2856
Added tests in DiffingTests_Protoypes: https://github.com/BHoM/DiffingTests_Prototypes/commit/1ff0d9399e4feb9f3b2023d1ed21b9865c42d1fb.
Run all tests, all should pass.
- When diffing, the single property changes have now a Description which start by giving the Name of the modified object. The name is only given when it did not change between past and following object. 
- A minor bug was also fixed, in that the Type was incorrectly reported before. Now the type is not exposed anymore, unless an option is turned on.
- More options to customise the Description have been implemented, but all of them are currently private and therefore not accessible, although they will be exposed soon.
Note that this PR adds some new options as inputs to the private method called …

Diffing_Engine: `IPropertyDifference.Description` to contain modified object Name by default when possible

---

Facade_Engine/Query/MaterialComposition.cs

Closes #2864 
Made MaterialComposition return an empty MaterialComposition for a valid empty frame edge.
[Facade_Engine Test File](https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/03_Alpha/BHoM/BHoM_Engine/Facade_Engine?csf=1&web=1&e=s1STNX)

Facade_Engine: MaterialComposition tweak to return valid empty value for valid empty frame edge

---

Humans_Engine/Query/CvalueAnalysis.cs

Humans_Engine: Fix CValue variable use

---

Geometry_Engine/Query/FilterByNormal.cs

Closes #2876 
Added a method to filter a list of PlanarSurface objects by their surface normal, within a given tolerance.
[Geometry_Engine-#2876-AddFilterByNormal.zip](https://github.com/BHoM/BHoM_Engine/files/9008323/Geometry_Engine-.2876-AddFilterByNormal.zip)
- `Query.FilterByNormal()` Query method added in the `Geometry_Engine` for lists of PlanarSurface objects

Geometry_Engine: Added Query.FilterByNormal method

---

Graphics_Engine/Query/GradientLegend.cs
Spatial_Engine/Query/Bounds.cs

Closes #
Implicitly tested by https://github.com/BHoM/Revit_Toolkit/pull/1225

Spatial_Engine: bounding box query for profiles added

---

Diffing_Engine/Compute/DiffWithCustomIds.cs

Diffing_Engine: Fix incorrect method reporting in `IDiffing()`

---

Facade_Engine/Compute/UValueAW.cs
Facade_Engine/Compute/UValueOpeningAW.cs
Facade_Engine/Compute/UValuePanelAW.cs

Closes #2905 
- Updated UValueOpeningAW method to handle construction fragment UValueContinuous
- Created new method UValuePanelAW that calculates the u-value of a panel by area weighting the UValueContinuous assigned to panel construction and the u-values of all Openings within the panel
[Test File](https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/03_Alpha/BHoM/BHoM_Engine/Facade_Engine/Facade_Engine-TestPanelUValueWithFull.gh?csf=1&web=1&e=gqxrmF)

Facade_Engine: Update Methods to Handle UValueContinuous Fragment

---

Structure_Engine/Create/Loads/BarDifferentialTemperatureLoad.cs

Fix output label for BarDifferentialTemperatureLoad

---

BHoM_Engine/Modify/SetPropertyValue.cs

Closes #2918
Numbers represented as strings are not converted. This is relevant for both Excel and numbers in panels in Grasshopper.
The string should be automatically converted.

BHoM_Engine: Fix SetProperty of numbers represented as strings

---

BHoM_Engine/Compute/ParseEnum.cs
BHoM_Engine/Convert/ToText.cs

https://github.com/BHoM/BHoM/pull/1441
See https://github.com/BHoM/BHoM/issues/1440
Not a file per se since there isn't obviously a case of `DisplayText` usage in the BHoM yet. But here's a working example:
Best is to add the attribute yourself to a random enum and test that it is well supported. Happy to jump to a call if it is easier for the review though.

Add DisplayText support on enums

---

Versioning_Engine/Convert/ToNewVersion.cs

Closes #2940
Adding a simple lock around the for loop calling the BHoMUpgraders in attempt to make it thread safe.
Simplest way of dealing with this that I could think of, but open for this to be handled differently if a better way is suggested.
Hard to provide. To test, one can ensure to have analytics logs with methods requiring versioning (or failing to deserialise for other reasons) while opening a script requiring versioning.

Versioning_Engine: Adding lock around the upgrader loop in the ToNewVersion method.

---

BHoM_Engine/Compute/ExtractAssembly.cs
Versioning_Engine/Query/UpgraderVersions.cs

Closes #2953 
Two things are being fixed: 
- Check that the `C:\ProgramData\BHoM\Upgrades` folder exists before collecting Versioning upgraders to prevent errors in web apps.
- Filter out dynamic assemblies when extracting types as the call to the `ReflectionOnly` property is throwing an exception for them.
Test of the fix ran in a live session with @FraserGreenroyd as it requires testing the fix within a Blazor application.

Serialiser_Engine: Fix serialisation in Blazor web assemblies

---

Environment_Engine/Query/IsClosed.cs
Environment_Engine/Query/IsValid.cs

Environment_Engine: Add IsValid check for spaces

---

Serialiser_Engine/Objects/BsonSerializers/MethodBaseSerializer.cs

Closes #2823
Added a null check in [MethodBaseSerializer](https://github.com/BHoM/BHoM_Engine/blob/ae5f832e75f8f8a4d4f3b994e6253c4485a5e829/Serialiser_Engine/Objects/BsonSerializers/MethodBaseSerializer.cs) to avoid it throwing an exception during startup (plugin loading) as explained in #2823.
See #2823. I can provide an assembly that throws the error if deemed necessary.
- Added a null check in [MethodBaseSerializer](https://github.com/BHoM/BHoM_Engine/blob/ae5f832e75f8f8a4d4f3b994e6253c4485a5e829/Serialiser_Engine/Objects/BsonSerializers/MethodBaseSerializer.cs).

Serialiser_Engine: added null check in MethodBaseSerialiser

---

Environment_Engine/Query/IsShade.cs

Null handling protection added only to the second method as the first method is non-nullable.
Closes #2958

Environment_Engine: Adding null handling protection to IsShade method

---

Graphics_Engine/Convert/ToSVGString.cs

Closes #501
Simple code inspection is enough in this case
VS decided to automatically add a space between the `if` and he`(` but, other than that, this PR is only adding a fallback method without touching anything else.

Adding fallback method to IToSVGString(this IGeometry geometry)

---

Geometry_Engine/Modify/ProjectAlong.cs

Closes #2990 
Character changed to lowercase.

Geometry_Engine: project along lowercase character compliance

---

BHoM_Engine/Compute/RecordError.cs
BHoM_Engine/Compute/RecordEvent.cs
BHoM_Engine/Compute/RecordNote.cs
BHoM_Engine/Compute/RecordWarning.cs

Fixes #2011 
Code review should be suitable for these methods.

BHoM_Engine: Add methods to record events from exceptions

---

Structure_Engine/Create/Elements/Panel.cs

Closes #2961 
Adding tolerance the the Create.Panel methods in the Structural engine. At least for the ones where that makes sense. The other ones don't require any checks that involve the tolerance.
[CreatePlanarCurveWithTolerance.zip](https://github.com/BHoM/BHoM_Engine/files/10699657/CreatePlanarCurveWithTolerance.zip)

Structure_Engine - Adding tolerance to create panel methods

---

Environment_Engine/Modify/SplitOpeningByGeometry.cs
Geometry_Engine/Compute/Split.cs

Closes #2969
On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FBHoM%5FEngine%2FEnvironment%5FEngine%2F%233004%2DSplitOpeningFix&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4)

Environment_Engine: opening split bug fixed

---

Physical_Engine/Query/MaterialComposition.cs
Physical_Engine/Query/SolidVolume.cs
Physical_Engine/Query/VolumetricMaterialTakeoff.cs

Closes #2895
Updates so that Physical ISurface objects account for inner opening type objects, such as doors and walls, for computation of SolidVolume as well as MaterialComposition.
- Add method for VolumetricMaterialTakeoff
- Make MaterialComposition method rely on new method
- Make SolidVolume rely on the new method
Important that this _is_ changing behaviour, and would impact workflows like LCA, but should be to the better. Important that people using the tools are aware of this. @enarhi when review/merged would you be able to help spread this?
Also, smaller change, is I removed all errors/warnings regarding Void type openings, as imo, it is safe to simply return 0 volume/empty material composition for this type of object, given it by definition is meant to model nothingness.
Testfile …

Physical_Engine: Make physical surfaces return material and volume of all content

---

MEP_Engine/Compute/Mechanical/MassFlowRate.cs
MEP_Engine/Compute/Mechanical/ProcessLatentHeat.cs
MEP_Engine/Compute/Mechanical/ProcessSensibleHeat.cs
MEP_Engine/Compute/Mechanical/ProcessTotalHeat.cs

MEP_Engine: MEP Psychrometric Equations Unit and Descriptions Updated

---

BHoM_Engine/Convert/ToText.cs

Closes #3019
On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FBHoM%5FEngine%2FBHoM%5FEngine%2FExcel%5FToolkit%2D%2314%2DEnumValueBug&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4)

BHoM_Engine: IToText fixed for primitives and DateTime

---

.ci/unit-tests/Base_Engine_Tests/Query/IsNumeric.cs
.ci/unit-tests/Base_Engine_Tests/Query/IsNumericIntegralType.cs
BHoM_Engine/Query/IsNumeric.cs
BHoM_Engine/Query/IsNumericFloatingPointType.cs
BHoM_Engine/Query/IsNumericIntegralType.cs
Diffing_Engine/Query/NumericalDifferenceInclusion.cs

Closes #3025 
This PR adds a new `bool EnumAsNumeric = true` optional parameter to `IsNumeric()` and `IsNumericIntegralType()` methods. This is needed to clarify whether `enums` should be considered a numeric number or not. In certain contexts like Diffing (see #3025), `IsNumeric()` is used to parse a wide variety of types, and `IsNumeric` needs this option to clarify what it does, because we had Diffing failures in certain edge cases.
The default value of this new parameter `EnumAsNumeric` is set to `true`, so it keeps the same behaviour by default, avoiding problems with any existing reference to the method. The diffing engine method that needs this parameter was changed to pass `false` in.
Test with the newly added unit tests.
- Provided a new `EnumAsNumeric` optional input to …

BHoM_Engine: `IsNumeric()` to be explicit about whether enum types should be considered numeric

---

Structure_Engine/Modify/Transform.cs

Closes #3029
On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FBHoM%5FEngine%2FStructure%5FEngine%2F%233030%2DBarTransformBug&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4).

Structure_Engine: NullReferenceException on transform of a bar with null nodes fixed

---

Diffing_Engine/Query/NumericalDifferenceInclusion.cs

Closes #3039
Reworked the NumericalTolerance mechanism to compute the difference between the numbers, then see if it is larger than the specified tolerance.
See #3039.

Diffing_Engine: reworked the NumericTolerance mechanism

---

Serialiser_Engine/Compute/Deserialise.cs
Serialiser_Engine/Compute/Deserialise/Deprecate.cs
Serialiser_Engine/Compute/Deserialise/IObject.cs

Closes #3055
Add isUpgraded argument to DeprecateSerialiser and pass on bool
Especially critical for the call to this made from the main Deserialise method when the type upgrader failed, as this was the mechanism able to cause an infinite loop
CheckVerisoning should still pass.
Was trying to figure out a way to add a UT for this, but could not think of a simple case that is not to involved, as it require type upgrader to fail, but an explicit upgrader to run and return a faulty type.

Add isUpgraded argument to DeprecateSerialiser and pass on bool

---

Serialiser_Engine/Compute/Deserialise/IObject.cs

Minor spelling error found during other testing. Didn't raise an issue for this as it's so incredibly minor it didn't seem worth it.

Serialiser_Engine: Minor spelling fix for error passed to UI

---

Humans_Engine/Query/CvalueAnalysis.cs

Closes #3075 
- Moved URLs inside DocumentationURL

Humans_Engine: Moved URLs inside DocumentationURL

---

Serialiser_Engine/Compute/Deserialise/IObject.cs

Closes #3066 
As detailed in the issue, the BHoM UI was crashing on the deserialisation of a specific dataset. It appears that the 'failed' boolean that is passes up from properties to parents was used to force a different deserialisation behaviour inside the `SetProperties` method. 
- The issue is that that boolean is never reset between properties. This means one incorrect property would trigger a failing behaviour on all the following ones. 
- Deserialisation is also capable of restoring partial objects by saving the remaining properties inside CustomData. Those objects were still marked as 'failed' though causnig the whole chain of parents to come back as Custom objects. 
As the only place where the 'failed' boolean is used for a conditional check is inside the `SetProperty` method …

Fix serialiser crash on failed

---

Security_Engine/Query/ViewCone.cs

Closes #3098 
Corrected angle calculation for `Camera Field of View`.
[Rhino and GH files](https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/BHoM_Engine/Security_Engine/%232888-CameraFieldOfView?csf=1&web=1&e=rWkaoD)

Security_Engine: Camera Field of View angle fix

---

Security_Engine/Query/ViewCone.cs

Closes #3100 
Corrected calculation of camera field of view cone shape. This change is to precise the value of horizontal field of view:
Before (HoV = 1000):
After (HoV = 1000):

Security_Engine: Camera Field of View - cone shape calculation fix

---

Facade_Engine/Query/GeneralMaterialTakeoff.cs

Closes #3091 
Added `GeneralMaterialTakeoff` methods for Facade namespace, so that takeoffs for these elements properly account for area and volumes.
[Test File](https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/BHoM_Engine/Facade_Engine/%233091-AreaTakeoffFix?csf=1&web=1&e=bPXCod)
To test, check the Panel, Opening, etc elements and confirm area takeoffs and LCA values work correctly for the Area EPD/material applied. 
I have implemented this for Facade elements within Facade_Engine. Technically we could implement higher, but it seems to make sense with how @IsakNaslundBh has implemented this and others, allowing for specific approaches within namespaces as needed. It makes for a bit more redundant code, but allows for custom bits such as the …

Facade_Engine: Added Facade GeneralMaterialTakeoff methods

---

Serialiser_Engine/Convert/Json.cs

Closes #3109
The json text is trimmed before attempting to read it. See #3109 for a longer description.
This helps solving issues reading files with trailing/initial newlines/whitespaces, in particular for workflows that @pawelbaran highlighted in https://github.com/BHoM/File_Toolkit/issues/161 (if you go there, make sure you read its closing comment https://github.com/BHoM/File_Toolkit/issues/161#issuecomment-1640364782).
Attached in #3109.

Serialiser_Engine: `FromJson()` to Trim the text before attempting to read it 

---

Environment_Engine/Modify/Transform.cs

Closes #3123 
Input in the Transform.cs method was renamed from 'transform' to 'matrix'

Environment_Engine: Renaming input in the Transform.cs

---

Geometry_Engine/Query/Normal.cs

Geometry_Engine: Fix code comment spelling

---

Serialiser_Engine/Compute/Deserialise/Decimal.cs
Serialiser_Engine/Compute/Deserialise/Double.cs
Serialiser_Engine/Compute/Deserialise/String.cs

Closes #3130
- Overall, the serialisation of numbers was already relying on Mongo to do things correctly but there was a few cases where we were doing a 'manual' conversion to/from strings.
- I used `CultureInfo.InvariantCulture` instead of `en-GB` because it is [more robust to changes](https://learn.microsoft.com/en-us/dotnet/api/system.globalization.cultureinfo.invariantculture?view=net-7.0) 
-  Integers don't need formatting constraints as they don't change across cultures. I also checked other types like `Timespan` and `DateTime` and they don't need any modification as the first is invariant across cultures for default formatting and the second is represented as a long anyways.

Serialiser_Engine: Force invariant representation of number in serialisation

---

BHoM_Engine.sln
Settings_Engine/Compute/LoadSettings.cs
Settings_Engine/Compute/SaveSettings.cs
Settings_Engine/Modify/UpdateSettings.cs
Settings_Engine/Objects/Global.cs
Settings_Engine/Query/GetSettings.cs
Settings_Engine/Settings_Engine.csproj

Fixes #2709 
Available [here](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?newTargetListUrl=%2Fsites%2FBHoM%2F02%5FCurrent&viewpath=%2Fsites%2FBHoM%2F02%5FCurrent%2FForms%2FAllItems%2Easpx&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FBHoM%5FEngine%2FSettings%5FEngine&viewid=a5a93cba%2Dfcca%2D46cc%2Da31a%2D80b8d5cbfd7b) - thanks @peterjamesnugent for the nudge!
Please see [this comment](https://github.com/BHoM/BHoM_Engine/issues/2709#issuecomment-1665354605) for a brief overview of why a new project was added instead of utilising an existing project.
You may also be asking how does this link in with existing BHoM_UI methods on [saving](https://github.com/BHoM/BHoM_UI/blob/eba2e7d933178705d9082090ebe57934154e56c1/UI_Engine/Co …

Settings_Engine: Add central settings management

---

Facade_Engine/Compute/UValueOpeningsSAM.cs
Facade_Engine/Query/PsiValuesMatch.cs

Closes #3132
Added method to check that adjacent frame edges have matching PsiValues, as mismatching PsiValues indicates an error in frame properties that needs to be resolved before running the calc.
[Test file](https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/03_Alpha/BHoM/BHoM_Engine/Facade_Engine/Facade_Engine-OverallUFactorCalculationMethods_PsiBased.gh?csf=1&web=1&e=L7pxdh)

Facade_Engine: Added PsiValuesMatch method and OpeningsSAM check for matching

---

Environment_Engine/Create/Panel.cs
Geometry_Engine/Query/InternalEdges.cs

Environment_Engine: UX improvement on panel creation

---

Serialiser_Engine/Compute/Serialise/IBHoMObject.cs

Fixes #3017 
Test file available [here](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?newTargetListUrl=%2Fsites%2FBHoM%2F02%5FCurrent&viewpath=%2Fsites%2FBHoM%2F02%5FCurrent%2FForms%2FAllItems%2Easpx&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FBHoM%5FEngine%2FSerialiser%5FEngine%2F%233144%2DJSONSize&viewid=a5a93cba%2Dfcca%2D46cc%2Da31a%2D80b8d5cbfd7b).
Test file is very simple - serialise any object implementing `IBHoMObject` (should be most - I went with an Environment oM Panel) without providing a Name or other property implemented from `IBHoMObject` - see that the JSON doesn't contain the key value pair for those properties. Then provide values to those properties and see them get included.
I opted to go with storing …

Serialiser_Engine: Improve size of JSON by excluding empty IBHoMObject properties

---

Diffing_Engine/Compute/IDiffing.cs

Closes #3146
Standard test procedure for diffing.

Diffing_Engine: InputObjectsNullOrEmpty method bugfixed

---

.github/CODEOWNERS
Settings_Engine/Compute/LoadSettings.cs
Settings_Engine/Objects/Global.cs
Settings_Engine/Query/GetSettings.cs

Settings_Engine: Ensure settings are loaded when queried

---

Settings_Engine/Settings_Engine.csproj

Settings_Engine: Fix output path

---

Serialiser_Engine/Compute/Deserialise.cs
Serialiser_Engine/Compute/Deserialise/List.cs

Fixes #2674 
[Available here](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?newTargetListUrl=%2Fsites%2FBHoM%2F02%5FCurrent&viewpath=%2Fsites%2FBHoM%2F02%5FCurrent%2FForms%2FAllItems%2Easpx&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FBHoM%5FUI%2F%23469%2DExplodeCustomObject&viewid=a5a93cba%2Dfcca%2D46cc%2Da31a%2D80b8d5cbfd7b). The JSON used has come from @tg359 on the linked issue which this PR aims to resolve.
On alpha:
On this PR:
If testing using the provided test script **please make sure** you redrag the output of `FromJson` into the `Explode` component to get it to update. Alternatively, drop a new `Explode` component on the canvas and compare the cached one with the one from this PR.
E.G:

Serialiser_Engine: Deserialisation of nested lists

---

Environment_Engine/Modify/AddOpening.cs
Environment_Engine/Query/PanelsContainingPoint.cs

Environment_Engine: Update PanelsContainingPoint to also return the panels not containing the point

---

Geometry_Engine/Query/Angle.cs
Security_Engine/Compute/CameraFieldOfView.cs

Geometry Engine: Fix method name spelling

---

Geometry_Engine/Compute/ShortestPath.cs

Geometry_Engine: Add shortest path algorithm

---

Serialiser_Engine/Compute/Deserialise/List.cs

Fixes #3168 
Running tests used on the Versioning PR should be sufficient.

Serialiser_Engine: Protect against BSON having no values in list deserialisation

---

Environment_Engine/Compute/AssignSpaceTypeByPoint.cs

Environment_Engine: Removed string to enum method from AssignSpaceTypeByPoint

---

BHoM_Engine.sln
Ground_Engine/Ground_Engine.csproj

https://github.com/BHoM/BHoM/issues/1548
Closes #3173 
Add project for future development in 6.4 milestone
CI/CD
- Added Ground_Engine for future development planned in 6.4 milestone

Ground_Engine: Add project for ground related objects and associated engine methods

---

Environment_Engine/Modify/AddOpening.cs

Environmental_Engine: Removed AddOpening method

---

Environment_Engine/Compute/AssignSpaceTypeByPoint.cs

Environment_Engine: Update AssignSpaceTypeByPoint to provide output of spaces not assigned

---

Settings_Engine/Compute/LoadSettings.cs

Settings_Engine: Default to not loading all directories when loading settings

---

Environment_Engine/Compute/ExtrudeToVolume.cs

Environment_Engine: Control of duplicate control points before extruding to volume

---

BHoM_Engine/Compute/RunExtensionMethod.cs
BHoM_Engine/Compute/TryRunExtensionMethod.cs

Closes #3140
Write a simple `public static async` Engine method taking `BHoMObject` and try running it via script uploaded [here](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FBHoM%5FEngine%2FBHoM%5FEngine%2F%233191%2DRunExtensionMethodAsync&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4).
The methods added are to large extent a rewrite of `TryRunExtensionMethod`. However, `async` methods are not allowed to have `out` parameters, therefore I changed the method signature compared to synchronous flavour - happy to discuss if anyone has different/better ideas :+1:

BHoM_Engine: RunExtensionMethodAsync and TryRunExtensionMethodAsync added

---

Environment_Engine/Compute/ElementsInSpace.cs
Environment_Engine/Query/IsContaining.cs
Lighting_Engine/Query/Geometry.cs

Closes #3194 
Added ElementsInSpace for Element0D (1D/2D to follow as a latter PR). Also added IsContaining method for Element0D as well as faster method for detecting list of points' containment in a single space.
[Test Script](https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/BHoM_Engine/Environment_Engine/%233195-ElementInSpace?csf=1&web=1&e=uPbwro)
Test by checking that the method correctly identifies the elements in each space as per the different visualization output options in dark blue to the script's far right.

Environment_Engine: Added ElementsInSpace and dependant IsContaining methods / optimisations

---

Analytical_Engine/Compute/ElementsInRegion.cs
Analytical_Engine/Compute/ExtrudeToVolume.cs
Analytical_Engine/Query/IsContaining.cs
Environment_Engine/Environment_Engine.csproj
Environment_Engine/Query/IsContaining.cs
Geometry_Engine/Query/IsContaining.cs
Structure_Engine/Modify/SetAnalysisParameters.cs

Closes #3198 and #3199 
Methods for IsContaining were added to Geometry_Engine, and the ElementsInSpace method was moved to analytical. Both now work off polylines and regions respectively to allow for wider usage outside of the Environment_Engine.
[Test Script](https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/BHoM_Engine/Environment_Engine/%233199-IsContaining_Refactor?csf=1&web=1&e=o1EJ7L)

Environment_Engine: Refactor of IsContaining and ElementsInSpace methods to Geometry and Analytical namespaces as appropriate

---

Security_Engine/Compute/CameraFieldOfView.cs

Closes #3167
Added input description to make it compliant.

Security_Engine: Fixed documentation compliance

---

BHoM_Engine/Query/BHoMFolder.cs
Library_Engine/Query/IsPrototype.cs
Library_Engine/Query/Library.cs
Library_Engine/Query/LibrarySettings.cs
Reflection_Engine/Query/IsPrototype.cs
Versioning_Engine/Convert/ToNewVersion.cs

…clude the new method instead
Closes #3219
Replaced C:\ProgramData with methods using SpecialFolder construct.

BHoM_Engine: Replaced C:\ProgramData with SpecialFolder construct

---

Structure_Engine/Create/Loads/GeometricalLineLoad.cs

https://github.com/BHoM/BHoM/pull/1565
The class GeometricalLineLoad has been modified by adding an attribute, as discussed in https://github.com/BHoM/BHoM/issues/1564. this PR should introduce a new 'Create' method featuring a more intuitive naming and data structure for the input parameters.
Closes #3212 
https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/01_Issue/BHoM/BHoM_Engine/Structure_Engine/%233412-ChangesToGeometricalLineLoad/%233412ChangestoGeometricalLineLoad.gh?csf=1&web=1&e=GBLHkr

Structure_Engine: Added an additional Create Method for GeometricalLineLoad

---

Geometry_Engine/Query/IsVertical.cs
Structure_Engine/Compute/ShearAreaPolyline.cs
Structure_Engine/Query/IsVertical.cs
Structure_Engine/Query/ShearArea.cs

Fixes https://github.com/BHoM/BHoM/issues/1570

Geometry_Engine & Structure_Engine: Update documentation links

---

Geometry_Engine/Compute/BooleanDifference.cs
Geometry_Engine/Compute/BooleanIntersection.cs
Geometry_Engine/Compute/BooleanUnion.cs
Geometry_Engine/Compute/ClusterCollinear.cs
Geometry_Engine/Compute/DistributeOutlines.cs
Geometry_Engine/Compute/SortAlongCurve.cs
Geometry_Engine/Compute/SortCollinear.cs
Geometry_Engine/Compute/WetBlanketInterpretation.cs
Geometry_Engine/Convert/NurbsForm.cs
Geometry_Engine/Create/Plane.cs
Geometry_Engine/Modify/CollapseToPolyline.cs
Geometry_Engine/Modify/Mirror.cs
Geometry_Engine/Modify/Normalise.cs
Geometry_Engine/Modify/Project.cs
Geometry_Engine/Modify/ProjectAlong.cs
Geometry_Engine/Modify/SetGeometry.cs
Geometry_Engine/Modify/SortCurves.cs
Geometry_Engine/Modify/SplitAtPoints.cs
Geometry_Engine/Modify/Transform.cs
Geometry_Engine/Modify/Translate.cs
Geometry_Engine/Query/Area.cs
Geometry_Engine/Query/Bounds.cs
Geometry_Engine/Query/ExternalEdges.cs
Geometry_Engine/Query/InternalEdges.cs
Geometry_Engine/Query/IsClockwise.cs
Geometry_Engine/Query/IsCoplanar.cs

Closes #943
@FraserGreenroyd as discussed, it would be great if you could do a sanity check and onboard someone to dust off the test scripts that would confirm that I have not broken anything 🙈

Geometry_Engine: redundant calls to clone removed

---

Spatial_Engine/Query/Area.cs
Spatial_Engine/Versioning_71.json

Spatial_Engine: Remove unnecessary area methods

---

BHoM_Engine/Query/BHoMFolder.cs

Closes #3227 
Description attributes which referred to file paths now use `/` instead of `\\` as there are some json issues during beta deployment.

BHoM_Engine: Replace \\ in description attributes with /

---

Security_Engine/Compute/CameraFieldOfView.cs
Security_Engine/Modify/SimplifyCameraFieldOfView.cs
Security_Engine/Query/ViewCone.cs

Closes #3265
- arc creation bug fixed
- skip obstacles if camera device is inside (don't return null as before)

Security_Engine: Camera Field of View bug fix

---

Serialiser_Engine/Compute/Serialise.cs

Closes #3210 
after many hours of searching, finally found out that System.DBNull should serialise as null, so we should stop throwing errors when trying to serialise it.
[3210-DBNullCannotBeSerialised.zip](https://github.com/BHoM/BHoM_Engine/files/14142502/3210-DBNullCannotBeSerialised.zip)
Run through instructions made by myself in parent issue.

Serialiser_Engine: Stop throwing error on System.DBNull

---

Environment_Engine/Compute/OpeningsFromGlazingRatio.cs

Closes #3226
Added compute method, as described in the linked issue, the method calculates window sizes based on glazing ratio, for externally facing panels and creates openings.
[OpeningsByGlazingByRatioTestScript.zip](https://github.com/BHoM/BHoM_Engine/files/14163921/OpeningsByGlazingByRatioTestScript.zip)
Unzip, open in Rhino and check actual area is equal to expected area

Environment_Engine: Compute Openings from a list of panels and a glazing ratio

---

.ci/BHoMBot/Nuget/BHoM.Engine.nuspec

Fixes #3223 
This is based on [this Nuget report](https://www.nuget.org/packages/DeepCloner/0.10.2#supportedframeworks-body-tab) which highlights the `netstandard1.3` is a supported version for DeepCloner, and as such has a computed support package up to `net5.0` and `net6.0` crucially for the tools being prototyped across the BHoM community.
Ultimate proof will be in the nuget produced at the end of this sprint, hopefully will resolve the warning and error.

BHoM_Engine: Use NetStandard version of DeepCloner in Nugets rather than NetFramework

---

Geometry_Engine/Compute/FitLine.cs
Geometry_Engine/Compute/SingularValueDecomposition.cs

Closes #3278
General tests are available [here](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FBHoM%5FEngine%2FGeometry%5FEngine%2F%233275%2DSpeedUpBooleanOperations%2FFitLine%2Egh&parent=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FBHoM%5FEngine%2FGeometry%5FEngine%2F%233275%2DSpeedUpBooleanOperations)
Edge cases covered [here](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FIssue%2FBHoM%2FBHoM%5FEngine%2FGeometry%5FEngine%2F%233278%2DFitLineEdgeCase%2Egh&parent=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5F …

Geometry_Engine: Singular Value Decomposition implemented and applied to FitLine

---

Settings_Engine/Compute/SaveSettings.cs

Settings_Engine: Ensure SaveSettings also updates settings in memory

---

Geometry_Engine/Compute/SplitAtSelfIntersections.cs

Closes #3291
On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FBHoM%5FEngine%2FGeometry%5FEngine%2F%233292%2DSplitAtSelfIntersections&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4).

Geometry_Engine: split at self intersections method added

---

Geometry_Engine/Compute/FitPlane.cs

Closes #3287
See https://github.com/BHoM/BHoM_Engine/issues/3287

Geometry_Engine: Singular Value Decomposition algorithm applied to FitPlane method

---

Geometry_Engine/Compute/FitLine.cs

Closes #3288
On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FBHoM%5FEngine%2FGeometry%5FEngine%2F%233293%2DMakeUseOfToleranceInFitLine&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4)

Geometry_Engine: Tolerance introduced to the check of 2-dimensionality of the input point set

---

Settings_Engine/Compute/LoadSettings.cs
Settings_Engine/Compute/SaveSettings.cs

Settings_Engine: Add LoadSettings method for loading a single settings file

---

BHoM_Engine/Compute/RecordEvent.cs
BHoM_Engine/Compute/ThrowErrorsAsExceptions.cs

Fixes #3301
This will now make it so that `ThrowErrorsAsExceptions(true)` is turning on error throwing, as opposed to turning it off in the previous implementation.

BHoM_Engine: Fix ThrowError confusion for developers

---

Geometry_Engine/Query/IsCollinear.cs
Geometry_Engine/Query/IsCoplanar.cs

Closes #2423
Closes #3294
General test files for the methods changed in this PR uploaded to [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FBHoM%5FEngine%2FGeometry%5FEngine%2F%233298%2DGeometricalIsCoplanarNew&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4)
Test file for https://github.com/BHoM/BHoM_Engine/issues/2423 linked in the issue
This is the last PR in the current push in Geometry_Engine 🙈

Geometry_Engine: numerical solution in IsCoplanar replaced with geometrical one

---

Structure_Engine/Query/Description.cs
Structure_Engine/Query/MassPerArea.cs
Structure_Engine/Query/MaterialComposition.cs
Structure_Engine/Query/TotalThickness.cs
Structure_Engine/Query/VolumePerArea.cs

https://github.com/BHoM/BHoM/pull/1604
Adds required methods for new Cassette and BuiltUpRibbed properties:
- Descriptions
- VolumePerArea
- TotalThickness
- MaterialComposition
- MassPerArea
https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/BHoM/Structure_oM/%231604-AddCassetteAndBuiltUpRibProperties?csf=1&web=1&e=0MwLH7

Structure_Engine: Add required methods for Cassette and BuiltUpRibbed properties

---

Facade_Engine/Compute/UValueOpeningAW.cs
Facade_Engine/Compute/UValueSpandrelAW.cs

Closes #3315
Updated UValueOpeningAW and UValueSpandrelAW methods so that the Cavity UValue fragment is only applied to the center of the opening and not to the edges. 
New check has been added under section 5 of the SpandrelAWTestFile: https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/03_Alpha/BHoM/BHoM_Engine/Facade_Engine/BHoM%20PR%20Test%20Files?csf=1&web=1&e=pf2Sja

Updated AW methods to handle Cavity UValue

---

Data_Engine/Create/DomainTree.cs

Closes #3317 
The existing code does (min + min)/2 which I've rectified to (min + max)/2.
It's just a typo so hopefully someone who worked on Domain Tree before can approve right away 😉

Fix typo in DomainTree creation

---

Versioning_Engine/Convert/ToNewVersion.cs

https://github.com/BHoM/Versioning_Toolkit/pull/257
Closes #3331 
Changes the way the BHoMUpgraders are called from running via pipes to instead dynamically loading up the upgraders and directly calling them.
Initial testing shows that this can give a more than 10x speed increase for de-serialising objects requiring versioning, which can be critical for slightly larger serialised files. Increasingly important after changes like the one made in https://github.com/BHoM/BHoM/pull/1579 as that would significantly slow down the de-serialisation of and json file containing Bar objects. This could mean a difference for a file containing a few 100 bars of 10-30 seconds rather than say 3-5 minutes. Hence think this change is fairly critical.
For this PR I opted to make the events raised and calls …

Versioning_Engine: Add methodology for directly calling upgrades from main process rather than via pipes

---

Facade_Engine/Query/Geometry.cs

Facade_Engine: Geometry queries added for facade elements

---

BHoM_Engine/Create/Type/AllTypes.cs
BHoM_Engine/Create/Type/GenericType.cs
BHoM_Engine/Create/Type/Type.cs
Serialiser_Engine/Compute/Deserialise/Type.cs

BHoM_Engine: creation of type in case of multiple matching types fixed

---

Diffing_Engine/Compute/DiffOneByOne.cs
Diffing_Engine/Compute/DiffRevisions.cs
Diffing_Engine/Compute/DiffWithCustomIds.cs
Diffing_Engine/Query/DifferentProperties.cs
Diffing_Engine/Query/IsEqual.cs
Diffing_Engine/Query/ObjectDifferences.cs

Supports closing out https://github.com/BHoM/Test_Toolkit/issues/473
Very raw test file uploaded on [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FBHoM%5FEngine%2FDiffing%5FEngine%2F%233338%2DReplaceKellermanWithDiffing&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4), also diffing test project written by @alelom

Diffing_Engine: IsEqual method added

---

Structure_Engine/Query/Description.cs
Structure_Engine/Query/MassPerArea.cs
Structure_Engine/Query/MaterialComposition.cs
Structure_Engine/Query/TotalThickness.cs
Structure_Engine/Query/VolumePerArea.cs

https://github.com/BHoM/BHoM/pull/1615
Add all required methods for the added BuiltUpDoubleRibbed surface property.
https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/BHoM/Structure_oM/%231615-AddDoubleRibSurfaceProperty?csf=1&web=1&e=SjcnHu

Structure_Engine: Add method required for new BuiltUpDoubleRibbed surface property

---

BHoM_Engine/Modify/SortExtensionMethods.cs

Closes #3349
On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FBHoM%5FEngine%2FBHoM%5FEngine%2F%233350%2DSortExtensionMethodsBug)

BHoM_Engine: Modify.SortExtensionMethods fixed not to exclude methods targeting object 

---

Structure_Engine/Query/Geometry3D.cs

Closes #3347 
Geometry3D for pile and pad foundations added to Structure_Engine
https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/BHoM_Engine/Structure_Engine/%233347-add-geometry3d-for-piles-and-foundations/%233347-TypicalPileFoundation_Geometry3D_TestScript.gh?csf=1&web=1&e=44L3qr
- Added Geometry3D method for `Pile`, `PadFoundation` and `PileFoundation`;

Structure_Engine: Add Geometry3D method for Pile, PileCap and PileFoundation

---

Geometry_Engine/Compute/BooleanDifference.cs

Closes #3368
On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FBHoM%5FEngine%2FGeometry%5FEngine%2F%233369%2DNullReferenceInBooleanOperations).

Geometry_Engine: BooleanDifference secured against single-dimensional regions

---

BHoM_Engine/Create/Type/Type.cs
Serialiser_Engine/Compute/Deserialise/Type.cs

Serialiser_Engine: fix for MessageForDeleted to be picked up for properties of types that have multiple matching types

---

Ground_Engine/Create/Stratum.cs

Closes #3374
[#12-HandlingBlankGeology.gh](https://burohappold.sharepoint.com/:u:/s/BHoM/EbIE5Lj72U9Ji-kJwoL_4b8BjHLCZR59LHGGfUewAjsHag?e=lymhua) - this requires https://github.com/BHoM/AGS_Toolkit/pull/13 to be built
[#3374-VersionCheckForStratum](https://burohappold.sharepoint.com/:u:/s/BHoM/EQjpMFdKDcdFjR5RNVl1PB8BA_HwZGWGZT460p5HwG3O0w?e=UjHcyl) this requires the Versioning_Toolkit to be built
- Removed `blankGeology` from the `Create` method for `Stratum` and versioned the method;
Do not merge until the AGS_Toolkit PR is ready

Ground_Engine: Remove blankGeology from Stratum Create method

---

Ground_Engine/Compute/ConsolidateStrata.cs
Ground_Engine/Create/Borehole.cs
Ground_Engine/Create/ContaminantSample.cs

Closes #3271 
https://burohappold.sharepoint.com/:u:/s/BHoM/Ed88wg7PXYJEmTkOJcxKgkgBDI2rWoJoVNS3sJPTk4iwJw?e=24SqQ2
- Added `ConsolidateStrata` method that uses a property to combine sequential `Stratum`. For example, combining `Stratum` with the same `ObservedGeology` property.

Ground_Engine: Consolidate method for a Borehole

---

BHoM_Engine/Create/Type/EngineType.cs

Closes #3398 
Add additional check for assembly qualified name without version. Important for edgecase of same namespace and typename, from different assemblies for types serialized in an older major version. Only runs this additional step if more than one type is found.
Generally having this duplication should most likely be avoided, but as that has not been enforced, and was not an issue before #3389 which fixed other critical issues, but introduced this edge case problem, we should still attempt to make sure it works after that fix.
All query components should deserialise correctly:
[On Sharepoint](https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/03_Alpha/BuroHappoldEngineering/ModelLaundry_Toolkit/BuroHappold_BHoM_v3.3.beta_Structures_ML_BasicWorkFlow.gh?csf=1& …

BHoM_Engine: Additional check for assembly qualified type without version for Create EngineType

---

Analytical_Engine/Modify/SetOutlineElements1D.cs
Analytical_Engine/Query/Geometry.cs
Analytical_Engine/Query/IsOutlineQuad.cs
Analytical_Engine/Query/IsOutlineRectangular.cs
Analytical_Engine/Query/IsOutlineSquare.cs
Analytical_Engine/Query/IsOutlineTrianglular.cs
Analytical_Engine/Query/OutlineElements1D.cs
Geometry_Engine/Query/IsQuad.cs
Geometry_Engine/Query/IsRectangular.cs
Geometry_Engine/Query/IsSquare.cs
Geometry_Engine/Query/IsTriangular.cs
Structure_Engine/Create/Elements/PadFoundation.cs
Structure_Engine/Create/Elements/RetainingWall.cs
Structure_Engine/Create/Elements/Stem.cs
Structure_Engine/Modify/Flip.cs
Structure_Engine/Modify/Transform.cs
Structure_Engine/Query/Geometry.cs
Structure_Engine/Query/Geometry3D.cs
Structure_Engine/Query/IsNull.cs
Structure_Engine/Query/IsValid.cs
Structure_Engine/Query/MaterialComposition.cs
Structure_Engine/Query/OutlineElements1D.cs
Structure_Engine/Query/SolidVolume.cs

https://github.com/BHoM/BHoM/pull/1621
Closes [BHoM_Structure_oM](https://github.com/BHoM/BHoM/issues/1619#issue-2388764920)
See. 
https://github.com/BHoM/BHoM/pull/1621
Added required extension methods for implemented interfaces for new retaining wall classes.
- Added `Geometry()` method for `Stem` and `RetainingWall`
- Added `IsNull()` method for `Stem` and `RetainingWall`
- Added `SolidVolume()` method for `Stem` and `RetainingWall`
- Added `MaterialComposition()` method for `Stem` and `RetainingWall`
- Added `SetOutlineElements(List<IElement1D> outlineElements1D)` method for `Stem`
- Added `OutlineElemets1D()` method for `Stem`
- Added `Geometry3D()` method for `Stem` and `RetainingWall`
- Migrated `IsQuad`, `IsTriangular`, `IsRectangular`, `IsSquare` to the `Geometry` namespace so …

Structure_Engine: Add engine methods for retaining wall classes

---

.ci/code/Engine_Test/Verify/NullChecks.cs
.ci/code/Serialiser_Test/Serialiser_Test.csproj
.ci/code/Serialiser_Test/Verify/MethodsToFromJson.cs
.ci/code/Serialiser_Test/Verify/ObjectsToFromJson.cs
.ci/code/Serialiser_Test/Verify/TypesToFromJson.cs

Closes #3413 
Fixes references to the verification solution that broke after https://github.com/BHoM/Test_Toolkit/pull/474
Make sure compiles, and checks should be actually running on this PR.

Verifiaction: Add reference to Diffing_Engine to properly access the IsEqual method

---

Structure_Engine/Query/Geometry.cs

Closes #3411
https://burohappold.sharepoint.com/:u:/s/BHoM/EYbRjWNJQ3xDnepsnRTz1cQBaOOADL2wUdPn9FdauQ_ZOw?e=MqaFkK
- Updated `PileFoundation` `Geometry` method to use `IRegion` `Geometry` method for the `PileCap`.

Structure_Engine: Update `PileFoundation` Geometry method

---

Diffing_Engine/Query/DifferentProperties.cs
Diffing_Engine/Query/NumericalDifferenceInclusion.cs
Diffing_Engine/Query/ObjectDifferences.cs

Closes #3406
Rule out static properties from inclusion in comparison. (see issue for a bit more detail).
Minor cleanup of unused using's.
This reinstates the behaviour for testing prior to this:
https://github.com/BHoM/Test_Toolkit/pull/474
Check unit-tests. This should give a not insignificant improvement in speed for running through them, especially for tests containing System.Drawing.Color.
Also, @alelom , great if you can test this through your diffing tests.
Example run before this PR:
https://github.com/BHoM/BHoM_Engine/runs/29579805351

Diffing_Engine: Do not include static properties and fields in differences

---

Diffing_Engine/Query/IsEqual.cs

Closes #3427
DiffingTests_Prototypes

Diffing_Engine: Performance of IsEqual improved

---

.ci/unit-tests/BHoM_Engine_Tests.sln
.ci/unit-tests/Base_Engine_Tests/Base_Engine_Tests.csproj
.ci/unit-tests/Base_Engine_Tests/Compute/TryRunExtensionMethod.cs
.ci/unit-tests/Serialiser_Engine_Tests/Serialiser_Engine_Tests.csproj
.ci/unit-tests/Structure_Engine_Tests/Structure_Engine_Tests.csproj
.ci/unit-tests/TestHelper_Engine/Compute/ExtensionMethodToCallHelper.cs
.ci/unit-tests/TestHelper_Engine/TestHelper_Engine.csproj
BHoM_Engine/Query/ExtensionMethodHierarchy.cs
BHoM_Engine/Query/ExtensionMethodToCall.cs

Closes #3424
See the changes in the test project - review and run the newly added tests.

BHoM_Engine: TryRunExtensionMethod made more sensitive to inputs

---

Verification_Engine/Query/ReportMessage.cs

Closes #3432 
Added null checks to `ReportMessage` public method.

Verification_Engine - Report Message null checks added

---

Facade_Engine/Compute/UValueOpeningSAM.cs
Facade_Engine/Compute/UValuePanelAW.cs
Facade_Engine/Compute/UValuePanelSAM.cs
Facade_Engine/Compute/UValueSAM.cs

Closes #3434 
Added continuous UValue to SAM Method, and added parent methods to get collective UValues for any collection of FacadeElements.
[Test Script](https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/BHoM_Engine/Facade_Engine/%233434-OverallUValueMethods/%233434-CheckFacadeEngineUValueMethods.gh?csf=1&web=1&e=hU9YQe)

Facade_Engine: Added continuous UValue Calc to SAM method and Overarching UValue Methode for Collections of Elements

---

.ci/code/Serialiser_Test/Verify/ObjectsToFromJson.cs
Diffing_Engine/Diffing_Engine.csproj

Closes #3442
Add try-catch around IsEquals method to ensure it does not crash the whole test method, if exception is raised inside.
running check serialisaiton should show some known errors for objects

Add proper protection for IsEquals check for Serialisation

---

Structure_Engine/Create/Elements/RetainingWall.cs

Closes #3448 
https://burohappold.sharepoint.com/:f:/s/BHoM/Eht9vjlD7rRKqh_PiRUotbcBEKXpMpf_XTQv2fad052_jQ?e=IISoJB
- Added quantities to the `Create.RetainingWall()` method;
- Unitised the vector for the `Normal` used to create the `RetainingWall`;
This can be merged after the 8.0 release, just wanted to get it up while I had chance.

Structure_Engine: Unitise normal vector and add quantities to descriptions

---

BHoM_Engine/Objects/Global.cs

Closes #
See https://github.com/BHoM/Excel_Toolkit/pull/81
The PR adds a central assembly resolution mechanism that attempts to load the failing assembly from the BHoM folder in case of `AppDomain.CurrentDomain.AssemblyResolve` event being triggered as a result of BHoM method call.

BHoM_Engine: assembly resolution mechanism added to Global class

---

Diffing_Engine/Objects/CustomComparers/DataColumnComparer.cs
Diffing_Engine/Objects/CustomComparers/DataRowComparer.cs
Diffing_Engine/Objects/CustomComparers/DataTableComparer.cs
Diffing_Engine/Query/ObjectDifferences.cs

Closes #3455 
Fix IsEqual check for DataTables by inclusion of local copies of the custom comparers from Kellerman. See issue for more detail.
[On Sharpoint](https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/BHoM_Engine/Diffing_Engine/%233456-FixIsEqualOfDataTable?csf=1&web=1&e=whOnFz)
Serialisation check for the branch should not give warning about tables.

Diffing_Engine: Fix is equal of DataTable

---

Structure_Engine/Query/Geometry3D.cs

Solves issue and adds functionality to Geometry3D for panels. Previously, extrusion of panel was created along global Z-axis, meaning extruded geometry for walls was incorrect. Furthermore, extrusion distance was calculated from VolumePerArea() property,  meaning extruded dimension of i.e. Waffle Slab was incorrect.
To fix above, extrusion direction is changed from global Z vector to the normal vector of the panel surface and extrusion distance from VolumePerArea() to TotalThickness().
Closes #2852 
Check different thicknesses and different slab types. Control that results reasonable and like expected.
https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/BHoM_Engine/Structure_Engine/%232852-Geometry3DPanel-WrongThicknessAndNormalVector/%232852_Pa …

Structure_Engine: Geometry3D Panel Extrusion method using wrong thickness and normal vector

---

Versioning_Engine/Convert/ToNewVersion.cs

Closes #3470
Fixes issues with versioning in net framework environments not compatible with the upgrades dlls.
Tries with the direct call system, by extractign upgrade methods from the upgrader assemblies, and if it fails, sets the system to use the pipes instead.
Explicitly important to get versioning working for Rhino 8.
[Link to GH files that require versioning](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?csf=1&web=1&e=FuvTMj&CID=7ba6b874%2D3b0f%2D4112%2D8f61%2D6aa88e8a609c&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F03%5FAlpha%2FBuroHappoldEngineering%2FModelLaundry%5FToolkit)

Fallback on versioning to upgrade via pipes if direct calling crashes

---

Verification_Engine/Compute/CompareValues.cs
Verification_Engine/Compute/VerifyCondition.cs
Verification_Engine/Query/FormulaComponent.cs
Verification_Engine/Query/HasValue.cs

Helps closing https://github.com/BHoM/Revit_Toolkit/issues/1545
https://github.com/BHoM/BHoM_Engine/pull/3431
https://github.com/BHoM/BHoM_Engine/pull/3465
https://github.com/BHoM/BHoM_Engine/pull/3460
https://github.com/BHoM/BHoM_Engine/pull/3454

Verification_Engine: code tweaked to enable special treatment of Revit parameters

---

BHoM_Engine/Compute/ExtractAssembly.cs

Closes #3461 
Explude `IsSpecialName` from being added to the BHoMMethodList. This excludes Proeprty get and sets, from Properties in the engine. Also excludes Add and Remove methods for events.
This relates to these PRs:
https://github.com/BHoM/Versioning_Toolkit/pull/276
https://github.com/BHoM/Versioning_Toolkit/pull/281
Run the testscript on develop, internalise the results, then re-run on branch and check that the items removed make sense. @pawelbaran quite a few Revit types flagged, so good to make sure you are happy with the removal of them, and that they are not required to be in the BHoMMethod list for anything revit-related (assume not, but want to double check)
[Test script on sharepoint](https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request …

BHoM_Engine: Exclude SpecialName methods from BhoMMethodList

---

BHoM_Engine/Create/Type/EngineType.cs

Closes #3490
Locally apply the tweak from https://github.com/BHoM/Versioning_Toolkit/pull/297 to _C:\ProgramData\BHoM\Upgrades\BHoMUpgrader81\Upgrades.json_ and run versioning check - on `develop` it will throw errors, while after this fix it will be all good.

Base_Engine: Create.EngineType fixed to always return alphabetically first type in case of a few types matching the unqualified name

---

Verification_Engine/Compute/TryGetValueFromSource.cs

Closes #
Improve TryGetValueFromSource to work with specific cases of nested properties:
- if there's more than one property of the same name in the object, get one without indexing
- if property has no getter, check property from the base type

Verification_Engine: fixed TryGetValueFromSource for nested properties
