- docs/CODEOWNERS
Closes #783 
Added - new governance documents
> Create CODEOWNERS file in docs/

- Engine_Test/Program.cs
- Structure_Engine/Create/Bar.cs
- Structure_Engine/Create/MeshFace.cs
- Structure_Engine/Create/NewElement0D.cs
- Structure_Engine/Create/Node.cs
- Structure_Engine/Modify/SetGeometry.cs
- Structure_Engine/Objects/EqualityComparers/NodeDistanceComparer.cs
- Structure_Engine/Query/Centroid.cs
- Structure_Engine/Query/ControlPoints.cs
- Structure_Engine/Query/DeformedShape.cs
- Structure_Engine/Query/DistributedPoints.cs
- Structure_Engine/Query/Edges.cs
- Structure_Engine/Query/Extrude.cs
- Structure_Engine/Query/Geometry.cs
- Structure_Engine/Query/IsVertical.cs
- Structure_Engine/Query/Length.cs
- Structure_Engine/Query/Normal.cs
- Structure_Engine/Query/PlotForce.cs
- Structure_Engine/Query/PointGrid.cs
- Structure_Engine/Query/Position.cs
- Structure_Engine/Query/Tangent.cs
- Structure_Engine/Query/Visualize.cs
- Structure_Engine/Structure_Engine.csproj
https://github.com/BHoM/BHoM/pull/395
Closes #762 
See changelog below.
- All methods affected by `Node` class property change made in https://github.com/BHoM/BHoM/pull/395 updated. No change made to any of the method interfaces
- `Create.Node()` method added in the `Structure_Engine` accepting a `CoordinateSystem.Cartesian`
- `Query.Position()` method added in the `Structure_Engine` for the `Node` as a replacement for the changed property in the class
- `Query.Tangent()` Query method added in the `Structure_Engine` for `Bar` class
Changes made may include breaking changes for other toolkits. Please do not merge until dependant PR's are raised and approved
> Structure o m issue267 nodes to own a cartesian coordinate system

- Environment_Engine/Environment_Engine.csproj
- Environment_Engine/Query/UniqueConstructions.cs
- Environment_Engine/Query/UniqueMaterials..cs
Fixes #814 
Fixes #815 
Adds query methods for unique constructions and unique materials. Useful for XML, TAS, and EnergyPlus toolkits.
N/A
- Added Unique Construction Query
- Added Unique Material Query
> Environment engine issue814 815

- Environment_Engine/Query/UniqueConstructions.cs
Fixes #817 
Edge case in unique constructions
N/A
- Added edge case for unique constructions
> Fix opening construction uniques

- Environment_Engine/Create/Space.cs
- Environment_Engine/Environment_Engine.csproj
- Environment_Engine/Modify/AddAdjacentSpace.cs
- Environment_Engine/Modify/AddOpening.cs
- Environment_Engine/Query/BuildingElements.cs
Fixes #809 
Fixes #810 
Fixes #811 
Fixes #812 
Fixes #813 
Adds manipulation methods to aid the Visual Programming self-built model workflow to enable Rhino->BHoM->XML workflows for environmental people.
N/A - I have a dummy test model but thorough testing of this will come with the later Rhino->BHoM->XML workflows being generated.
- Added query methods to find `BuildingElements` by tilt, geometry, or a contained point
- Added modify method to add `Openings` to `BuildingElements`
- Added create method to create a `Space` with a name from a collection of `BuildingElements`
- Added modify method to add adjacent `Space` information to `BuildingElements`
> Environment Engine additions

- Environment_Engine/Query/ExposedToSun.cs
Fixes #821 
Exposed to Sun parameters resolved
See XML toolkit PR for full test files.
- Fixed ExposedToSun by string function
- Added ExposedToSun by BuildingElement function
> Resolve #821 - exposed to sun parameter

- Reflection_Engine/Query/Description.cs
- Reflection_Engine/Query/OutputDescription.cs
Closes #822
NullOrWhiteSpace checks for Description and Output, reverting to default text if nothing is provided.
> Reflection_Engine: Empty checks for attributes

- Environment_Engine/Compute/BuildSpace.cs
- Environment_Engine/Environment_Engine.csproj
- Environment_Engine/Modify/AddAdjacentSpace.cs
- Environment_Engine/Modify/AddOpening.cs
- Environment_Engine/Modify/Copy.cs
- Environment_Engine/Modify/MergeBuildingElements.cs
- Environment_Engine/Modify/SetBuildingElementType.cs
- Environment_Engine/Query/BuildingElements.cs
Fixes #826 
Fixes #829 
XML test files currently being taken
- Added methods to aid the Rhino to BHoM to XML workflow
- Fixed protection of build spaces if no connected spaces exist
> Environment_Engine - Rhino to BHoM to XML workflow

- Architecture_Engine/Create/Grid.cs
- Architecture_Engine/Create/Level.cs
- Environment_Engine/Create/Construction.cs
- Environment_Engine/Create/Material.cs
Fixes #800 
Fixes #836 
Adds name input parameters to creation methods of:
- Grid (Architecture)
- Level (Architecture)
- Construction (Environment)
- Material (Environment)
- Added Create Method with name parameter for `Grid` and `Level` in the `Architecture_Engine`
- Updated Create Method to include name parameter for `Construction` and `Material` in the `Environment_Engine`
> Environment_Engine/Architecture_Engine - add names to create methods

- BHoM_Engine/BHoM_Engine.csproj
- BHoM_Engine/Query/FilterByType.cs
- BHoM_Engine/Query/GroupByType.cs
Closes #772 
Adding filter and group by type methods
https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/BHoM_Engine/BHoM_Engine/Query?csf=1&e=E5D1Iy
- FilterByType and GroupByType methods added to the BHoM_Engine
> BHoM_Engine- Adding filter and group by type methods

- Environment_Engine/Environment_Engine.csproj
- Environment_Engine/Query/ElementID.cs
Fixes #798 
Existing TAS pull XML push test scripts
- Added query methods to obtain some elements by their ElementID
> Environment_Engine: Query element by IDs

- Geometry_Engine/Create/PlanarSurface.cs
- Geometry_Engine/Geometry_Engine.csproj
- Geometry_Engine/Query/Bounds.cs
- Geometry_Engine/Query/ControlPoints.cs
- Geometry_Engine/Query/ExternalEdges.cs
- Geometry_Engine/Query/InternalEdges.cs
- Geometry_Engine/Query/IsClosed.cs
- Geometry_Engine/Query/IsPlanar.cs
https://github.com/BHoM/BHoM/pull/427
Closes #853 
Adding the first methods to generate PlanarSurface objects as well as Bounds, Internal and external edges.
Test file will be provided when Rhino support is implemented.
Added:
- Adding support for PlanarSurface class
> Geometry engine issue853 add create methods for planar surface

- Structure_Engine/Query/Mass.cs
Closes #864 
Implements a Query method on the PanelPlanar objects. Method returns the mass of the PanelPlanar
https://burohappold.sharepoint.com/:u:/s/BHoM/Ed62DyBerYJBv4js_KaxC08BUGAwwLbHDIEyZvLBzbAdUw?e=Nb6TlZ
> Query Mass of PanelPlanar

- Common_Engine/Common_Engine.csproj
- Common_Engine/Query/IsSelfIntersecting.cs
- Common_Engine/Query/IsSelfIntersectiong.cs
- Geometry_Engine/Geometry_Engine.csproj
- Geometry_Engine/Query/CurveIntersections.cs
- Geometry_Engine/Query/CurvePlanarIntersections.cs
- Geometry_Engine/Query/IsSelfIntersecting.cs
- Geometry_Engine/Query/LineIntersections.cs
Closes #423 
Closes #856 
Closes #860 
Available [here](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F02_Current%2F12_Scripts%2F01_Test%20Scripts%2FBHoM_Engine%2FGeometry_Engine%2FCommonGeometry_Engine-Issues423%2C856%2C860-CurveIntersections%26IsSelfIntersecting) and LineIntersections.gh from [here](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F02_Current%2F12_Scripts%2F01_Test%20Scripts%2FBHoM_Engine%2FGeometry_Engine%2FQuery) - in the latter a few cases fail, this is related to the tolerance (different approach in GH and BHoM).
- small change in logics of `LineIntersection(Line, Line)` and `LineIntersections(List<Line>)` methods:
- the former now returns null when the lines are …
> CommonGeometry_Engine-Issues423,856,860-CurveIntersections&IsSelfIntersecting

- Library_Engine/Library_Engine.csproj
Closes #883
Project now builds if user account name and user folder names are different.
Should work for everyone to build
> Fixes #883 now uses appdata system variable

- Environment_Engine/Modify/SetInternalElements2D.cs
Closes #888 
Cannot think of one 😸 But needed for the operations on the IElements2D.
> Environment_Engine-Issue888-MakeSetInternalElements2DNotReturnNull

- Geometry_Engine/Query/IsContaining.cs
- Geometry_Engine/Query/ParameterAtPoint.cs
Closes #884 
Closes #885 
Test file is [here](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F02_Current%2F12_Scripts%2F01_Test%20Scripts%2FBHoM_Engine%2FGeometry_Engine%2FGeometry_Engine-Issues-884%2C885-ParameterAtPointAndIsContainingBugs).
Minor fixes to 2 methods.
> Geometry_Engine-Issues-884,885-ParameterAtPointAndIsContainingBugs

- Library_Engine/DataSets/Planning/Labels/IssueLabels.json
Closes #908 
Have updated the .json file to match the new key value pair label system we are using
> Library_Engine : Update Planning.Labels Datasets

- Humans_Engine/Create/Employee.cs
- Humans_Engine/Humans_Engine.csproj
Closes #910 
Addition of a single new Create method - creating `BH.oM.Humans.Employee` based on `Name` and `Email`
> Add simple Create Employee method

- Common_Engine/Common_Engine.csproj
- Common_Engine/Query/Length.cs
Closes #925 
Test file is [here](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F02_Current%2F12_Scripts%2F01_Test%20Scripts%2FBHoM_Engine%2FCommon_Engine%2FCommon_Engine-Issue925-AddLengthIElement1DMethod).
Added a Length(IElement1D) method.
It is a direct call to the existing, tested methods, so everything should be fine.
> Common_Engine-Issue925-AddLengthIElement1DMethod

- Environment_Engine/Query/Openings.cs
- Environment_Engine/Query/Panels.cs
Fixes #948 
Fixes #949 
[test file](https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/Revit_Toolkit/Revit_Toolkit-Issue288-GetInstanceTypeOpeningParameters?csf=1&e=KPJB9s)
- unique instances for panel
- unique instances for opening
> Environment engine issue948

- Environment_Engine/Environment_Engine.csproj
- Environment_Engine/Modify/SetConstruction.cs
- Environment_Engine/Modify/SetGeometry.cs
Fixes #952 
Current test script for changing constructions
- Added ability to change constructions on panels and openings based on type name
> Environment_Engine: set constructions

- Environment_Engine/Environment_Engine.csproj
- Environment_Engine/Query/ICurve.cs
- Environment_Engine/Query/Line.cs
- Environment_Engine/Query/Polyline.cs
- Environment_Engine/Query/Space.cs
Fixes #933 
Fixes #965 
Test file from #965 
- Changed some `Converts` to `Query` methods
- Fixed polyline representation of environment objects
> Environment_Engine - Polyline contains duplicate points fix

- Geometry_Engine/Geometry_Engine.csproj
- Geometry_Engine/Modify/CleanPolyline.cs
- Geometry_Engine/Query/Angle.cs
Fixes #983
Test model and GH script available [here](https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/BHoM_Engine/Geometry_Engine/Geometry_Engine-Issue983/983%20issue.zip?csf=1&e=LcWEwc)
- Added Modify method to clean unnecessary control points from a polyline
Only works for Closed Polylines - but have added reflection warnings and attributes as appropriate. See code changes for more info.
> Geometry_Engine: Clean Polyline

- Geometry_Engine/Compute/BooleanDifference.cs
- Geometry_Engine/Compute/BooleanIntersection.cs
- Geometry_Engine/Compute/BooleanUnion.cs
- Geometry_Engine/Compute/Join.cs
- Geometry_Engine/Geometry_Engine.csproj
- Geometry_Engine/Modify/Join.cs
- Geometry_Engine/Query/Normal.cs
- Structure_Engine/Query/Area.cs
- Structure_Engine/Query/Extrude.cs
- Structure_Engine/Query/PointGrid.cs
Closes #460 
Closes #902 
In #460 I did exactly what @epignatelli suggested in archived comments [here](https://burohappold.sharepoint.com/sites/BHoM/01_Master%20File/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F01_Master%20File%2F999_BHoM_GitHub_History_Archive). Now Join runs ok. Former method was adding more and more points to the list while recalculating.
In #902 it was caused by geometry engine method which did not cover polycurves consisting of 1 curve being circle or ellipse. Now it does.
#460:
[Here](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4&id=%2Fsites%2FBHoM%2F02_Current%2F12_Scripts%2F01_Test%20Scripts%2FBHoM_Engine%2FGeometry_Engine%2FGeometry_Engine-issue460-Join%20-ExponentialGrowthOfComputingT …
> Geometry_Engine: issue 460, Common_Engine: issue 902: Join (exponential growth of time), Normal (fails on circular panels)

- Geometry_Engine/Compute/FitPlane.cs
Closes #905 
The issue occurred only when points were almost (but not exactly) in the YZ plane.
As the method most often refers to `FitPlane(List<Point>)` I've changed only that one.
Now the method first checks if points are coplanar or colinear. If colinear returns null, if coplanar calculates normal of a fitting plane from a cross products of vectors made from points. If neither, it does what it did before. So the edge case is culled out.
[Here](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?newTargetListUrl=%2Fsites%2FBHoM%2F02_Current&viewpath=%2Fsites%2FBHoM%2F02_Current%2FForms%2FAllItems%2Easpx&id=%2Fsites%2FBHoM%2F02_Current%2F12_Scripts%2F01_Test%20Scripts%2FBHoM_Engine%2FGeometry_Engine%2FGeometry_Engine-Issue905-FitPlaneDoesNotAlwaysProduceCorrectPl …
> Geometry_EngineL: issue 905 - FitPlane doesn't always produce correct plane

- Structure_Engine/Modify/SetMaterial.cs
- Structure_Engine/Structure_Engine.csproj
Closes #903 
Adding SetMaterial Method to bars.
https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?csf=1&e=w3LMVj&cid=1cabe4cd-378f-4aaf-a05f-2e0b555da13d&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4&id=%2Fsites%2FBHoM%2F02_Current%2F12_Scripts%2F01_Test%20Scripts%2FBHoM_Engine%2FStructure_Engine%2FModify
> Structure engine issue903 set material to bar

- Environment_Engine/Query/ExposedToSun.cs
- Environment_Engine/Query/Panels.cs
Fixes #821 
Fixes #1012 
N/A
- Changed `ExposedToSun` to include additional exposed to sun `PanelType`.
> Fix #821 - additional exposed to sun panel types

- Environment_Engine/Create/Space.cs
- Environment_Engine/Environment_Engine.csproj
- Environment_Engine/Modify/AdjacentSpace.cs
- Environment_Engine/Modify/SetGeometry.cs
Fixes #1014 
Fixes #1015 
Current topologic testing
- Changed space creation method to include location point
- Added method for setting location point of a space
- Added method for setting connected spaces of a panel
> Environment_Engine: Panels and Space location

- Common_Engine/Create/Material.cs
- Common_Engine/Query/ShearModulus.cs
- Physical_Engine/Create/FramingElement.cs
- Physical_Engine/Create/FramingElementProperty.cs
- Physical_Engine/Create/Surface.cs
- Physical_Engine/Physical_Engine.csproj
- Physical_Engine/Query/Geometry.cs
- Structure_Engine/Convert/ToFramingElement.cs
- Structure_Engine/Create/ConstantFramingProperty.cs
- Structure_Engine/Create/FramingElement.cs
- Structure_Engine/Create/FramingElementProperty.cs
- Structure_Engine/Create/LoadingPanelProperty.cs
- Structure_Engine/Query/AnalyticalBars.cs
- Structure_Engine/Query/BarSectionTranformation.cs
- Structure_Engine/Query/Extrude.cs
- Structure_Engine/Query/Geometry.cs
- Structure_Engine/Query/IsVertical.cs
- Structure_Engine/Structure_Engine.csproj
https://github.com/BHoM/BHoM/pull/502
As the BHoM PR only deprecates the classes, not deleting them, this should build to master as well, but done in the same sprint
**ONLY DEPRECATING METHODS SO THINGS SHOULD BUILD, BUT PLEASE DO NOT MERGE UNTIL BHOM AND REVIT ARE READY AS WELL**
Closes #1000 (!!!)
Closes #999 
Closes #998 
Closes #997 
Closes #996 
- Deprecating methods pointing to deprecated classes/interfaces.
- Adding new methods corresponding to deprecated ones for FramingElements
- Adding missing methods for physical objects.
- Bug fix for Extrude method for vertical elements
- Fix for handling of orientation angles of non-linear elements for AnalyticalBars method
Unit testfiles will be updated/created when missing. Will get this done ASAP. Posting Pr for initial code review and …
> B ho m engine issue1000 physical cleanup

- Environment_Engine/Modify/AdjacentSpace.cs
Fixes #1029 
Current topologic work flows
- Added functions to change connected spaces of environment panels
> Environment_Engine: Add methods for changing adjacent space names

- Environment_Engine/Modify/AddFragment.cs
- Environment_Engine/Modify/Copy.cs
- Environment_Engine/Query/FindFragment.cs
- Environment_Engine/Query/ObjectsByFragment.cs
- Environment_Engine/Query/Openings.cs
- Environment_Engine/Query/Panels.cs
- Environment_Engine/Query/Spaces.cs
https://github.com/BHoM/BHoM/pull/508
Fixes #1035 
N/A
- Changed fragment namespace in line with BHoM changes
Do not merge until BHoM PR is ready
> Environment_Engine: Align to BHoM fragments

- Environment_Engine/Query/FloorGeometry.cs
Fixes #871 
Existing test files
- Fixed Floor Geometry method
> Environment_Engine: Floor geometry method fix

- Environment_Engine/Compute/BooleanIntersect.cs
- Environment_Engine/Convert/Edge.cs
- Environment_Engine/Environment_Engine.csproj
- Environment_Engine/Modify/AddOpening.cs
- Environment_Engine/Modify/SplitPanels.cs
- Environment_Engine/Query/Altitude.cs
- Environment_Engine/Query/AltitudeRange.cs
- Environment_Engine/Query/Azimuth.cs
- Environment_Engine/Query/Bounds.cs
- Environment_Engine/Query/ClosedShellGeometry.cs
- Environment_Engine/Query/FloorGeometry.cs
- Environment_Engine/Query/Height.cs
- Environment_Engine/Query/Inclination.cs
- Environment_Engine/Query/IsCoPlanar.cs
- Environment_Engine/Query/IsContaining.cs
- Environment_Engine/Query/IsIdentical.cs
- Environment_Engine/Query/Level.cs
- Environment_Engine/Query/NormalAwayFromSpace.cs
- Environment_Engine/Query/Orientation.cs
- Environment_Engine/Query/OutlineElements1D.cs
- Environment_Engine/Query/Panels.cs
- Environment_Engine/Query/Polyline.cs
- Environment_Engine/Query/SpaceCentre.cs
- Environment_Engine/Query/StoreyGeometry.cs
- Environment_Engine/Query/Tilt.cs
- Environment_Engine/Query/Vertices.cs
- Environment_Engine/Query/Width.cs
Fixes #1048 
Existing test scripts
- Changed `ToPolyline` to `Polyline`
> Environment_Engine: Fix ToPolyline as Polyline

- Geometry_Engine/Geometry_Engine.csproj
- Geometry_Engine/Query/PointInRegion.cs
Closes #1026 
Standard test file located [here](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FBHoM%5FEngine%2FGeometry%5FEngine%2FQuery).
- `Query.PointInRegion()` method added in the Geometry_Engine for `ICurve` interface
This PR does not modify same files as #1047 and #1051, all should merge seamlessly - if not, this one has lowest priority.
> Geometry_Engine-Issue1026-PointInRegion

- Reflection_Engine/Compute/RunExtentionMethod.cs
- Reflection_Engine/Modify/SortExtensionMethods.cs
- Reflection_Engine/Query/ExtentionMethods.cs
- Reflection_Engine/Reflection_Engine.csproj
Closes #1002 
- `ExtensionMethods()` now returns all methods callable by the type. Change from type == to type.IsAsignableFrom()
- Simple sorting of the methods to ensure that exact type matching is rated higher than interface/baseclass types.
- Storing of methods having multiple input parameters
This now makes in possible to reach methods written for an interface type via the `RunExtensionMethod()` schema.
Further improvements to be done:
- Make the sort method handle the closeness sorting in a more extensive way. Currently only sorts exact type higher than non-exact type. Should be done in a more hierarchical way based on inheritance chain.
Testfile trying to get out geometry for IFramingElement types
https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scr …
> Reflection engine issue1002 extension method to return interface methods

- Environment_Engine/Query/FloorGeometry.cs
Fixes #1044 
Existing test files
- Fixed Floor Geometry method tilt
> Environment_Engine: Floor geometry method fix issue#1044

- Structure_Engine/Modify/SetGeometry.cs
- Structure_Engine/Modify/SetOutlineElements1D.cs
Closes #1001 
Added 'true' to the GetShallowClone method when Edges are copied - for translate/other methods. 
https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/BHoM_Engine/Structure_Engine/Structure_Engine-Issue1001-Ensure%20new%20Guids%20on%20Edges?csf=1&e=Ktl5jm
> Structure_Engine: Ensure new GUIDs for Edges

- .github/ISSUE_TEMPLATE/api_changed.md
- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/compliance.md
- .github/ISSUE_TEMPLATE/documentation.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/ISSUE_TEMPLATE/question.md
- .github/ISSUE_TEMPLATE/test_script.md
Fixes #1069 
N/A
- Added IssueTemplates
> BHoM_Engine: Add issue templates

- Environment_Engine/Environment_Engine.csproj
- Environment_Engine/Modify/FixNormal.cs
Fixes #1067 
Test script provided on issue
- Added method to fix Panel normals for environmental analysis
> Environment_Engine: Add method to modify panels and fix their normals

- Environment_Engine/Environment_Engine.csproj
- Environment_Engine/Query/IsContaining.cs
- Environment_Engine/Query/PointInSpace.cs
Fixes #1046 
[Here](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?csf=1&e=QQohUR&cid=2a7f8848%2Dce0d%2D46e1%2Db127%2Dc5506f4bc760&RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FBHoM%5FEngine%2FEnvironment%5FEngine%2FEnvironment%5FEngine%2DIssue%2D1046%20Fix%20SpaceCentres&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4)
- Fixed Points In Space algorithm
Also removed an unused variable as caught by @adecler :wink:
> Environment_Engine: Points in space fix

- Environment_Engine/Query/FloorGeometry.cs
Fixes #1071 
Existing test script
- Fixed FloorGeometry query method to return accurate floor geometry.
> Environment_Engine: Resolve floor geometry issues

- Environment_Engine/Environment_Engine.csproj
- Environment_Engine/Modify/Remove.cs
- Environment_Engine/Modify/SetConstruction.cs
- Environment_Engine/Query/Panels.cs
Fixes #1075 
Rhino to BHoM workflow
- Added methods to modify collections of panels
> Environment_Engine: Adding lost methods

- Acoustic_Engine/Properties/AssemblyInfo.cs
- Analytical_Engine/Properties/AssemblyInfo.cs
- Architecture_Engine/Properties/AssemblyInfo.cs
- BHoM_Engine/Properties/AssemblyInfo.cs
- Common_Engine/Properties/AssemblyInfo.cs
- Data_Engine/Properties/AssemblyInfo.cs
- Engine_Test/Properties/AssemblyInfo.cs
- Environment_Engine/Properties/AssemblyInfo.cs
- Geometry_Engine/Properties/AssemblyInfo.cs
- Humans_Engine/Properties/AssemblyInfo.cs
- Library_Engine/Properties/AssemblyInfo.cs
- Physical_Engine/Properties/AssemblyInfo.cs
- Planning_Engine/Properties/AssemblyInfo.cs
- Reflection_Engine/Properties/AssemblyInfo.cs
- Results_Engine/Properties/AssemblyInfo.cs
- SVG_Engine/Properties/AssemblyInfo.cs
- Serialiser_Engine/Properties/AssemblyInfo.cs
- Speech_Engine/Properties/AssemblyInfo.cs
- Structure_Engine/Properties/AssemblyInfo.cs
- Testing_Engine/Properties/AssemblyInfo.cs
- Units_Engine/Properties/AssemblyInfo.cs
Fixes #1085 
N/A
- Changed AssemblyFileVersion to 2.3.0.0
> BHoM_Engine: Update assembly info

- Analytical_Engine/Properties/AssemblyInfo.cs
- Physical_Engine/Properties/AssemblyInfo.cs
Fixes #1090 
N/A
- Changed AssemblyVersion for Analytical and Physical oM from 1.0 to 2.0
> BHoM_Engine: Update assembly version

- Environment_Engine/Compute/Occupancy.cs
- Environment_Engine/Compute/PeopleGain.cs
- Environment_Engine/Environment_Engine.csproj
Closes #1101
Add People Gain and Occupancy Compute
N/A
- Add People Gain and Occupancy Compute
> EnvironmentEngine: Add People Gain and Occupancy Compute

- Environment_Engine/Compute/EquipmentGain.cs
- Environment_Engine/Compute/PlugGain.cs
- Environment_Engine/Create/Gains.cs
- Environment_Engine/Environment_Engine.csproj
Fixes #1109 
Add plug and equipment gain create and compute methods
> B env add plug gain

- Environment_Engine/Query/Polyline.cs
Fixes #1121 
N/A
- Fix crashing of Polyline query method if no edges exist
> Environment_Engine: Fix Polyline crash bug

- Environment_Engine/Compute/SolarPosition.cs
- Environment_Engine/Convert/Degrees.cs
- Environment_Engine/Environment_Engine.csproj
- Environment_Engine/Query/Azimuth.cs
- Environment_Engine/Query/SolarPosition.cs
Fixes #1129 
GH script [Here](https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/BHoM_Engine/Environment_Engine/Issue%201129%20-%20Sun%20Position%20calc/SunPositionTest.gh?csf=1&e=czwYMz)
> Environment_Engine: Add Solar Position Compute Methods

- Environment_Engine/Query/NormalAwayFromSpace.cs
- Geometry_Engine/Modify/CleanPolyline.cs
This PR increases accuracy from 99.0% to 99.8%
Fixes #1136 
Fixes #930 
[test file](https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/BHoM_Engine/Environment_Engine/Environment_Engine-Issue-930%20Normal_IsContaining/2019-08-15?csf=1&e=Ixmb7T)
Fix clean polyline
Fix NormalawayfromSpace
> Fix Clean Polyline and Fix Normal Away From Space

- Reflection_Engine/Convert/ToText.cs
Closes https://github.com/BHoM/BHoM_UI/issues/41
Adds parameter input names into the menu when browsing methods:
* Added parameter input names into the menu when browsing methods.
> Reflection_Engine: added methods' inputs parameters names in menu description

- Reflection_Engine/Convert/ToText.cs
> Reflection_Engine: shorten the params input description if longer than a max value

- Environment_Engine/Modify/SetPanelType.cs
Closes #1174 
fix naming in iteration
N/A
- Bug fix PanelsList
> Environment_Engine: Set Roof Panel Bug fix

- Environment_Engine/Query/NormalAwayFromSpace.cs
> Environment Engine Exposed tolerance parameter for NormalAwayFromSpace

- Environment_Engine/Query/NormalAwayFromSpace.cs
- Geometry_Engine/Query/Centroid.cs
- Geometry_Engine/Query/PointInRegion.cs
Closes #1190 
Add tolerance to NormalAwayFromSpace, Centeroid and PointInRegion
> Environment_Engine, Geometry_Engine - Add tolerance setting

- Common_Engine/Common_Engine.csproj
- Common_Engine/Modify/TranslateIElements.cs
Closes #1201 
https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/BHoM_Engine/Common_Engine/Issues/Issue1201-IElement%20Translate%20Methods?csf=1&e=aW8nTo 
- Raising further issues to add ITranslate interface to restrict application of the methods. 
- This is currently in common engine, @pawelbaran we should look at tidying the IElement methods up (classes are in Geometry but methods in Common)?
> Common_Engine: Add Translate Methods For IElements

- BHoM_Engine/Modify/AddFragment.cs
Fixes #1206 
[Here](https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/BHoM_Engine/BHoM_Engine/FragmentAdding.gh?csf=1&e=jh2UMC)
- Ensure that only one instance of a fragment can be added to an object at this time
> BHoM_Engine: fix fragment adding bug

- Structure_Engine/Query/CoordinateSystem.cs
Closes #1227 
Adds a method which creates a local coordinate system form a bars orientation
[The file](https://burohappold.sharepoint.com/:u:/s/BHoM/EWmOxYyfBThMl-41Qr1um5sBTtETP_fBLXOLLHcEgu95Ig?e=9gzLZR)
> Structure_Engine: #1227 CoordinateSystem from bar

- docs/CODEOWNERS
> Update code owners

- Geometry_Engine/Modify/RemoveLeastSignificantVertices.cs
- Geometry_Engine/Modify/RemoveShortSegments.cs
- Geometry_Engine/Query/Angle.cs
Closes #1207
https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/BHoM_Engine/Geometry_Engine/Modify/RemoveLeastSignificantVertices_2019-10-14.gh?csf=1&e=qIGlV4
https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/BHoM_Engine/Geometry_Engine/Modify/RemoveShortSegments_2019-10-14.gh?csf=1&e=ohKfnB
* Enabled RemoveShortSegments to handle open polylines.
* Enabler RemoveLeastSignificantVertices to handle open polylines.
> Geometry_Engine: Methods now work for open polylines

- Acoustic_Engine/Properties/AssemblyInfo.cs
- Analytical_Engine/Properties/AssemblyInfo.cs
- Architecture_Engine/Properties/AssemblyInfo.cs
- BHoM_Engine/Properties/AssemblyInfo.cs
- Common_Engine/Properties/AssemblyInfo.cs
- Data_Engine/Properties/AssemblyInfo.cs
- Diffing_Engine/Properties/AssemblyInfo.cs
- Engine_Test/Properties/AssemblyInfo.cs
- Environment_Engine/Properties/AssemblyInfo.cs
- Geometry_Engine/Properties/AssemblyInfo.cs
- Humans_Engine/Properties/AssemblyInfo.cs
- Library_Engine/Properties/AssemblyInfo.cs
- Physical_Engine/Properties/AssemblyInfo.cs
- Planning_Engine/Properties/AssemblyInfo.cs
- Reflection_Engine/Properties/AssemblyInfo.cs
- Results_Engine/Properties/AssemblyInfo.cs
- SVG_Engine/Properties/AssemblyInfo.cs
- Serialiser_Engine/Properties/AssemblyInfo.cs
- Speech_Engine/Properties/AssemblyInfo.cs
- Structure_Engine/Properties/AssemblyInfo.cs
- Testing_Engine/Properties/AssemblyInfo.cs
- Units_Engine/Properties/AssemblyInfo.cs
> Update assembly version

- Environment_Engine/Modify/AddOpening.cs
- Environment_Engine/Modify/AdjacentSpace.cs
- Environment_Engine/Modify/FixNormal.cs
- Environment_Engine/Modify/Remove.cs
- Environment_Engine/Modify/SetConstruction.cs
- Environment_Engine/Modify/SetPanelType.cs
- Environment_Engine/Modify/SplitPanels.cs
Closes #1265 
Added DeepClone to modify Methods 
Existing test files 
- Update modify methods to prevent upstream object changes
> Environment_Engine DeepClone modify Methods

- BHoM_Engine/Modify/AddFragment.cs
- BHoM_Engine/Query/FindFragment.cs
- Diffing_Engine/Modify/SetHashFragment.cs
- Diffing_Engine/Query/GetHash.cs
- Engine_Test/Diffing_Engine/Test01.cs
- Engine_Test/Program.cs
- Environment_Engine/Modify/Copy.cs
https://github.com/BHoM/BHoM/pull/574
Closes https://github.com/BHoM/BHoM_Engine/issues/1249
Align all Engine projects that needs alignment to the FragmentSet change.
- Align BHoM_Engine to FragmentSet change
- Align Diffing_Engine to FragmentSet change
- Align Engine_Test to FragmentSet change
- Align Environment_Engine to FragmentSet change
To be merged with:
- https://github.com/BHoM/TAS_Toolkit/pull/216
- https://github.com/BHoM/XML_Toolkit/pull/360
> Changes to align to FragmentSet

- Environment_Engine/Modify/SetConstruction.cs
N/A
Fixed #1271 
see attached in Issue #1271
> Environment_Engine Fix bug in Set Construction

- Structure_Engine/Create/Load.cs
Closes #1257 
Closes #1128 
Added constructors for ContourLoads and GeometricLineLoads, copied directly from Robot_Toolkit
> Structure_Engine: Add Create methods for ContourLoads and GeoemetricalLineLoad

- Environment_Engine/Create/BuildingAnalyticalFragment.cs
- Environment_Engine/Create/BuildingContextFragment.cs
- Environment_Engine/Create/BuildingResultFragment.cs
- Environment_Engine/Create/CoefficientFragment.cs
- Environment_Engine/Create/EnvironmentConstructionFragment.cs
- Environment_Engine/Create/LightReflectanceFragment.cs
- Environment_Engine/Create/LightTransmittanceFragment.cs
- Environment_Engine/Create/OriginContextFragment.cs
- Environment_Engine/Create/PanelAnalyticalFragment.cs
- Environment_Engine/Create/PanelContextFragment.cs
- Environment_Engine/Create/RadiationFragment.cs
- Environment_Engine/Create/SpaceAnalyticalFragment.cs
- Environment_Engine/Create/SpaceContextFragment.cs
https://github.com/BHoM/BHoM/pull/592
Fixes #1280 
N/A
- Deprecate existing fragment create methods to remove inherited properties
> Environment_Engine: Update fragments

- Data_Engine/Create/Dataset.cs
- Data_Engine/Data_Engine.csproj
- Library_Engine/Create/Dataset.cs
https://github.com/BHoM/BHoM/pull/582
Closes #1254 
Adding Create method for Dataset
https://burohappold.sharepoint.com/:u:/s/BHoM/Ed1f1PCNKiVHtDVxMO-9DlYB0-7GDljl63jROVs9sl_HYA?e=uHJ99c
> Data_Engine: Adding create method for Dataset

- BHoM_Engine.sln
- Serialiser_Engine/Compute/Compute.cs
- Serialiser_Engine/Convert/Bson.cs
- Serialiser_Engine/Objects/BsonSerializers/DeprecatedSerializer.cs
- Serialiser_Engine/Objects/BsonSerializers/ObjectSerializer.cs
- Serialiser_Engine/Objects/Config.cs
- Serialiser_Engine/Objects/IDeprecated.cs
- Serialiser_Engine/Objects/MemberMapConventions/GenericDiscriminatorConvention.cs
- Serialiser_Engine/Serialiser_Engine.csproj
- Versioning_Engine/Convert/ToNewVersion.cs
- Versioning_Engine/Properties/AssemblyInfo.cs
- Versioning_Engine/Versioning_Engine.csproj
- Versioning_Engine/packages.config
https://github.com/BHoM/Versioning_Toolkit/pull/2
Closes #1267 
See the PR in the Versioning_Toolkit for more details
Recreating with proper branch name
Edit: This doesn't really depends on the Version toolkit per se anymore (no direct reference) but you will need it for testing.
> Leverage the versioning engine for deserialisation of objects

- Serialiser_Engine/Objects/BsonSerializers/DeprecatedSerializer.cs
- Serialiser_Engine/Objects/BsonSerializers/ObjectSerializer.cs
- Serialiser_Engine/Objects/MemberMapConventions/GenericDiscriminatorConvention.cs
- Versioning_Engine/Convert/ToNewVersion.cs
https://github.com/BHoM/Versioning_Toolkit/pull/4
Closes #1290
See https://github.com/BHoM/Versioning_Toolkit/pull/4 for more details
This PR provide the necesseray interaction with the new version of the versioning engine and greatly simplify the whole process (code deletion is back!!)
> Serialiser_Engine: Improve on the handling of deprecated and inexistent classes

- Geometry_Engine/Modify/CleanPolyline.cs
- Geometry_Engine/Modify/RemoveLeastSignificantVertices.cs
> Geometry_Engine: Make use of parameters in CleanPolyline

- .ci/CloneTest.ps1
- .ci/check-all-depandants.yml
- .ci/check-core.yml
- .ci/check-installer.yml
- .ci/run-compliance-tests.yml
- .ci/testSettings.runsettings
- Acoustic_Engine/Acoustic_Engine.csproj
- Diffing_Engine/Diffing_Engine.csproj
- Diffing_Engine/packages.config
- Environment_Engine/Environment_Engine.csproj
- Structure_Engine/Structure_Engine.csproj
- core.txt
- dependencies.txt
> BHoM_Engine: Set up CI

- Reflection_Engine/Query/EnumValues.cs
- Reflection_Engine/Reflection_Engine.csproj
Closes #1325
Uploaded to [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?viewid=a5a93cba%2Dfcca%2D46cc%2Da31a%2D80b8d5cbfd7b&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FBHoM%5FEngine%2FReflection%5FEngine%2FReflection%5FEngine%2DIssue1325%2DAddEnumValuesMethod).
- `EnumValues()` method has been added in `BH.Engine.Reflection.Query`
> Reflection_Engine: Add EnumValues method

- Structure_Engine/Create/MeshResult.cs
- Structure_Engine/Query/DeformedShape.cs
https://github.com/BHoM/BHoM/pull/611
Closes #1321 
Update references to MeshResults to new name MeshResult
> Structure_Engine: Update names of MeshResults

- Geometry_Engine/Query/Angle.cs
Closes #1353 
Updated output description for Angle from three points method to say radians instead of degrees.
> Geometry_Engine updated output documentation

- Structure_Engine/Create/MaterialFragment.cs
Closes #1213 
Fixes description for Shear Modulus `G` 
To be tested by inspection
- Fixes description for Shear Modulus `G`
> Structure_Engine: Correct description for Shear Modulus in Timber Constructor

- Structure_Engine/Query/Geometry.cs
> Structure_Engine: the fallback `public static IGeometry Geometry(this object section)` is now private 

- Acoustic_Engine/Properties/AssemblyInfo.cs
- Analytical_Engine/Properties/AssemblyInfo.cs
- Architecture_Engine/Properties/AssemblyInfo.cs
- BHoM_Engine/Properties/AssemblyInfo.cs
- Common_Engine/Properties/AssemblyInfo.cs
- Data_Engine/Properties/AssemblyInfo.cs
- Diffing_Engine/Properties/AssemblyInfo.cs
- Environment_Engine/Properties/AssemblyInfo.cs
- Geometry_Engine/Properties/AssemblyInfo.cs
- Graphics_Engine/Properties/AssemblyInfo.cs
- Humans_Engine/Properties/AssemblyInfo.cs
- Library_Engine/Properties/AssemblyInfo.cs
- MEP_Engine/Properties/AssemblyInfo.cs
- Physical_Engine/Properties/AssemblyInfo.cs
- Planning_Engine/Properties/AssemblyInfo.cs
- Reflection_Engine/Properties/AssemblyInfo.cs
- Results_Engine/Properties/AssemblyInfo.cs
- Serialiser_Engine/Properties/AssemblyInfo.cs
- Speech_Engine/Properties/AssemblyInfo.cs
- Structure_Engine/Properties/AssemblyInfo.cs
- Units_Engine/Properties/AssemblyInfo.cs
- Versioning_Engine/Properties/AssemblyInfo.cs
> BHoM_Engine: Update assembly file version

- Data_Engine/Compute/Series.cs
- Data_Engine/Data_Engine.csproj
Closes #1396
This is a pretty straightforward one but necessary to provide a matching method to the `Series` component in Grasshopper (in the context of node2code).
To test this, just make sure that this method output the same result as the `Series` component in Grasshopper.
> Data_Engine - Issue 1396 - Add method to create numerical series

- Geometry_Engine/Create/ShapeProfileCurves.cs
Closes #1399
Forgot to commit last white space change before merging old branch.
> Geometry_Engine: added white space for compliance 

- Diffing_Engine/Diffing_Engine.csproj
> Diffing_Engine: Removed unused references

- Geometry_Engine/Geometry_Engine.csproj
- Geometry_Engine/Modify/RoundPoint.cs
> Geometry_Engine: Add round point method

- Environment_Engine/Environment_Engine.csproj
- Environment_Engine/Modify/OffsetOpenings.cs
> Environment_Engine: Add ability to Offset Openings

- BHoM_Engine/BHoM_Engine.csproj
- BHoM_Engine/Objects/EqualityComparers/TypeComparer.cs
- Diffing_Engine/Comparers/HashComparer.cs
- Diffing_Engine/Compute/Diffing.cs
- Diffing_Engine/Compute/HashComparing.cs
- Diffing_Engine/Compute/SHA256Hash.cs
- Diffing_Engine/Create/DiffConfig.cs
- Diffing_Engine/Diffing_Engine.csproj
- Reflection_Engine/Compute/RecordEvent.cs
- Reflection_Engine/Query/DistinctProperties.cs
Closes #1374
- Added a `HashComparer` that can be used by the Adapter if no other Comparer is found.
- Tidy up of the Diffing_Engine as prompted by the addition of the HashComparer.
Replacing https://github.com/BHoM/BHoM_Engine/pull/1371
> Aligning with changes in BHoMAdapter Refactoring Level 04

- Environment_Engine/Query/UniqueConstructions.cs
> Environment_Engine: Add flag for unique construction names

- .ci/CloneTest.ps1
- .ci/check-installer.yml
- .ci/run-compliance-tests.yml
> Update CI files

- Reflection_Engine/Query/UnderlyingType.cs
Minor fix required for https://github.com/BHoM/BHoM_UI/pull/186 to work properly in all cases
It should be pretty trivial to see that this doesn't break anything and fix a potential crash by simple code inspection.
> Reflection_Engine: Add null check for UnderlyingType method

- Serialiser_Engine/Convert/Json.cs
Closes #1435 
-Supports json serialization where json is nested with header or other data
[200127_HTTPTest-Adapter.zip](https://github.com/BHoM/BHoM_Engine/files/4124570/200127_HTTPTest-Adapter.zip)
> Serialiser_Engine: Nested objects with headers supported using iterative approach

- Environment_Engine/Modify/Copy.cs
Fixes #1442 
See @BingWangUS script
> Environment_Engine: Fix bug in copy panel for null fragment set

- .ci/CloneTest.ps1
This should resolve the issue being experienced with some PR checks not building due to disparities between BHoM and BHoM_Engine.
> Update CI checking file

- .ci/CloneTest.ps1
> BHoM_Engine: Update CI file

- Data_Engine/Create/GraphLink.cs
- Data_Engine/Create/GraphNode.cs
https://github.com/BHoM/BHoM/pull/664
Fixes #1448
Optional parameters added to create methods for the GraphNode and the GraphLink so a ``Dictionary<string,object>`` can be passed in.
> Data_Engine: Add attribute dictionary to GraphNode and GraphLink

- Reflection_Engine/Query/Description.cs
- Reflection_Engine/Query/OutputAttributes.cs
- Reflection_Engine/Query/OutputDescription.cs
https://github.com/BHoM/BHoM/pull/684
Closes #1453 
- Moving quantity description to description for Types
- Adding ability to retrieve quantity attributes from input and output attributes to be used to describe the types
- Modifying the MultiOutput attribute to also consider type description as well as Quantity attributes
This will let us do the following:
```
[Input("loadcase", "Loadcase for the load to be applied to")]
[Input("objects", "The collection fo Bars to apply the load to")]
[Input("distFromA", "Distance between the start node of the bar and the load position", typeof(Length))]
[Input("force", "Point force to be applied to the bars as a vector controling direction and magnitude. The load requires either a force and/or a moment to be valid", typeof(Force))]
[Input("moment", …
```
> Reflection_Engine: Add Quantity descriptions for Inputs and Outputs

- .ci/CloneTest.ps1
This should resolve the issue still presented by https://github.com/BHoM/BHoM_Engine/pull/1451
> BHoM_Engine: Update CI for upstream breaking changes

- .ci/BuildTest.ps1
- .ci/CloneTest.ps1
- .ci/run-compliance-tests.yml
Continuing to try and resolve issues found in this PR: https://github.com/BHoM/BHoM_Engine/pull/1451
This PR will be running some tests - please observe labels and do not merge until labels are removed
> Update CI files to protect Test Toolkit

- Data_Engine/Create/LogicalAndRequest.cs
- Data_Engine/Create/LogicalOrRequest.cs
- Data_Engine/Data_Engine.csproj
[BHoM #688](https://github.com/BHoM/BHoM/pull/688)
Closes #1459
Not added as the code is self-explanatory.
> Data_Engine: Create methods for LogicalAnd and LogicalOr requests added

- .github/CODEOWNERS
- BHoM_Engine.sln
- Spatial_Engine/Properties/AssemblyInfo.cs
- Spatial_Engine/Spatial_Engine.csproj
Closes #1469 
Creation of new Spatial_Engine in advance of migrate of the IElementXD methods from Common_Engine as discussed.
> Creation of new Spatial_Engine

- Reflection_Engine/Query/Description.cs
https://github.com/BHoM/BHoM/pull/695
Closes #1462 
Makes use of new InputFromProperty attribute to grab descriptions from the oM. Lets you do for example:
```
[InputFromProperty("property","SectionProperty")]
[InputFromProperty("orientationAngle")]
[InputFromProperty("release")]
[InputFromProperty("feaType","FEAType")]
public static Bar Bar(Line line, ISectionProperty property = null, double orientationAngle = 0, BarRelease release = null, BarFEAType feaType = BarFEAType.Flexural, string name = "")
{          
return Bar(Node(line.Start), Node(line.End), property, orientationAngle, release, feaType, name);
}
```
Add a Create.Bar component accepting a Line as its first input. OrientationAngle and Release should have descriptions grabbed from the bar class.
> Reflection_Engine: Extracting descriptions of properties for Create methods

- Data_Engine/Data_Engine.csproj
- Data_Engine/Query/Linq/FilterBy.cs
- Data_Engine/Query/Linq/OrderBy.cs
Closes #1305 
https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/BHoM_Engine/Data_Engine/Issues?csf=1&e=fk4xir
**Additional Test script by @FraserGreenroyd **
[Here is a GH script and a JSON file of test data to pull from for the script to work with](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?csf=1&e=fk4xir&cid=4eedc797%2D06e0%2D4cc5%2Daec9%2D39a8d560956c&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4&viewid=a5a93cba%2Dfcca%2D46cc%2Da31a%2D80b8d5cbfd7b&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FBHoM%5FEngine%2FData%5FEngine%2FIssues%2F1305%20%2D%20Linq)
- Add OrderBy and FilterBy methods to wrap Linq OrderBy and Where respectively.
> Data_Engine: Enable advanced sorting and filtering BHoM object lists, by wrapping 'Linq' methods

- BHoM_Engine/Create/RandomObject.cs
- BHoM_Engine/Modify/AddFragment.cs
- BHoM_Engine/Modify/RemoveFragment.cs
- BHoM_Engine/Query/FindFragment.cs
- BHoM_Engine/Query/GetAllFragments.cs
- Environment_Engine/Modify/AddFragment.cs
https://github.com/BHoM/BHoM/pull/711
Fixes #1494
> BHoM_Engine: Rename IBHoMFragment -> IFragment

- Environment_Engine/Modify/AddFragment.cs
> Environment_Engine: Deprecate Add Fragment method

- MEP_Engine/Create/AirHandlingUnit.cs
> MEP_Engine: Compliance Update

- Geometry_Engine/Modify/Offset.cs
Fixes #1514 
N/A
The issue will be resolved by the changes made. Outstanding issues will be raised in 3.2 compliance reports as discussed.
Geometry_Engine has some fundamental compliance issues, with sub-classes and incorrect classes which will need addressing as part of a 3.2 discussion as there may be script breakages as a result.
Therefore only the ticked items on the issue are resolved here, but the issue is valid to close with this PR ready for a 3.2 compliance report.
> Geometry_Engine: Compliance Update

- Data_Engine/Data_Engine.csproj
- Data_Engine/Query/FirstValueAbove.cs
- Data_Engine/Query/FirstValueAt.cs
- Data_Engine/Query/ValuesAbove.cs
- Data_Engine/Query/ValuesAt.cs
Fixes #1510 
N/A
The issue will be resolved by the changes made. Outstanding issues will be raised in 3.2 compliance reports as discussed.
Data_Engine has some fundamental compliance issues, with sub-classes and incorrect classes which will need addressing as part of a 3.2 discussion as there may be script breakages as a result.
> Data_Engine: Compliance Update

- Library_Engine/Library_Engine.csproj
- Library_Engine/Query/AllLibraryPathNames.cs
- Library_Engine/Query/Datasets.cs
- Library_Engine/Query/Libraries.cs
- Library_Engine/Query/LibraryNames.cs
- Library_Engine/Query/LibraryTree.cs
- Library_Engine/Query/Names.cs
- Library_Engine/Query/PartialMatch.cs
- Library_Engine/Query/RefreshLibraries.cs
- Library_Engine/Query/StringMatch.cs
> Library_Engine: Compliance updates

- Environment_Engine/Query/CullDuplicateLines.cs
Issue was found briefly during a code review and training session. Fixing because it'll annoy me to leave it.
> Environment_Engine: Fix scope

- Environment_Engine/Environment_Engine.csproj
- Environment_Engine/Query/FrameFactor.cs
> Environment_Engine: Add query for FrameFactor

- Environment_Engine/Compute/ExtrudeToVolume.cs
- Environment_Engine/Environment_Engine.csproj
> Environment_Engine: Add compute to extrude Architecture Rooms into closed volumes

- Environment_Engine/Create/Space.cs
[BHoM/BHoM#740](https://github.com/BHoM/BHoM/pull/740)
Resolves alignment to oM changes
> Environment_Engine: Align to oM changes

- Library_Engine/Convert/ToText.cs
- Library_Engine/Library_Engine.csproj
- Library_Engine/Query/GeneralDisclaimer.cs
- Library_Engine/Query/SourceAndDisclaimer.cs
Closes #1562 
Adding methods for turning a Source into text and extracting source text from a library
https://burohappold.sharepoint.com/:f:/s/BHoM/Em1iX6AW4K5Og6hei-bFqnABCUktj1_Jx2I-hEu-mnAojg?e=b1414F
> Library_Engine: Adding methods for extracting source as text from a library

- .ci/check-all-depandants.yml
- .ci/check-core.yml
- .ci/check-installer.yml
- .ci/run-compliance-tests.yml
> BHoM_Engine: Update CI files

- Environment_Engine/Compute/MapToLevel.cs
- Environment_Engine/Environment_Engine.csproj
Fixes #1573 
Being uploaded but have been shared among reviewers
> Environment_Engine: Add compute method for mapping rooms to levels

- BHoM_Engine.sln
- Matter_Engine/Compute/AggregateMaterialComposition.cs
- Matter_Engine/Create/MaterialComposition.cs
- Matter_Engine/Matter_Engine.csproj
- Matter_Engine/Properties/AssemblyInfo.cs
- Matter_Engine/Query/Density.cs
- Matter_Engine/Query/Mass.cs
- Matter_Engine/Query/MaterialComposition.cs
- Matter_Engine/Query/SolidVolume.cs
- Physical_Engine/Query/AverageProfileArea.cs
- Physical_Engine/Query/MaterialComposition.cs
- Physical_Engine/Query/SolidVolume.cs
- Structure_Engine/Query/MaterialComposition.cs
- Structure_Engine/Query/SolidVolume.cs
- Structure_Engine/Structure_Engine.csproj
This is a Re-creation of #1550 
https://github.com/BHoM/BHoM/issues/729
Base functionality for:
- Physical `ISurface`
- Physical `IFramingElement`
- Structure `Bar`
which includes:
- `MaterialComposition()`
- `SolidVolume()`
which enables the methods:
- `Mass()`
It also creates the create methods for the type `MaterialComposition` which includes:
- single `Material` to `MaterialComposition`
- a collection of `Material` and their ratios to `MaterialComposition`
- a collection of `MaterialComposition` and their ratios to `MaterialComposition`
- a collection of `IElementM` to their collective `MaterialComposition`
https://burohappold.sharepoint.com/:u:/s/BHoM/EQuOFTEei95BkUaR0_o4RZIBdnHDyw2V9PBmh0VdF8ZE_A?e=rLG4OV
- Added `SolidVolume()` & `MaterialComposition()` for `IFramingElement`
- …
> Matter_Engine: Creation of the Matter Engine and subsequent methods

- Environment_Engine/Compute/ExtrudeToVolume.cs
Closes #1599 
Add 5th control point
> Environment_Engine: Fix wall edges of ExtrudeToVolume

- Environment_Engine/Compute/MapToLevel.cs
Closes #1593 
Sort Room in outputs
Sort LevelInUsed in outputs
Remove unused variable
> Environment_Engine: Sort Outputs based on Level in MapToLevel

- Environment_Engine/Compute/ExtrudeToVolume.cs
Fixes #1604 
Sent to @rboulton-BH
> Environment_Engine: ExtrudeToVolume for polyline

- Spatial_Engine/Create/NewElement0D.cs
- Spatial_Engine/Create/NewElement1D.cs
- Spatial_Engine/Create/NewInternalElement2D.cs
- Spatial_Engine/Modify/SetElements0D.cs
- Spatial_Engine/Modify/SetGeometry.cs
- Spatial_Engine/Modify/SetInternalElements2D.cs
- Spatial_Engine/Modify/SetOutlineElements1D.cs
- Spatial_Engine/Modify/Translate.cs
- Spatial_Engine/Query/Area.cs
- Spatial_Engine/Query/Bounds.cs
- Spatial_Engine/Query/Centroid.cs
- Spatial_Engine/Query/ControlPoints.cs
- Spatial_Engine/Query/ElementCurves.cs
- Spatial_Engine/Query/ElementVertices.cs
- Spatial_Engine/Query/Elements0D.cs
- Spatial_Engine/Query/Geometry.cs
- Spatial_Engine/Query/InternalElements2D.cs
- Spatial_Engine/Query/InternalOutlineCurves.cs
- Spatial_Engine/Query/IsSelfIntersecting.cs
- Spatial_Engine/Query/Length.cs
- Spatial_Engine/Query/Normal.cs
- Spatial_Engine/Query/OutlineCurve.cs
- Spatial_Engine/Query/OutlineElements1D.cs
Closes #1595
Adds descriptions for all Spatial_Engine methods
Not needed
> Spatial_Engine:  Descriptions for Methods 

- Library_Engine/Query/SourceAndDisclaimer.cs
Closes #1606 
As title says
no need
> Library_Engine: Fix type in SourceAndDisclaimer when no source is available

- Environment_Engine/Environment_Engine.csproj
- Environment_Engine/Query/FloorHeights.cs
Fixes #1615 
@BingWangUS to provide
> Environment_Engine: Add FloorHeight query method

- Architecture_Engine/Architecture_Engine.csproj
- Architecture_Engine/Modify/CleanRoom.cs
Fixes #1611 
@BingWangUS or @michaelhoehn to provide
> Architecture_Engine: Add CleanRoom modify method

- Geometry_Engine/Query/Bounds.cs
- Structure_Engine/Compute/Integrate.cs
- Structure_Engine/Compute/IntegrateSection.cs
Closes #1657 
Closes #1658 
https://burohappold.sharepoint.com/:f:/s/BHoM/EsCnlfKi1CVKl2RxG-SXCEUBuXEWwwikU8m6BwmSjoqaVQ?e=7tKiR3
- Adds Geometry.Query.Bounds(List<BoundingBox> boxes)
> Structure_Engine: Off-centre section issues

- Environment_Engine/Create/Gains.cs
UpdatedEngineMethodforCreateGain
https://github.com/BHoM/BHoM/pull/799
Closes #
> Environments_Engine: Updated Engine Method for Create Gain

- Environment_Engine/Environment_Engine.csproj
- Environment_Engine/Query/HasMergeablePropertiesWith.cs
- Environment_Engine/Query/MaterialComposition.cs
- Environment_Engine/Query/SolidVolume.cs
- Physical_Engine/Query/MaterialComposition.cs
> Environment_Engine: Add Interface methods

- Environment_Engine/Query/UniqueConstructions.cs
> Environment_Engine: Add UniqueConstructions for Openings

- Structure_Engine/Query/HasMergeablePropertiesWith.cs
- Structure_Engine/Structure_Engine.csproj
Partially handles #1674 
Fixes for the `Edge`s which is the pressing matter
https://burohappold.sharepoint.com/:f:/s/BHoM/En26cTEF-h1Al4qHoBRqSi4Bx81OZ8GJFuI8UHOWWuSiEg?e=obT54u
> Structure_Engine: Implement HasMergeablePropertiesWith

- Spatial_Engine/Modify/RoundCoordinates.cs
- Spatial_Engine/Spatial_Engine.csproj
Closes #1676 
Extends the `RoundCoordinates` functionality to `IElement`s
https://burohappold.sharepoint.com/:u:/s/BHoM/EZ2JPv2CavlKiRyACCEe5FMBonKL_JbfAxvRQ0eeUPELSA?e=cyh71C
> Spatial_Engine: Add RoundCoordinates

- Environment_Engine/Compute/GenerateCylindricalFarfield.cs
- Environment_Engine/Environment_Engine.csproj
Fixes #1720 
Existing by @RasmusCanfjorden
> Environment_Engine: Add GenerateCylindricalFarfield method

- Architecture_Engine/Architecture_Engine.csproj
- Architecture_Engine/Query/HasMergeablePropertiesWith.cs
> Architecture_Engine: Implement HasMergeablePropertiesWith

- Environment_Engine/Environment_Engine.csproj
- Environment_Engine/Query/OpeningsByType.cs
> Environment_Engine: Add OpeningsByType Query method

- Physical_Engine/Physical_Engine.csproj
- Physical_Engine/Query/HasMergeablePropertiesWith.cs
Closes #1673 
No Idea how to check if framing elements pointing towards each other with mirrored versions of each others profiles are correct. So either if there's a suggestion on how to do that or we'll put that  off in a new issue after some mirroring method for Profiles is implemented @IsakNaslundBh 
https://burohappold.sharepoint.com/:f:/s/BHoM/Ej0PXCOWAKhIpjcljaqtlDEB_3RPJe3GN7-EHP6YpVVJVw?e=2R3ofC
> Physical_Engine: Implement HasMergeablePropertiesWith

- Reflection_Engine/Create/MethodBase.cs
Closes #1731
See issue for full details
> Reflection_Engine: Fix MethodBase() method

- Environment_Engine/Environment_Engine.csproj
- Environment_Engine/Query/Area.cs
> Environment_Engine: Remove Common_Engine reference

- Serialiser_Engine/Convert/Bson.cs
Closes #1680
Fell free obviously to test for as many types as you can to make sure it doesn't break anything. There are still a very small number of types still failing so you might have to compare with and without the PR to make sure.
> Serialisation_Engine: Fix serialisation of objects with Id property

- Reflection_Engine/Query/UnderlyingType.cs
https://github.com/BHoM/BHoM/pull/853
https://github.com/BHoM/BHoM_Adapter/pull/228
(at least for testing)
Supports https://github.com/BHoM/BHoM_UI/pull/253
Closes #1739 
The idea here is that `IEnumerable` types like `FragmentSet` and `ModuleSet` should be treated as List input in the UI even if they are not generic types. To solve that problem, I updated the `UnderlyingType` method to look for a constructor that takes a list as input (only for `IEnumerable` classes obviously).
While you can call `UnderlyingType` directly from the UI, the best way to test this is within the context of https://github.com/BHoM/BHoM_UI/pull/253.
> Reflection_Engine: Non-generic treated as list when calling UnderlyingType()

- Graphics_Engine/Convert/ToRenderMesh.cs
- Graphics_Engine/Graphics_Engine.csproj
Is a part of #1694
On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?viewid=a5a93cba%2Dfcca%2D46cc%2Da31a%2D80b8d5cbfd7b&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FTest%20Scripts%2FBHoM%5FEngine%2FGraphics%5FEngine%2FGraphics%5FEngine%2DIssue1694%2DToRenderMesh)
> ToRenderMesh() convert added for oM.Geometry.Mesh

- Structure_Engine/Create/Elements/Panel.cs
- Structure_Engine/Query/Geometry.cs
- Structure_Engine/Structure_Engine.csproj
#1624 
and allows for #1759 to work
> Structure_Engine: Remove Common_Engine reference

- Environment_Engine/Compute/ExtrudeToVolume.cs
- Environment_Engine/Environment_Engine.csproj
- Environment_Engine/Modify/SetGeometry.cs
- Environment_Engine/Modify/SetOutlineElements1D.cs
- Environment_Engine/Query/Azimuth.cs
- Environment_Engine/Query/Geometry.cs
- Environment_Engine/Query/HasMergeablePropertiesWith.cs
- Environment_Engine/Query/InvalidPanels.cs
- Environment_Engine/Query/NewElement1D.cs
- Environment_Engine/Query/OutlineElements1D.cs
- Environment_Engine/Query/Tilt.cs
Fixes #1782 
- Add interface elements to `Node`
- Add interface elements to `Space`
- Add `ExtrudeToVolume` method to `Space`
> Environment_Engine: Add Space manipulation methods

- Structure_Engine/Create/Elements/Panel.cs
Closes #1439
Add create method for panel accepting a planar surface
https://burohappold.sharepoint.com/:f:/s/BHoM/EnN5nbFKnhhMuZ3lkUJ8_kMBB1dErX78phwOvT8lD3RQow?e=uI9AH8
> Structure_Engine: Add create method for panel accepting a planar surface

- Environment_Engine/Create/Space.cs
Updated Space
https://github.com/BHoM/BHoM/pull/884
Closes #1791
> Environment_Engine: Modify Space Object

- Environment_Engine/Create/AnalysisGrid.cs
- Environment_Engine/Environment_Engine.csproj
> Environment_Engine: Add create for AnalysisGrid

- Environment_Engine/Create/AnalysisGrid.cs
https://github.com/BHoM/BHoM/pull/897
> Environment_Engine: Align to BHoM for AnalysisGrid change

- Data_Engine/Data_Engine.csproj
- Data_Engine/Query/Requests.cs
https://github.com/BHoM/BHoM/pull/890
Closes #1797
See https://github.com/BHoM/Revit_Toolkit/pull/731
> Data_Engine: ILogicalRequest.Requests query method implemented

- Environment_Engine/Modify/AddOpenings.cs
- Environment_Engine/Query/Level.cs
- Environment_Engine/Query/NormalAwayFromSpace.cs
- Environment_Engine/Query/PanelsByLevel.cs
- Environment_Engine/Query/PanelsByMaximumLevel.cs
- Environment_Engine/Query/PanelsByMinimumLevel.cs
- Environment_Engine/Query/PanelsContainingPoint.cs
- Environment_Engine/Query/StoreyGeometry.cs
Closes #1813 
Removed methods that where deprecated before "3.0"
> Environment_Engine: Removed deprecated methods

- Structure_Engine/Modify/ApplyModifiers.cs
- Structure_Engine/Query/Modifiers.cs
https://github.com/BHoM/BHoM/pull/895
Closes #1808
Making modifier methods depend on fragment rather than CustomData
As the methods using the fragment input and the return the same things as before, I think it should be safe to merge this before dependant PRs have been approved.
> Structure_Engine: Update modifier methods to work with new fragment isntead of custom data

- Reflection_Engine/Create/Output.cs
- Reflection_Engine/Query/Item.cs
https://github.com/BHoM/BHoM/pull/892
Closes #1801
> Reflection_Engine: Update item to reflect changes to Output

- Results_Engine/Query/Group.cs
- Results_Engine/Results_Engine.csproj
- Structure_Engine/Create/Elements/IElement1D/NewElement1D.cs
- Structure_Engine/Query/SelectCase.cs
- Structure_Engine/Structure_Engine.csproj
https://github.com/BHoM/BHoM/pull/911
Aligning with migration of Results from Common_oM to Analytical_oM.
Affects:
- Structure_Engine
- Results_Engine
> Structure_Results_Engine: Aligning with changes for migrating results to Analytical_oM

- Environment_Engine/Environment_Engine.csproj
- Environment_Engine/Query/FilterResults.cs
- Environment_Engine/Query/UniqueObjectIDs.cs
- Environment_Engine/Query/UniqueResultCases.cs
> Environment_Engine: Ability to filter mesh results

- Structure_Engine/Create/SectionProperties/SectionProfile.cs
> Structure_Engine: Fixed bug where deprecated method did not implement new method for FabricatedISectionProfile

- Structure_Engine/Create/Requests/IResultRequest.cs
https://github.com/BHoM/BHoM/pull/917
Closes #1836
> Structure_Engine: Add support for NodeModalMass for converting Request

- Data_Engine/Create/Domain.cs
- Data_Engine/Create/DomainBox.cs
- Data_Engine/Create/DomainTree.cs
- Data_Engine/Create/Node.cs
- Data_Engine/Data_Engine.csproj
- Data_Engine/Query/Children.cs
- Data_Engine/Query/ClosestData.cs
- Data_Engine/Query/FurthestSquareDistance.cs
- Data_Engine/Query/IsInRange.cs
- Data_Engine/Query/ItemsInRange.cs
- Data_Engine/Query/Values.cs
- Geometry_Engine/Convert/DomainBox.cs
- Geometry_Engine/Create/DomainTree.cs
- Geometry_Engine/Geometry_Engine.csproj
https://github.com/BHoM/BHoM/pull/914
The final version of #1740 
Closes https://github.com/BHoM/BHoM/issues/843
No major changes since last PRs version other than the descriptions.
https://burohappold.sharepoint.com/:u:/s/BHoM/EaZM91qyXmVAo4ddZrneV6wB_1m8DlJ-Eq_PbDIsAlHoSQ?e=hxg7KS
And a more lightweight version:
https://burohappold.sharepoint.com/:u:/s/BHoM/Ec3OChqs5IpAvnWqCFjkTm4BJP_IaX6Z52Fg7R4BTgzHXw?e=yaG3zj
- Create methods for: `Node<T>`, `Domain`, `DomainBox`, `DomainTree`
- Query methods for closest data and items in range
- Support Create methods in Geometry_Engine for `DomainTree`
> Data_Engine: Methods for DomainTree and Node

- Geometry_Engine/Query/Bounds.cs
Closes #710 
as title
The standard one is very broken, but the items still appear through the UI, and doubt adding null checks would do anything worse than having an null exception somewhere else in the code
> Geometry_Engine: null checks in Bounds

- Geometry_Engine/Query/IsSelfIntersecting.cs
Closes #1845 
as title
See issue
> Geometry_Engine: Fix IsSelfIntersecting

- Environment_Engine/Compute/SolarPosition.cs
- Environment_Engine/Convert/Degrees.cs
> Environment_Engine: Remove unit conversions

- Structure_Engine/Create/Requests/BarResultRequest.cs
- Structure_Engine/Create/Requests/GlobalResultRequest.cs
- Structure_Engine/Create/Requests/MeshResultRequest.cs
- Structure_Engine/Create/Requests/NodeResultRequest.cs
- Structure_Engine/Structure_Engine.csproj
Closes #1858 
Adding simple property assignment create methods for all structural requests to make sure they appear in the CreateRequest component
https://burohappold.sharepoint.com/:f:/s/BHoM/ElutJoVwEfNPtXzX3xU0_NcBzo6Yp4tYawH3R8cfahzjVQ?e=G3YwZa
> Structure_Engine: Adding simple create methods for result requests

- Environment_Engine/Environment_Engine.csproj
- Environment_Engine/Query/BottomLeft.cs
- Environment_Engine/Query/BottomRight.cs
- Environment_Engine/Query/IsLeft.cs
- Environment_Engine/Query/TopRight.cs
> Environment_Engine: Migrate code from IES_Toolkit

- Data_Engine/Create/LogicalAndRequest.cs
- Data_Engine/Create/LogicalNotRequest.cs
- Data_Engine/Create/LogicalOrRequest.cs
- Data_Engine/Create/SelectionRequest.cs
- Data_Engine/Data_Engine.csproj
https://github.com/BHoM/BHoM/pull/923
Closes #1848
Not needed: just open the UI and check whether the requests are available using _CreateRequest_ component.
> Data_Engine: Missing Create methods added for IRequests

- Diffing_Engine/Diffing_Engine.csproj
> Diffing_Engine: Added Newtonsoft.json.dll in xcopy post build event

- Geometry_Engine/Create/Vector.cs
- Geometry_Engine/Geometry_Engine.csproj
- Geometry_Engine/Modify/Flip.cs
- Geometry_Engine/Query/Clone.cs
- Geometry_Engine/Query/ClosestPoint.cs
- Geometry_Engine/Query/IsEqual.cs
- Geometry_Engine/Query/IsInPlane.cs
- Geometry_Engine/Query/IsNurbsCurve.cs
Closes #1771 
Closes #1772 
Closes #1878 
Closes #1616 
Closes #1879 
Added a bunch of small requested methods
https://burohappold.sharepoint.com/:u:/s/BHoM/EcsuiThG1spMufdZ7gsofIgB7vijPXV-FYZtBkBcNtwenA?e=e6OxIq
- Added Create Vector from two Points
- Added IsNurbsCurve
- Implemented: Clone, ClosestPoint, IsEqual and IsInPlane for PlanarSurface
- Added IsEqual for Basis
- Implemented Flip for NurbsCurve
> Geometry_Engine: Minor method addition

- Geometry_Engine/Convert/Mesh.cs
- Geometry_Engine/Create/Mesh3D.cs
- Geometry_Engine/Geometry_Engine.csproj
- Geometry_Engine/Query/Cells.cs
- Geometry_Engine/Query/ExternalFaceMesh.cs
- Geometry_Engine/Query/Normal.cs
https://github.com/BHoM/BHoM/pull/942
Closes #
Adds convert to regular Mesh
Query cells (as lists of faces)
Query Normals
Query ExternalFaceMesh
Needs Rhino PR for GH to be happy with the testfile
https://github.com/BHoM/Rhinoceros_Toolkit/pull/167
See oM
> Geometry_Engine: Support methods for Mesh3D

- Environment_Engine/Query/BottomLeft.cs
- Environment_Engine/Query/BottomRight.cs
- Environment_Engine/Query/NormalAwayFromSpace.cs
- Environment_Engine/Query/TopRight.cs
> Environment_Engine: Provide protection around some aspects of engine code

- Structure_Engine/Create/Requests/IResultRequest.cs
- Structure_Engine/Query/DeformedShape.cs
https://github.com/BHoM/BHoM/pull/972
> Structure_Engine: Added ModeShapes to ResultRequest and IDisplacements to DeformedShape

- Reflection_Engine/Convert/ToText.cs
- Reflection_Engine/Create/Type.cs
- Reflection_Engine/Query/PropertyValue.cs
- Serialiser_Engine/Objects/BsonSerializers/MethodBaseSerializer.cs
- Serialiser_Engine/Objects/BsonSerializers/TypeSerializer.cs
See https://github.com/BHoM/BHoM_UI/pull/297 for details
> Minor fixes required for BHoM UI refactoring

- Physical_Engine/Physical_Engine.csproj
- Structure_Engine/Compute/OrientationAngle.cs
- Structure_Engine/Create/Elements/Bar.cs
- Structure_Engine/Create/Elements/FEMesh.cs
- Structure_Engine/Create/Elements/Panel.cs
- Structure_Engine/Modify/OrientTowards.cs
- Structure_Engine/Modify/SetLocalOrientation.cs
- Structure_Engine/Modify/SetNormal.cs
- Structure_Engine/Query/CoordinateSystem.cs
- Structure_Engine/Query/LocalOrientation.cs
- Structure_Engine/Query/Normal.cs
- Structure_Engine/Structure_Engine.csproj
https://github.com/BHoM/BHoM/pull/974
Adding methods related to https://github.com/BHoM/BHoM/issues/963
Adding general method to support the addition of an orientationangle to Panel and FEMeshFace.
Centralising and aligning handling of orientation angle between bar and area element.
Some quality of life methods added.
Versioning test files and testfiles for general functionality. Note that re-building versioning toolkit is needed to test the versioning files.:
https://burohappold.sharepoint.com/:f:/s/BHoM/EgtVAo-WZLxMuZ4smLsbhm8BzqRseNyNO8QxuZBWV6qqMw?e=ZglInM
- Adding method for getting local orientation from Panel and FEMeshFaces
- Adding method for extracting CoordinateSystem(s) from Panel and FEMesh(Faces)
- Adding methods for setting local orientation(s) for Panels and FEMeshes
- …
> Structure_Engine: Add support for local orientation of Panels and FEMeshes, and Orient methods

- Environment_Engine/Modify/SetFloorPanels.cs
- Environment_Engine/Modify/SetWallPanels.cs
Fixes #1959 
@vbeardow to provide
> Environment_Engine: Fix panel type setting bug

- Structure_Engine/Query/HasAssignedObjectIds.cs
- Structure_Engine/Structure_Engine.csproj
Closes #875
Adding method checking if obejcts on the load all contain an specific adapter id.
https://burohappold.sharepoint.com/:f:/s/BHoM/Ei47BMo0kzhNpmJDXFRIHlABU8sbHtLiiE-ELNQ12IwLXw?e=NAdF1b
> Structure_Engine: Adding method for checking objects on loads id assignment

- Structure_Engine/Query/TorsionalConstant.cs
Closes #1977
Updating definition to match https://eurocodeapplied.com/design/en1993/shs-design-properties which is the same as used in BS EN 10210-2:2019
https://burohappold.sharepoint.com/:f:/s/BHoM/EjDM8rvuDEFLtM7SyVXbeCABNmrhszeNgbCetHjliwFhMw?e=KAYjzR
> Structure_Engine: Update Torsional constant calculation for BoxProfiles

- Reflection_Engine/Query/AssemblyList.cs
Closes #1991 
Make sure that the `GetInfo` component in Dynamo is now working correctly without error message
> Reflection_Engine: Fix ExtractAllAsemblies bug

- Data_Engine/Data_Engine.csproj
- Data_Engine/Query/CleanList.cs
- Data_Engine/Query/RemoveNulls.cs
Closes #1993 
Adding `CleanList` method critical for excel workflows.
Test functionality:
https://burohappold.sharepoint.com/:f:/s/BHoM/Eo3XCg9b5rlNteTRdW0oT0oBnfGJaotIe7sKZlWIHZb7OA?e=Z3fdi8
Test in workflow:
Cell I2 in the supported nodes tab:
https://burohappold.sharepoint.com/:f:/s/BHoM/EszNjShmWNFJpiMmQ1EdM7ABAa3i7rfMe8oa54uHFtbwxg?e=O1XXQR
> Data_Engine: Adding CleanList method

- Environment_Engine/Compute/MapToLevel.cs
Fixes #1999 
[Download here](https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/BHoM_Engine/Environment_Engine/Environment_Engine-%231999-MapToLevels/MapToLevel%20section.gh?csf=1&web=1&e=7jNoDW)
Boom 2000th PR/Issue!
> Environment_Engine: Fix bug in MapToLevels

- Reflection_Engine/Query/MethodList.cs
Closes #2001 
Recording exception message when failing to load methods to give more detail of what is failing.
> Reflection_Engine: Record message when failing to load methods

- Environment_Engine/Compute/MapSpaces.cs
- Environment_Engine/Environment_Engine.csproj
Closes #2026 
FYI @rboulton-BH
> Environment_Engine: Add map to space method

- Reflection_Engine/Query/OutputAttributes.cs
Closes #2050
See issue for details and testing procedure
> Reflection_Engine: Make sure outputs always have different names

- Reflection_Engine/Query/DefaultValueWarning.cs
- Reflection_Engine/Query/IsAutoConstructorAllowed.cs
- Reflection_Engine/Query/IsRequired.cs
- Reflection_Engine/Reflection_Engine.csproj
https://github.com/BHoM/BHoM/pull/1020
See the oM PR for more details
> Reflection_Engine: Adding attributes to better control auto-create components

- Environment_Engine/Environment_Engine.csproj
- Environment_Engine/Query/Cardinality.cs
- Environment_Engine/Query/Orientation.cs
Adds features to the orientation method, such as azimuthAngle, and also works when the  northangle is not 90 degrees
Closes #1976 
[Normal Orientation test.zip](https://github.com/BHoM/BHoM_Engine/files/5349372/Normal.Orientation.test.zip)
> Environment_Engine: Adds features to the orientation method 

- Environment_Engine/Compute/BooleanIntersect.cs
- Environment_Engine/Compute/EquipmentGain.cs
- Environment_Engine/Compute/LightingGain.cs
- Environment_Engine/Compute/MapSpaces.cs
- Environment_Engine/Compute/Occupancy.cs
- Environment_Engine/Compute/PeopleGain.cs
- Environment_Engine/Compute/PlugGain.cs
- Environment_Engine/Query/Polyline.cs
- Environment_Engine/Query/ToLines.cs
- Environment_Engine/Query/ToSpace.cs
Closes #2039
Makes it possible to map regions to another set of regions and then calculate the area percentage of the region that have been mapped as well as sort out regions that haven't been mapped.
[MapRegions.zip](https://github.com/BHoM/BHoM_Engine/files/5372545/MapRegions.zip)
> Environment_Engine: Update map to space method

- Geometry_Engine/Modify/Transform.cs
https://github.com/BHoM/BHoM/pull/1026
https://github.com/BHoM/Versioning_Toolkit/pull/101
See https://github.com/BHoM/BHoM/pull/1026 for details and testing
> Geometry_Engine: Update Transform BoundaryRepresentation to handle Volume Property

- Programming_Engine/Create/BlockNode.cs
- Programming_Engine/Create/LoopNode.cs
- Programming_Engine/Programming_Engine.csproj
https://github.com/BHoM/BHoM/pull/1028
See https://github.com/BHoM/BHoM/issues/1027 for details
> Programming_Engine: Migrate code from constructor of NodeBlock and LoopBlock to new Create methods

- Spatial_Engine/Query/Area.cs
Closes #2081 
[Test file](https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/BHoM_Engine/Spatial_Engine/Query/Spatial_Engine%20%232081%20Element2D%20Area.gh?csf=1&web=1&e=YKRqo7)
> Spatial_Engine: Explicit use of geometry engine in Area(IElement2D)

- Geometry_Engine/Query/IsVertical.cs
Closes #2083 
Simple null check added for IsVertical method.
> Geometry_Engine: Adding null checks for IsVertical

- Structure_Engine/Query/DeformedShape.cs
- Structure_Engine/Query/HasAssignedObjectIds.cs
- Structure_Engine/Query/PlotBarForce.cs
https://github.com/BHoM/BHoM/pull/1033
Aligning with changes in https://github.com/BHoM/BHoM/issues/1012
Updating the following methods to be searching for Ids in the fragments rather than the custom data:
- PlotBarForce
- DeformedShape
- HasAssignedObjectIds
> Structure_Engine: Aligning with changes to AdapterIds

- Data_Engine/Query/Linq/FilterBy.cs
Closes #2072 
Removing use of custom data from the FilterBy methods by instead relying on the PropertyValue method
https://burohappold.sharepoint.com/:f:/s/BHoM/Eujc0WCfFOdLi1EZhWDmGpYBkEqsH1c_cjTZ3pKbx3eNEA?e=H0woYG
> Data_Engine: Remove custom data

- MEP_Engine/Compute/PlumbingFixtureWaterDemandPerDay.cs
- MEP_Engine/MEP_Engine.csproj
https://github.com/BHoM/BHoM/pull/1059
Closes #2116 
[Test File](https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/ClimateEmergency_Toolkit/RemoveMethods.gh?csf=1&web=1&e=3Q0ddF)
- Addition of `PlumbingFixtureWaterDemandPerDay()`
> MEP_Engine: Support for ClimateEmergency Methods

- Environment_Engine/Compute/MapRegions.cs
- Environment_Engine/Environment_Engine.csproj
> Environment_Engine: Fix bug in MapRegions for wholly contained regions

- Environment_Engine/Modify/Copy.cs
- Environment_Engine/Modify/FixNormal.cs
- Environment_Engine/Modify/RemoveOpening.cs
- Environment_Engine/Modify/RemoveOpeningsByName.cs
- Environment_Engine/Modify/SetGeometry.cs
- Environment_Engine/Modify/SetInternalElements2D.cs
- Environment_Engine/Modify/SetOutlineElements1D.cs
- Environment_Engine/Modify/Split.cs
- Environment_Engine/Modify/SplitOpeningByGeometry.cs
- Environment_Engine/Modify/SplitPanelByGeometry.cs
- Environment_Engine/Query/NewElement1D.cs
> Environment_Engine: Tidy up clone methods

- MEP_Engine/Modify/SetGeometry.cs
> Tidy clone methods

- Reflection_Engine/Query/Description.cs
- Reflection_Engine/Query/OutputAttributes.cs
- Reflection_Engine/Query/OutputDescription.cs
https://github.com/BHoM/BHoM/pull/1068
Closes https://github.com/BHoM/BHoM/issues/1067
Create one of the components that take inputs with quantities, e.g. `BH.Engine.Data.Query.ClosestData`, then check if the input descriptions are OK.
- code updated to the changes made in https://github.com/BHoM/BHoM/pull/1068
This PR will not conflict with #2124.
> Reflection_Engine: Code updated to the changes introduced in BHoM #1068

- Reflection_Engine/Modify/SetPropertyValue.cs
Needed for this PR in BHoM_UI:  https://github.com/BHoM/BHoM_UI/pull/334
See BHoM_UI PR
> Reflection_Engine: Make it easy to clear the value of a property

- Architecture_Engine/Create/Theatron/ProfileOrigin.cs
- Architecture_Engine/Create/Theatron/SeatingBlock.cs
- Architecture_Engine/Modify/CleanRoom.cs
- Architecture_Engine/Modify/SetGeometry.cs
- Architecture_Engine/Modify/SetOutlineElements1D.cs
- Architecture_Engine/Query/NewElement1D.cs
> Architecture_Engine: Replace clone calls with calls to DeepClone or ShallowClone

- Physical_Engine/Create/IElement/IElement1D/NewElement1D.cs
- Physical_Engine/Modify/SetGeometry.cs
- Physical_Engine/Modify/SetInternalElements2D.cs
- Physical_Engine/Modify/SetOutlineElements1D.cs
> Physical_Engine: Replace calls to Clone methods with calls to Base DeepClone or ShallowClone

- Reflection_Engine/Convert/ToText.cs
Provides a more comprehensive fallback method for ToText. This is useful for this PR: https://github.com/BHoM/Grasshopper_Toolkit/pull/567
Can be reviewed with it or in isolation.
> Reflection_Engine: Update fallback method for ToText

- Reflection_Engine/Convert/ToText.cs
Fixes #2194 
Originally was a PR on [Grasshopper_Toolkit](https://github.com/BHoM/Grasshopper_Toolkit/pull/570) but moved here at @adecler request.
@adecler not sure if this is the right fix, this seemed to work (as seen in screenshot above) after compiling this branch against today's alpha (thus discarding the Grasshopper branch).
> Reflection_Engine: Fix Enum display in UI

- Geometry_Engine/Query/Normal.cs
- Spatial_Engine/Query/Normal.cs
Closes #2184
Adding descriptions to all `Normal()` methods.
Only the descriptions and arguments names are changed, however [here](https://burohappold.sharepoint.com/:f:/s/BHoM/Esd2eZj9Hc1Mkh5tar8m-NsBlIxJtyJ40zXatKwF4D3uOQ?e=2cGnWq) is the general tet file.
- Adding descriptions to all `Normal()` and `Normals()` methods in the `Geometry_Engine`.
As this one concerns mostly descriptions, any suggestions from more experienced English speakers will be very welcomed 😉
> Geometry_Engine: Adding descriptions to the Normal() methods

- Physical_Engine/Query/MaterialComposition.cs
- Physical_Engine/Query/SolidVolume.cs
https://github.com/BHoM/BHoM/pull/1103
Closes #2187 
[Test File](https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/BHoM/Physical_oM/Physical_oM-Issue1088-ExplicitBulk/ExplicitBulk.gh?csf=1&web=1&e=LwundV)
> Physical_Engine: ExplicitBulk required extension methods added

- Physical_Engine/Physical_Engine.csproj
- Physical_Engine/Query/Mass.cs
- Physical_Engine/Query/MaterialComposition.cs
- Physical_Engine/Query/SolidVolume.cs
https://github.com/BHoM/BHoM/pull/1099
Closes #2181 
[Here is a test file](https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/BHoM/Physical_oM/Physical_oM-Issue1096-AddConstructionProp/Physical_oM-%231096-AddConstructionProperty.gh?csf=1&web=1&e=Wxr7uM)
- Update `ISolidVolume()`
- Update `MaterialComposition()`
> Physical_Engine: IElementM required extension methods

- Structure_Engine/Create/Elements/Bar.cs
I didn't raise one, sorry. Discussed with @IsakNaslundBh though!
N/A
Sorry for the massive change to review!
> Structure_Engine: Remove whitespace in Bar create method

- MEP_Engine/Create/Elements/CableTraySectionProperty.cs
- MEP_Engine/Create/Elements/DuctSectionProperty.cs
- MEP_Engine/Create/Elements/PipeSectionProperty.cs
- MEP_Engine/Create/Elements/WireSectionProperty.cs
- MEP_Engine/MEP_Engine.csproj
- MEP_Engine/Query/MaterialComposition.cs
- MEP_Engine/Query/SolidVolume.cs
https://github.com/BHoM/BHoM/pull/1104
Closes #2126 
Closes #2119 
[Test file](https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/BHoM/MEP_oM/MEP_oM-%231064%20MEPMaterials.gh?csf=1&web=1&e=PXC2UR)
> MEP_Engine: Matter-based workflows required extension methods

- Data_Engine/Data_Engine.csproj
- Data_Engine/Query/Linq/FilterBy.cs
- Data_Engine/Query/Linq/GroupBy.cs
- Data_Engine/Query/Linq/OrderBy.cs
Closes #2203 
Adds method to group objects by their property values.
[GroupBy_test.zip](https://github.com/BHoM/BHoM_Engine/files/5636805/GroupBy_test.zip)
> Data_Engine: Group objects by property values

- Spatial_Engine/Create/ShapeProfiles/FreeFormProfile.cs
Closes #2209
Add option to control if the freeform profiles should be centre or not. Important for Facade workflows.
Please test any script using freefrom profiles @enarhi
> Spatial_Engine: Add option to centre FreeFormProfiles

- Structure_Engine/Modify/AddReinforcement.cs
- Structure_Engine/Modify/ApplyModifiers.cs
- Structure_Engine/Modify/Flip.cs
- Structure_Engine/Modify/OrientTowards.cs
- Structure_Engine/Modify/SetLocalOrientation.cs
- Structure_Engine/Modify/SetMaterial.cs
- Structure_Engine/Modify/SetNormal.cs
- Structure_Engine/Modify/SetReinforcement.cs
- Structure_Engine/Modify/SetStructuralFragment.cs
Closes #2201
Just compliance, should mean no functional change
> Structure_Engine: Replace calls to GetShallowClone with ShallowClone

- Reflection_Engine/Compute/RemoveEvent.cs
- Reflection_Engine/Reflection_Engine.csproj
Change requires by this BHoM_UI PR: https://github.com/BHoM/BHoM_UI/pull/339
> Reflection_Engine: Adding ability to remove events from log

- Facade_Engine/Create/Elements/Opening.cs
- Facade_Engine/Query/IsAdjacent.cs
Closes #2225 
Closes #2232 
Fixes bugs for construction creation on opening create method and adjacency check accounting for tolerance.
[TestFacadeEngineCreateConstructionAndAdjacency.zip](https://github.com/BHoM/BHoM_Engine/files/5676563/TestFacadeEngineCreateConstructionAndAdjacency.zip)
> Facade_Engine: Construction bugfix and adjacency tolerance bugfix

- Geometry_Engine/Query/BasisFunction.cs
- Geometry_Engine/Query/CurvatureAtParameter.cs
- Geometry_Engine/Query/DerivativeAtParameter.cs
- Geometry_Engine/Query/DerivativeFunction.cs
- Geometry_Engine/Query/PointAtParameter.cs
- Geometry_Engine/Query/PrincipalCurvatureAtParameter.cs
- Geometry_Engine/Query/TangentAtParameter.cs
Closes #2228
Original files from #2028 uploaded on SharePoint:
- [curve](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FIssue%2FBHoM%2FBHoM%5FEngine%2FGeometry%5FEngine%2F%232228%2DNurbsCurveParam%2Egh&parent=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FIssue%2FBHoM%2FBHoM%5FEngine%2FGeometry%5FEngine)
- [surface](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FIssue%2FBHoM%2FBHoM%5FEngine%2FGeometry%5FEngine%2F%232228%2DNurbsSurfaceParam%2Egh&parent=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FIssue%2FB …
> Geometry_Engine: nurbs curve and surface parameter normalized

- Diffing_Engine/Diffing_Engine.csproj
- Diffing_Engine/packages.config
- Reflection_Engine/Convert/ToText.cs
- Reflection_Engine/Query/TypeList.cs
Supports https://github.com/BHoM/BHoM_UI/pull/348
A few minor things needed to be fixed for the UI CI tests to work without crashing. See commit names. 
Make sure that the Ci tests in the UI can run properly. Otherwise, this is mainly some trivial changes that can be validated by code inspection.
@alelom , added you here just to make sure you are happy with the upgrade on the Compare-NET version. This is needed to align with the upgrade I did on the Test toolkit so the correct version of the dll ends up in the BHoM assemblies.
> BHoM_Engine:  Fixes needed for CI tests on the UI

- Reflection_Engine/Query/DistinctProperties.cs
Closes #1250 
Making DistinctProperties check if P is a fragment type, and if so, try to fetch it from the fragment List of the objects.
> Reflection_Engine: Adding check for Fragments in the DistinctProperties

- Spatial_Engine/Query/Thickness.cs
- Spatial_Engine/Spatial_Engine.csproj
Closes #2171 
[Here](https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/01_Test%20Scripts/BHoM_Engine/Spatial_Engine/Issues/Spatial_Engine-%232171-IProfileThicknessQuery/IProfileThickness.gh?csf=1&web=1&e=ozLBf5)
> Spatial_Engine: Query Thickness of IProfiles

- core.txt
Fixes #2264 
Ensure Azure CheckCore passes.
> CI/CD: Update core.txt for CheckCore

- BHoM_Engine/BHoM_Engine.csproj
- BHoM_Engine/Modify/AddFragment.cs
- BHoM_Engine/Query/CanTarget.cs
- BHoM_Engine/Query/UniquenessRestrictions.cs
https://github.com/BHoM/BHoM/pull/1093
See https://github.com/BHoM/BHoM/pull/1093 for details
> Reflection_Engine: Add support for new fragments attributes

- Reflection_Engine/Compute/RunExtensionMethod.cs
- Reflection_Engine/Query/BHoMVersion.cs
- Serialiser_Engine/Convert/Bson.cs
- Serialiser_Engine/Objects/BsonSerializers/MethodBaseSerializer.cs
- Serialiser_Engine/Objects/BsonSerializers/ObjectSerializer.cs
- Serialiser_Engine/Objects/BsonSerializers/TypeSerializer.cs
- Serialiser_Engine/Objects/MemberMapConventions/BHoMObjectDiscriminatorConvention.cs
- Serialiser_Engine/Objects/MemberMapConventions/GenericDiscriminatorConvention.cs
- Serialiser_Engine/Serialiser_Engine.csproj
- Versioning_Engine/Convert/ToNewVersion.cs
- Versioning_Engine/Modify/AddVersion.cs
- Versioning_Engine/Modify/RemoveVersion.cs
- Versioning_Engine/Query/UpgraderVersions.cs
- Versioning_Engine/Query/UpgradersToCall.cs
- Versioning_Engine/Query/Version.cs
- Versioning_Engine/Versioning_Engine.csproj
Related to https://github.com/BHoM/Versioning_Toolkit/pull/133
See https://github.com/BHoM/Versioning_Toolkit/pull/133
Note: This code also support the injection of the `_bhomVersion` in json but has the code that add it commented out as agreed so it make this PR forward compatible with next beta.
> Serialiser_Engine: Align to forward versioning

- Programming_Engine/Create/BlockNode.cs
- Programming_Engine/Create/LoopNode.cs
https://github.com/BHoM/BHoM/pull/1173
See https://github.com/BHoM/BHoM/pull/1173
> Programming_Engine: Remove ParentId property from INodeParam

- Serialiser_Engine/Convert/Bson.cs
- Serialiser_Engine/Convert/Json.cs
- Serialiser_Engine/Objects/BsonSerializers/BHoMCollectionSerializer.cs
- Serialiser_Engine/Objects/BsonSerializers/TypeSerializer.cs
- Serialiser_Engine/Serialiser_Engine.csproj
Closes #2289
Some types, objects, and methods were still not deserialising correctly. This PR aims to fix that.
https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/03_Alpha/BHoM/BHoM_Engine/Serialiser_Engine/Serialisation_Engine.gh?csf=1&web=1&e=7g2oQo
> Serialiser_Engine: Get all methods, objects, and type to serialise

- BHoM_Engine/Query/Geometry.cs
- BHoM_Engine/Query/Geometry3D.cs
Closes #2340
See the text in #2340.
Try to create a Physical Construction or Layer object. It should not return any error. See issue text for more info.
> Geometry_Engine: IGeometry and IGeometry3D to check if ExtensionMethod is found before calling it to avoid exposing error when not relevant

- Reflection_Engine/Compute/MakeGenericFromInputs.cs
Closes #2364
Fix the case where methods inputs have multiple levels of generics. For example `IEnumerable<IMesh<TNode, TFace>>` should accept a `List<FEMesh>`.
I had to completely rewrite the code for `MakeGenericFromInputs` to make it recursive. I find this version a lot simpler than the previous one as well but will have to be tested heavily to make sure I didn't break anything.
Don't forget the PR in the UI to make sure that `MakeGenericFromInputs` is actually called.
https://burohappold.sharepoint.com/:u:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/BHoM_Engine/Reflection_Engine/%232364-NestedGenericBug.gh?csf=1&web=1&e=xEvYtK
Note that `DisplayMeshResults` is still giving errors but the inputs arrive to the method in the correct format so it's purely due to errors inside …
> Reflection_Engine: Fix bug on method with nested generic inputs called from the UI

- Architecture_Engine/Architecture_Engine.csproj
- Architecture_Engine/Modify/Transform.cs
Contributes to resolving #2322
On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FBHoM%5FEngine%2FArchitecture%5FEngine%2F%232322%2DTransform%2Egh&parent=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FBHoM%5FEngine%2FArchitecture%5FEngine).
- `Transform` methods added for `Ceiling`, `CeilingTile` and `Opening`
> Architecture_Engine: Transform methods added for Ceiling, CeilingTile and Opening

- Physical_Engine/Query/Geometry3D.cs
Closes #2329
Try creating a Floor and display its layers like:
The extrusion of the floor is not "capped", also this is not accounting for openings in the floor. Targeted by #2360.
One solution will be to extrude the openings also - and then translate the planar srf (including openings crvs) to top and bottom
> Physical engine: adding geometry3D method for Physical Floor

- Architecture_Engine/Modify/Transform.cs
Contributes to resolving #2383
On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FBHoM%5FEngine%2FArchitecture%5FEngine%2F%232383%2DMissingTransforms%2Egh&parent=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FBHoM%5FEngine%2FArchitecture%5FEngine) - only `Room` transforms need to be checked (others come from previous PRs and were copied over to allow creating batch UT).
- `Transform` method added for `BH.oM.Architecture.Elements.Room`
> Architecture_Engine: missing Transform methods added

- Geometry_Engine/Compute/Split.cs
Closes #2406
On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FIssue%2FBHoM%2FBHoM%5FEngine%2FGeometry%5FEngine%2F%232406%2DStackOverflowOnSplit%2Egh&parent=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F01%5FIssue%2FBHoM%2FBHoM%5FEngine%2FGeometry%5FEngine)
- Infinite loop removed from `BH.Engine.Geometry.Compute.Split` in case of overlapping cutting lines
@FraserGreenroyd you are the originator so happy to get your review on it.
> Geometry_Engine: Infinite loop removed from Split in case of overlapping cutting lines

- Geometry_Engine/Modify/Project.cs
Closes #2430
On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FBHoM%5FEngine%2FGeometry%5FEngine%2F%232432%2DProjectOnPlaneBug&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4)
My first PR, please be patient 👼
> Geometry_Engine: point on plane projection fixed

- Serialiser_Engine/Compute/RegisterClassMap.cs
- Serialiser_Engine/Convert/Bson.cs
Closes #2451
Very minimalistic test on [SharePoint](http://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02_Current%2F12_Scripts%2F02_Pull%20Request%2FBHoM%2FBHoM_Engine%2FSerialiser_Engine%2F%232453-RegisterClassMaps&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4).
> Serialiser_Engine: RegisterClassMaps added for entire assemblies

- Library_Engine/Convert/ToText.cs
> Library_Engine: Handle nulls

- Matter_Engine/Create/MaterialComposition.cs
- Matter_Engine/Query/Density.cs
- Matter_Engine/Query/Mass.cs
- Matter_Engine/Query/SolidVolume.cs
- Physical_Engine/Create/Column.cs
- Physical_Engine/Create/Material.cs
- Physical_Engine/Create/Wall.cs
- Physical_Engine/Modify/SetGeometry.cs
- Physical_Engine/Modify/SetInternalElements2D.cs
- Physical_Engine/Modify/SetOutlineElements1D.cs
- Physical_Engine/Query/AverageProfileArea.cs
- Physical_Engine/Query/BottomCentreline.cs
- Physical_Engine/Query/ExternalPolyline.cs
- Physical_Engine/Query/Geometry3D.cs
- Physical_Engine/Query/HasMergeablePropertiesWith.cs
- Physical_Engine/Query/InternalElements2D.cs
- Physical_Engine/Query/InternalPolyline.cs
- Physical_Engine/Query/MaterialComposition.cs
- Physical_Engine/Query/Normal.cs
- Physical_Engine/Query/OutlineElements1D.cs
- Physical_Engine/Query/Polyline.cs
- Physical_Engine/Query/SolidVolume.cs
- Physical_Engine/Query/Thickness.cs
- Physical_Engine/Query/TopCentreline.cs
> Physical_Engine: Null handling

- Acoustic_Engine/Acoustic_Engine.csproj
- Acoustic_Engine/Create/Ray.cs
- Acoustic_Engine/Query/GainFactor.cs
- Acoustic_Engine/Query/Length.cs
- Acoustic_Engine/Query/Order.cs
- Acoustic_Engine/Query/Plane.cs
- Acoustic_Engine/Query/ReverbDistance.cs
- Acoustic_Engine/Query/SabineTime.cs
- Acoustic_Engine/Query/SoundLevel.cs
- Acoustic_Engine/Query/TimeConstant.cs
- Acoustic_Engine/Query/TravelTime.cs
> Acoustic_Engine: Handle nulls

- Humans_Engine/Create/Spectator.cs
- Humans_Engine/Humans_Engine.csproj
- Humans_Engine/Query/AvalueAnalysis.cs
- Humans_Engine/Query/CvalueAnalysis.cs
- Humans_Engine/Query/EvalueAnalysis.cs
- Humans_Engine/Query/TrackingLines.cs
> Humans_Engine: Handle nulls

- Analytical_Engine/Convert/Graph/ToDataVizObjects.cs
- Analytical_Engine/Convert/Graph/ToDotFormat.cs
- Analytical_Engine/Convert/Graph/ToRelation.cs
- Analytical_Engine/Create/Graph/Relation.cs
- Analytical_Engine/Modify/Graph/RemoveEntity.cs
- Analytical_Engine/Modify/Graph/RemoveIsolatedEntities.cs
- Analytical_Engine/Modify/Graph/Reverse.cs
- Analytical_Engine/Modify/Graph/UniqueEntityNames.cs
- Analytical_Engine/Modify/SetGeometry.cs
- Analytical_Engine/Modify/SetOutlineElements1D.cs
- Analytical_Engine/Query/Geometry.cs
- Analytical_Engine/Query/Graph/AStarShortestPath.cs
- Analytical_Engine/Query/Graph/Adjacency.cs
- Analytical_Engine/Query/Graph/Depth.cs
- Analytical_Engine/Query/Graph/Destinations.cs
- Analytical_Engine/Query/Graph/DijkstraShortestPath.cs
- Analytical_Engine/Query/Graph/Entities.cs
- Analytical_Engine/Query/Graph/Entity.cs
- Analytical_Engine/Query/Graph/EntityNeighbourhood.cs
- Analytical_Engine/Query/Graph/FilterEntities.cs
- Analytical_Engine/Query/Graph/FilterRelations.cs
- Analytical_Engine/Query/Graph/Incoming.cs
- Analytical_Engine/Query/Graph/IsolatedEntities.cs
- Analytical_Engine/Query/Graph/NotSinks.cs
- Analytical_Engine/Query/Graph/Relation.cs
- Analytical_Engine/Query/Graph/RelationLength.cs
- Analytical_Engine/Query/Graph/Sinks.cs
- Analytical_Engine/Query/Graph/Sources.cs
- Analytical_Engine/Query/Graph/SubGraphs.cs
- Analytical_Engine/Query/OutlineElements1D.cs
> Analytical_Engine: Handle nulls

- Graphics_Engine/Convert/ToRenderMesh.cs
- Graphics_Engine/Convert/ToSVGString.cs
- Graphics_Engine/Create/Marker.cs
- Graphics_Engine/Modify/RepresentationFragments/Boxes.cs
- Graphics_Engine/Modify/View/DependencyChart.cs
- Graphics_Engine/Modify/View/View.cs
- Graphics_Engine/Query/Bounds.cs
- Graphics_Engine/Query/Color.cs
- Graphics_Engine/Query/IsNumericType.cs
- Graphics_Engine/Query/Scales/Scale.cs
> Graphics_Engine: Handle nulls

- Data_Engine/Compute/FilterData.cs
- Data_Engine/Create/DiscretePoint.cs
- Data_Engine/Query/Axes.cs
- Data_Engine/Query/AxisExists.cs
- Data_Engine/Query/FirstValueAbove.cs
- Data_Engine/Query/FirstValueAt.cs
- Data_Engine/Query/FurthestSquareDistance.cs
- Data_Engine/Query/IsInRange.cs
- Data_Engine/Query/Requests.cs
- Data_Engine/Query/SquareDistance.cs
- Data_Engine/Query/Values.cs
- Data_Engine/Query/ValuesAbove.cs
- Data_Engine/Query/ValuesAt.cs
> Data_Engine: Handle nulls

- Facade_Engine/Create/Elements/Opening.cs
- Facade_Engine/Create/Elements/Panel.cs
- Facade_Engine/Query/Depth.cs
- Facade_Engine/Query/IsAdjacent.cs
- Facade_Engine/Query/MaterialComposition.cs
- Facade_Engine/Query/PrimaryPropertyName.cs
- Facade_Engine/Query/SimpleGeometry.cs
- Facade_Engine/Query/SolidVolume.cs
- Facade_Engine/Query/Width.cs
Fixes #2477 
Fixed some minor compliance as I went through @enarhi FYI.
> Facade_Engine: Handle nulls

- Facade_Engine/Compute/AdjacentElements.cs
- Facade_Engine/Compute/EdgeAdjacencies.cs
- Facade_Engine/Create/Elements/CurtainWall.cs
- Facade_Engine/Create/Elements/Opening.cs
- Facade_Engine/Create/Elements/Panel.cs
- Facade_Engine/Facade_Engine.csproj
- Facade_Engine/Modify/SetOffsetFromFacetoFaceDist.cs
- Facade_Engine/Query/ExternalEdges.cs
- Facade_Engine/Query/FrameEdgeType.cs
- Facade_Engine/Query/IsAdjacent.cs
Closes #2424 
This PR adds features for use friendly Facade Create methods leveraging new query methods for ExternalEdges and GetEdgeType as well as added functionality to previous adjacency methods. 
https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/BHoM_Engine/Facade_Engine/%232424-AdjacencyAndEdgeTypeFeatureAdd?csf=1&web=1&e=avaE7L
The test script accounts for the GetEdgeType Query method as well as checks for the Create methods that use it and the adjacency methods that have been added / changed.
> Facade_Engine: Added ExternalEdges, GetEdgeType, and corresponding Create Methods

- Environment_Engine/Compute/RegionNameMapping.cs
- Environment_Engine/Create/Panel.cs
- Environment_Engine/Environment_Engine.csproj
Closes https://github.com/BHoM/IES_Toolkit/issues/173
Makes it possible to add a panel type when creating a panel object.
[TestFile.zip](https://github.com/BHoM/BHoM_Engine/files/6701657/TestFile.zip)
> Environment_Engine: Add the option to change panel type for panel objects

- Environment_Engine/Compute/AssignSpaceTypeByPoint.cs
- Environment_Engine/Environment_Engine.csproj
Closes #2520 
Moves the AssignSpaceTypeByPoint methods to Compute folder and changes the output from void to a list of spaces
TBC
> Environment_Engine: Bug fixes on geometry methods

- MEP_Engine/MEP_Engine.csproj
> MEP_Engine: Fix project reference to Matter Engine

- Environment_Engine/Compute/TidyPanels.cs
- Environment_Engine/Query/Bottom.cs
- Environment_Engine/Query/ExplodeToParts.cs
- Environment_Engine/Query/Sides.cs
- Environment_Engine/Query/Top.cs
Closes #2540 
Fixes bugs for TidyPanels method and adds tolerances to Top, Bottom, Sides and ExplodeToParts methods
> Environment_Engine: Bug fixes for various methods

- MEP_Engine/Modify/SetGeometry.cs
- MEP_Engine/Query/Geometry.cs
[BHoM/BHoM#1248](https://github.com/BHoM/BHoM/pull/1248)
Closes #2509 
Adds support for geometry changes to the new fitting object
[Here](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?newTargetListUrl=%2Fsites%2FBHoM%2F02%5FCurrent&viewpath=%2Fsites%2FBHoM%2F02%5FCurrent%2FForms%2FAllItems%2Easpx&viewid=a5a93cba%2Dfcca%2D46cc%2Da31a%2D80b8d5cbfd7b&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FBHoM%2FMEP%5FoM%2F%231034%2DAddGenericFittingObject)
Modified `BH.Engine.MEP.Modify.SetGeometry`
Modified `BH.Engine.MEP.Query.Geometry`
> MEP_Engine: Add support for the new fitting object

- Environment_Engine/Compute/TidyPanels.cs
- Environment_Engine/Query/Polyline.cs
Closes #2544 
Includes a flipPanels option in tidyPanels to help with workflows, and fixing a stack overflow for the Polyline method for spaces
> Environment_Engine: Bug fixes to fix stack overflow & TidyPanels bug

- Analytical_Engine/Analytical_Engine.csproj
- Analytical_Engine/Modify/CleanRegion.cs
Fixes #2543 
[Available here](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?newTargetListUrl=%2Fsites%2FBHoM%2F02%5FCurrent&viewpath=%2Fsites%2FBHoM%2F02%5FCurrent%2FForms%2FAllItems%2Easpx&viewid=a5a93cba%2Dfcca%2D46cc%2Da31a%2D80b8d5cbfd7b&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FBHoM%5FEngine%2FEnvironment%5FEngine%2F%232549%2DCleanRegions)
> Analytical_Engine: Add CleanRegion method

- Environment_Engine/Modify/Transform.cs
> Environment_Engine: Remove calls to GetShallowClone

- Analytical_Engine/Modify/SetGeometry.cs
Closes #2565 
Replaced a call to Geometry.IClone with Engine.Base.DeepClone()
- Review the code itself to make sure it compiles and makes sense
- Run the standard testing procedure that involve the geometry engine
> Analytical_Engine: Replaced calls to IClone with calls to DeepClone

- Physical_Engine/Modify/Transform.cs
Closes #2555
Just compliance, should mean no functional change
> Physical_Engine: replace calls to GetShallowClone

- Analytical_Engine/Analytical_Engine.csproj
- Analytical_Engine/Query/IsContaining.cs
Fixes #2524 
[Available here](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?newTargetListUrl=%2Fsites%2FBHoM%2F02%5FCurrent&viewpath=%2Fsites%2FBHoM%2F02%5FCurrent%2FForms%2FAllItems%2Easpx&sortField=LinkFilename&isAscending=true&viewid=a5a93cba%2Dfcca%2D46cc%2Da31a%2D80b8d5cbfd7b&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FBHoM%5FEngine%2FEnvironment%5FEngine%2F%232567%2DRegionsContainingPoints)
> Analytical_Engine: Add Region IsContaining method

- Lighting_Engine/Modify/Transform.cs
> Lighting_Engine: Remove calls to GetShallowClone

- Security_Engine/Modify/Transform.cs
> Security_Engine: Remove calls to GetShallowClone

- MEP_Engine/Modify/Transform.cs
Closes #2557
Just compliance, should mean no functional change
> MEP_Engine: replace calls to GetShallowClone

- Facade_Engine/Modify/Transform.cs
- Structure_Engine/Modify/Transform.cs
Closes #2551 
Just compliance, should mean no functional change
> Facade_Engine: replace calls to GetShallowClone 

- Architecture_Engine/Architecture_Engine.csproj
- Architecture_Engine/Create/BuildersWork/Opening.cs
- Architecture_Engine/Modify/SetGeometry.cs
- Architecture_Engine/Query/Geometry.cs
- Architecture_Engine/Query/HasMergeablePropertiesWith.cs
https://github.com/BHoM/BHoM/pull/1258
Closes #
On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FBHoM%5FEngine%2FArchitecture%5FEngine%2F%232572%2DBuildersWorkOpening0D&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4)
> Architecture_Engine: IElement0D methods added to Architecture.BuildersWork.Opening

- Diffing_Engine/Compute/DiffWithFragmentId.cs
> Diffing_Engine: DiffWithFragmentId to pass the DiffConfig correctly

- Structure_Engine/Modify/Transform.cs
Closes #2201
Restores some of the changes done in https://github.com/BHoM/BHoM_Engine/pull/2550 that somehow got lost.
> Structure_Engine: remove references to GetShallowClone

- Facade_Engine/Compute/UValueOpeningAW.cs
- Facade_Engine/Facade_Engine.csproj
Closes #2547 
Added new method for calculating U-value of opening using area weighting calculations
https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/BHoM_Engine/Facade_Engine/%232547-UValueAreaWeightCalculation?csf=1&web=1&e=nGl7bv
> Facade_Engine: Calculation Method to translate section U-values to Effective U-values by Area Weighting

- Library_Engine/Library_Engine.csproj
- Library_Engine/Query/IsPrototype.cs
> Library_Engine: Add method for checking if Dataset is Prototype

- Geometry_Engine/Create/PlanarSurface.cs
Closes #2593
On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FBHoM%5FEngine%2FGeometry%5FEngine%2F%232594%2DPlanarSurfaceWithoutOpeningBug&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4)
> Geometry_Engine: Planar surface creation without openings fixed

- Results_Engine/Query/Group.cs
- Results_Engine/Query/MapResults.cs
- Structure_Engine/Query/SelectCase.cs
https://github.com/BHoM/BHoM/pull/1279
Closes https://github.com/BHoM/BHoM_Engine/issues/2603
Aligns to https://github.com/BHoM/BHoM/pull/1279, updating the bare minimum of methods in order to support the changes.
Methods that operated on the previous version of `IResult` that can now rely on more basics implementations of the new `IResult` interface. For example, [`GroupByObjectId()`](https://github.com/BHoM/BHoM_Engine/pull/2604/commits/557e8c5c58336d2bde269a9951ee104dc9b0de83#diff-c1af917ae24d685e82f66723bee09560eefe1308c03a5c7f77f90dfe84164f39R45-R48) and [`GroupByTimeStep()`](https://github.com/BHoM/BHoM_Engine/pull/2604/commits/557e8c5c58336d2bde269a9951ee104dc9b0de83#diff-c1af917ae24d685e82f66723bee09560eefe1308c03a5c7f77f90dfe84164f39R52-R55) now operate respectively on …
> Aligning to IResult interface reformulation

- Structure_Engine/Query/Description.cs
> Structure_Engine: rename DOF f to o

- Graphics_Engine/Graphics_Engine.csproj
- Graphics_Engine/Query/RenderMesh.cs
Closes #2624
Added a `BH.Engine.Graphics.Query.RenderMesh(IObject obj)` method. This currently does two searches. First, it looks for an `IRenderMesh` extension method first, which is currently defined in the TriangleNet_Toolkit. If that is not found, then a `RenderMesh` extension method for the given object is searched. As we centralise the Meshing functionality more, we will be able to remove the former search.
What this accomplishes is that we can compute the representation/rendermesh of objects only by referencing the Graphics_Engine.
https://burohappold.sharepoint.com/:u:/s/BHoM/Ece-Cznw65xKr1saRkBX300BmOvYL2jvOXE0mav1GNE7kg?e=pNLRs6
The script should return `RenderMesh`es for several objects/combinations of objects.
- Added a `BH.Engine.Graphics.Query.RenderMesh(IObject obj)` …
> Graphics_Engine: added new RenderMesh extension method

- Environment_Engine/Query/IsExternal.cs
Closes #2525 
Added new method to determine whether a panel is external or internal. The new method sorts the panels using the isContaining method instead of the panel type.
The component is working by own testing
> Environment_Engine Updated Method for isExternal.cs

- BHoM_Engine/Create/Enumeration.cs
- Reflection_Engine/Compute/ParseEnum.cs
- Reflection_Engine/Modify/SetPropertyValue.cs
- Serialiser_Engine/Objects/MemberMapConventions/ImmutableTypeClassMapConventionFixed.cs
https://github.com/BHoM/BHoM/pull/1294
See https://github.com/BHoM/BHoM/pull/1294 for more details
TODO
This is currently the minimum required to have a working Embodied carbon toolkit. A proper workshop is needed before merging
> Base_Engine: Adding basic support for Enumeration objects

- BHoM_Engine/Create/Enumeration.cs
- Reflection_Engine/Compute/ParseEnum.cs
Closes #2697
See issue / title.
Not needed
> BHoM_Engine: Adding description to Create.Enumeration and Compute.ParseEnum

- Structure_Engine/Query/WarpingConstant.cs
Closes #2706 
- Adding warping constant calculations for TaperedFlange sections
- Adding Angle sections to list of sections that return 0 value without raising warning for WapringConstant
> Structure_Engine: Add warping constants for tapered flange and angle sections

- Matter_Engine/Create/MaterialComposition.cs
Does not depend on for compilation, but done in alignment with https://github.com/BHoM/BHoM/pull/1341 .
Checks done in constructor migrated to engine Create method.
Adding additional checks for Create method of material composition.
> Matter_Engine: Additional checks on Create for MaterialComposition

- Spatial_Engine/Modify/SetGeometry.cs
- Spatial_Engine/Query/Geometry.cs
Closes #2600
Adding Geometry method for ShapeProfiles to make them automatically visible in UIs
https://burohappold.sharepoint.com/:f:/s/BHoM/EjrFiU9GGw1Ik9_YKrViltkBvnp8YFZH3s8mN6vOiXMJOQ?e=QQrGJt
> Spatial_Engine: Adding Geometry method for shapeprofiles

- Physical_Engine/Create/Floor.cs
- Physical_Engine/Create/Roof.cs
- Physical_Engine/Create/Wall.cs
- Results_Engine/Query/MapResults.cs
- Structure_Engine/Query/Edges.cs
Closes #2627 
Fixed 5 instances of typos of the word 'objects'.
> BHoM_Engine: Fix typos

- Data_Engine/Query/Children.cs
> Data_Engine: tree children query added

- Data_Engine/Create/Table.cs
- Physical_Engine/Create/Floor.cs
- Physical_Engine/Create/Roof.cs
- Physical_Engine/Create/Wall.cs
Closes #2780
Fixed a typo and fixed the compliance warnings from https://github.com/BHoM/BHoM_Engine/pull/2759/files
> Physical_Engine: Fix typo and punctuations

- BHoM_Engine/Convert/ToFunc.cs
- Reflection_Engine/Query/PropertiesWithAttribute.cs
- Results_Engine/Query/DisplayElement1DResults.cs
- Results_Engine/Query/Group.cs
- Results_Engine/Query/IdentifierProperties.cs
https://github.com/BHoM/BHoM/pull/1383   
Closes #2794 
- Adding method for extracting all properties that have a particular attribute assigned, allowing checking base type as well as interface for the particular attribute
- Adding methods for finding names of properties of results that have identifier attributes assigned
- Adding grouping methods making use of the attributes
- Updating DisplayELement1D result to make use of the GroupByScenario method
https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/BHoM/Analytical_oM/%231383-Add-identifier-categorisation-attribute-for-results?csf=1&web=1&e=9V9ApA
> Results_Engine: Adding method for grouping by types of Identifiers

- Structure_Engine/Query/AverageThickness.cs
- Structure_Engine/Query/Description.cs
- Structure_Engine/Query/MassPerArea.cs
- Structure_Engine/Query/TotalThickness.cs
Closes #2799 
https://burohappold.sharepoint.com/:f:/r/sites/BHoM/02_Current/12_Scripts/02_Pull%20Request/BHoM/BHoM_Engine/Structure_Engine/%232800-Add-LayeredShell-Methods?csf=1&web=1&e=w99257
> Structure_Engine: Add layered shell methods

- Structure_Engine/Create/Framing/FramingElement.cs
- Structure_Engine/Query/HasReinforcement.cs
- Structure_Engine/Query/ReinforcementLayout.cs
Closes #2829
- Adding method for checking if a Bar has any reinforcement applied
- Calling the checking method when creating Bars from Framing
https://burohappold.sharepoint.com/:f:/s/BHoM/EmAT8FrB1wRGkG6PmYkSWhIBfZWrqUF2nrGNlt6IHeZ8nA?e=RKU5Tp
> Structure_Engine: Add check if bar contains reinforcement

- Data_Engine/Modify/Round.cs
Closes [#308](https://github.com/BHoM/TAS_Toolkit/issues/308)
Moved Round method from TAS_Toolkit to Data_Engine.
> Data_Engine: Add Round method from TAS_Toolkit

- Analytical_Engine/Modify/Graph/ProjectGraph.cs
- Analytical_Engine/Query/Geometry.cs
- Analytical_Engine/Query/Graph/Adjacency.cs
- Analytical_Engine/Query/Graph/Depth.cs
- Analytical_Engine/Query/Graph/EntityNeighbourhood.cs
- Analytical_Engine/Query/Graph/IsolatedEntities.cs
Closes #2809
Closes #2754
Closes #2433
Closes #2165
Various tweaks and refactoring's so drastically improve the performance of some of the Graph methods, by use of Lookups, dictionaries etc, and general rejigging the way the code run to dramatically improve the performance.
https://burohappold.sharepoint.com/:f:/s/BHoM/Eu87lOuPfq1BvmoimITDszkBCtuwbKUadANis4NDer5_jQ?e=rHLXyK
- Significant speed improvement to Adjacency method
- Complete rewrite of EntityNeighbourhood to significantly quicker method making use of the Depth method. Most notable performance can be seen when finding Neighbourhood in both directions, and slightly larger Depth.
- Rewrite of the Geometry method for it to display more geometries, if set, and significant speed upgrade.
- Rewrite the way ProjectGraph works from …
> Analytical_Engine: Refactor and efficiency of graph methods

- Matter_Engine/Query/MaterialComposition.cs
- Matter_Engine/Query/SolidVolume.cs
Closes #2933
Adds PreviousVersion attributes that were missed in https://github.com/BHoM/BHoM_Engine/pull/2897
> Matter_Engine: Add missing PreviousVersion Attributes

- Serialiser_Engine/Compute/RegisterClassMap.cs
- Serialiser_Engine/Convert/Bson.cs
- Serialiser_Engine/Serialiser_Engine.csproj
- Versioning_Engine/Versioning_Engine.csproj
> Upgrade to Mongo version 2.18

- Graphics_Engine/Modify/SetDefaultGradient.cs
- Structure_Engine/Query/Default.cs
https://github.com/BHoM/BHoM_Datasets/pull/122
Aligns hardcoded paths to datasets migrated to discipline superfolder.
> Structure_Engine: Align with migration of Structures datasets to subfolder

- Geometry_Engine/Modify/ProjectAlong.cs
- Geometry_Engine/Query/Direction.cs
- Geometry_Engine/Query/Normal.cs
Closes #320 
Closes #391 (becomes redundant as the method is being removed)
Correcting the names of some methods in the Geometry_Engine
> Geometry_Engine: Fix wrongly named methods

- Serialiser_Engine/Compute/RegisterClassMap.cs
Fixes #2995 
[Available here](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FBHoM%5FEngine%2FSerialiser%5FEngine%2F%232996%2DMultipleDiscriminator&viewid=a5a93cba%2Dfcca%2D46cc%2Da31a%2D80b8d5cbfd7b) - **note this requires Test_Toolkit to be built to run**
> Serialiser_Engine: Prevent duplicated types being registered

- BHoM_Engine/Convert/ToText.cs
- BHoM_Engine/Query/InputExposure.cs
> BHoM_Engine: Update MethodBase ToText to include denotation of hidden inputs

- Structure_Engine/Compute/ShearAreaPolyline.cs
- Structure_Engine/Query/IsVertical.cs
- Structure_Engine/Query/ShearArea.cs
Closes #3077 
- moved linked structural derivation page to DocumentationURL
> Structure_Engine: Updated DocumentationURL

- BHoM_Engine/Query/BHoMWebsiteURL.cs
Added method to generate up-to-date BHoM website URL
Closes #3081 
- Method call that returns up-to-date BHoM website URL
> BHoM_Engine: Added BHoMWebsiteURL.cs

- Reflection_Engine/Compute/OpenHelpPage.cs
BHoMWebsiteURL.cs, see pull request: [3082](https://github.com/BHoM/BHoM_Engine/pull/3082)
Closes #3074 
- Calls BHoMWebsiteURL to get URL instead of storing URL as constant value.
> Reflection_Engine: Updated URL to call BHoMWebsiteURL

- .ci/BHoMBot/Nuget/BHoM.Engine.nuspec
> BHoM_Engine: Add nuspec template file

- Geometry_Engine/Compute/RowEchelonForm.cs
> Geometry_Engine: Fix spelling in input attribute of RowEchelonForm

- Geometry_Engine/Compute/CountNonZeroRows.cs
> Geometry_Engine: Fix spelling of description in CountNonZeroRows

- BHoM_Engine/Compute/ParseEnum.cs
> BHoM_Engine: Add ParseEnum method for int value and add ignoreCase option for string conversion

- Geometry_Engine/Query/IsContaining.cs
> Geometry_Engine:  Changing from colleciton to collection in IsContaining.

- Environment_Engine/Modify/AssignGenericConstructions.cs
> Environment_Engine: Changing note wording

- Analytical_Engine/Create/Graph/Graph.cs
Checks against Dictionary Duplicated Key added
Closes #3192
> Analytical_Engine: Resolve Dictionary Key Duplication Error

- .ci/BHoMBot/Nuget/BHoM.Engine.nuspec
Closes #3196 
removed duplicate reference to net standard library
> .ci: removed duplicate reference

- Serialiser_Engine/Compute/Deserialise/Nullable.cs
> Serialiser_Engine: Fix stack overflow when deserialising nullable items

- Environment_Engine/Modify/ReplaceSpaceName.cs
> Environment_Engine: adding replace space name method

- BHoM_Engine/Query/BHoMFolder.cs
Closes #3218 
replaced reference to C: so that users not using C: can use the BHoM.
> BHoM_Engine: replaced C:/ProgramData with SpecialFolder construct

- Structure_Engine/Query/AnalyticalBars.cs
Closes #1406
Checking if the property is null and displaying a more informative error message.
> Structure_Engine: Checking if property is null in AnalyticalBars

- Geometry_Engine/Convert/Polyline.cs
- Geometry_Engine/Query/Integration.cs
- Geometry_Engine/Query/SliceAt.cs
Closes #502 
The following methods have been converted into extension methods:
- `ToPolyline(this Line)`
- `ToPolyline(this PolyLine)`
- `IToPolyline(this ICurve)`
- `ToPolyline(this ICurve)`
- `AreaIntegration(this List<IntegrationSlice>, double, double, double, ref double)`
- `AreaIntegration(this List<IntegrationSlice>, double, double, double, double)`
- `AreaIntegration(this List<IntegrationSlice>, double, double, double, double, double, double)`
- `AreaIntegration(this List<IntegrationSlice>, Vector, ICurve, double, double, ref double)`
- `AreaIntegration(this List<IntegrationSlice>, List<IntegrationSlice>, Vector, ICurve, double, double, ref double)`
- `SliceAt(this IList<ICurve>, double, double, Plane, double)`
Place each component and check that no error occurs when using the …
> Geometry_Engine: make all methods extension methods.

- Diffing_Engine/Compute/DiffWithCustomIds.cs
- Diffing_Engine/Convert/TryParseObjectToGuid.cs
- Diffing_Engine/Create/Delta.cs
https://github.com/BHoM/BHoM/pull/1583
> Diffing_Engine: Align to changes from Id to ID

- Spatial_Engine/Create/ShapeProfiles/CircleProfile.cs
> Spatial_Engine: Update description for create CircleProfile

- BHoM_Engine/Modify/ShiftList.cs
Closes #3273
On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?RootFolder=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FBHoM%5FEngine%2FBHoM%5FEngine%2F%233273%2DShiftListBug&FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4)
> BHoM_Engine: wrapping fixed in ShiftList method

- Settings_Engine/Compute/LoadSettings.cs
Closes #3303 
Changed new method name to LoadSettingsFromFile.
> Settings_Engine: Change LoadSettings method name to avoid conflicts

- BHoM_Engine/Compute/RecordEvent.cs
- BHoM_Engine/Query/IsSuppressing.cs
- BHoM_Engine/Query/IsThrowingErrors.cs
> BHoM_Engine: Add methods to query the current event log suppression state

- BHoM_Engine/Compute/MakeGenericFromInputs.cs
- BHoM_Engine/Compute/TryRunExtensionMethod.cs
- BHoM_Engine/Query/ExtensionMethodHierarchy.cs
- BHoM_Engine/Query/ExtensionMethodToCall.cs
- BHoM_Engine/Query/IsNullable.cs
- BHoM_Engine/Versioning_73.json
Closes #3393
On [SharePoint](https://burohappold.sharepoint.com/sites/BHoM/02_Current/Forms/AllItems.aspx?FolderCTID=0x0120008122C8891F89054B8ACED0196C70DFC4&id=%2Fsites%2FBHoM%2F02%5FCurrent%2F12%5FScripts%2F02%5FPull%20Request%2FBHoM%2FBHoM%5FEngine%2FBHoM%5FEngine%2F%233397%2DNullsInTryRunExtensionMethod).
To run the script, add the following snippet into any engine project that has required dependencies:
```C#
// Pass ICurve as 1st argument
// Should bind if 2nd argument != null
// Should not bind if 2nd argument == null
public static void AmbiguityTest1(this ICurve curve, Point point)
{
}
// Pass ICurve as 1st argument
// Should bind if 2nd argument != null
// Should not bind if 2nd argument == null
public static void AmbiguityTest1(this ICurve curve, Vector vector)
{
}
// Pass …
```
> BHoM_Engine: null inputs enabled in TryRunExtensionMethod

- .ci/unit-tests/Base_Engine_Tests/Compute/TryRunExtensionMethod.cs
- BHoM_Engine/Query/NumericalApproximation.cs
> BHoM_Engine: documentation compliance fixed

- Verification_Engine/Compute/TryGetValueFromSource.cs
- Verification_Engine/Compute/VerifyCondition.cs
Closes #3466
See https://github.com/BHoM/BHoM_Engine/issues/3466
> Verification_Engine: extraction of nested properties via TryGetValueFromSource fixed

- .ci/unit-tests/Base_Engine_Tests/Query/IsNumeric.cs
- .ci/unit-tests/Base_Engine_Tests/Query/IsNumericIntegralType.cs
- .ci/unit-tests/Base_Engine_Tests/Query/Unpack.cs
- .ci/unit-tests/Serialiser_Engine_Tests/BaseLoader.cs
- .ci/unit-tests/Serialiser_Engine_Tests/Helpers/CanReplaceMethodWithType.cs
- .ci/unit-tests/Serialiser_Engine_Tests/Helpers/TemporaryLogFolder.cs
- .ci/unit-tests/Serialiser_Engine_Tests/Helpers/TemporaryLogPath.cs
- .ci/unit-tests/Structure_Engine_Tests/Query/Geometry.cs
- .ci/unit-tests/Structure_Engine_Tests/Query/Geometry3D.cs
Closes #3473 
Add missing descriptions for test methods. Should be the final leftovers to have 0 compliance errors in the Engine once the tests have been updated on the bots.
Not required. Simply added descriptions
> Add missing descriptions for Tests

- Verification_Engine/Verification_Engine.csproj
Closes #3484
Check whether Verification_Engine gets added to BHoM\Assemblies folder on Release build config.
> release build fixed for Verification_Engine

- Verification_Engine/Verification_Engine.csproj
Closes #3508
Passing core check should be enough of a test.
> Verification_Engine: references fixed

- Versioning_Engine/Convert/ToNewVersion.cs
Closes #3521
Hardcoded string for stack trace for versioning events. This is to drastically reduce RAM usage for cases where a lot of versioning is done. Also gives a massive speedup for files with a lot of versioning.
> Default message for stack trace for verisoning
